<?php

use Illuminate\Database\Seeder;

class AnamnesesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('Anamneses')->delete();
        
        \DB::table('Anamneses')->insert(array (
            0 => 
            array (
                'id' => 1,
                'possui_doenca' => 2,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 2,
                'peso' => 83.0,
                'altura' => 1.73,
                'fumante' => 2,
                'cirurgia' => 1,
                'dor_muscular' => 2,
                'dor_ossea' => 2,
                'dor_articular' => 2,
                'atestado' => 2,
                'observacao' => NULL,
                'ano' => 2015,
                'pessoas_id' => 1,
                'created_at' => '2018-12-26 15:25:07',
                'updated_at' => '2018-12-26 15:25:07',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 3,
                'possui_doenca' => 1,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 1,
                'peso' => 60.0,
                'altura' => 1.5,
                'fumante' => 2,
                'cirurgia' => 1,
                'dor_muscular' => 2,
                'dor_ossea' => 2,
                'dor_articular' => 2,
                'atestado' => 2,
                'observacao' => 'Possui óculos',
                'ano' => 2015,
                'pessoas_id' => 3,
                'created_at' => '2018-12-27 12:16:50',
                'updated_at' => '2018-12-27 12:16:50',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 4,
                'possui_doenca' => 1,
                'toma_medicacao' => 2,
                'alergia_medicacao' => 2,
                'peso' => 71.0,
                'altura' => 1.69,
                'fumante' => 1,
                'cirurgia' => 1,
                'dor_muscular' => 1,
                'dor_ossea' => 2,
                'dor_articular' => 2,
                'atestado' => 2,
                'observacao' => NULL,
                'ano' => 2015,
                'pessoas_id' => 4,
                'created_at' => '2018-12-27 12:24:05',
                'updated_at' => '2018-12-27 12:24:05',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 7,
                'possui_doenca' => 2,
                'toma_medicacao' => 2,
                'alergia_medicacao' => 2,
                'peso' => 58.1,
                'altura' => 1.7,
                'fumante' => 1,
                'cirurgia' => 2,
                'dor_muscular' => 2,
                'dor_ossea' => 2,
                'dor_articular' => 2,
                'atestado' => 2,
                'observacao' => NULL,
                'ano' => 2015,
                'pessoas_id' => 7,
                'created_at' => '2018-12-27 12:37:49',
                'updated_at' => '2018-12-27 12:37:49',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 8,
                'possui_doenca' => 1,
                'toma_medicacao' => 2,
                'alergia_medicacao' => 2,
                'peso' => 90.0,
                'altura' => 1.6800000000000002,
                'fumante' => 2,
                'cirurgia' => 1,
                'dor_muscular' => 2,
                'dor_ossea' => 1,
                'dor_articular' => 1,
                'atestado' => 2,
                'observacao' => 'Cansaço físico depois de meia hora',
                'ano' => 2015,
                'pessoas_id' => 8,
                'created_at' => '2018-12-27 12:55:48',
                'updated_at' => '2018-12-27 12:55:48',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 9,
                'possui_doenca' => 1,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 2,
                'peso' => 76.82,
                'altura' => 1.65,
                'fumante' => 2,
                'cirurgia' => 2,
                'dor_muscular' => 2,
                'dor_ossea' => 2,
                'dor_articular' => 1,
                'atestado' => 2,
                'observacao' => 'Problemas na Perna',
                'ano' => 2015,
                'pessoas_id' => 9,
                'created_at' => '2018-12-27 13:00:18',
                'updated_at' => '2018-12-27 13:00:18',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 11,
                'possui_doenca' => 2,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 1,
                'peso' => 86.0,
                'altura' => 1.5699999999999998,
                'fumante' => 2,
                'cirurgia' => 1,
                'dor_muscular' => 2,
                'dor_ossea' => 2,
                'dor_articular' => 2,
                'atestado' => 2,
                'observacao' => 'Acima do peso',
                'ano' => 2015,
                'pessoas_id' => 11,
                'created_at' => '2018-12-27 13:11:58',
                'updated_at' => '2018-12-27 13:11:58',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 12,
                'possui_doenca' => 1,
                'toma_medicacao' => 2,
                'alergia_medicacao' => 2,
                'peso' => 50.9,
                'altura' => 1.58,
                'fumante' => 2,
                'cirurgia' => 2,
                'dor_muscular' => 2,
                'dor_ossea' => 2,
                'dor_articular' => 2,
                'atestado' => 2,
                'observacao' => 'Não pode ficar exposta ao sol',
                'ano' => 2015,
                'pessoas_id' => 12,
                'created_at' => '2018-12-27 13:18:02',
                'updated_at' => '2018-12-27 13:18:02',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 13,
                'possui_doenca' => 2,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 2,
                'peso' => 79.56,
                'altura' => 1.56,
                'fumante' => 2,
                'cirurgia' => 1,
                'dor_muscular' => 2,
                'dor_ossea' => 1,
                'dor_articular' => 1,
                'atestado' => 2,
                'observacao' => 'Físico Deteriorado',
                'ano' => 2015,
                'pessoas_id' => 13,
                'created_at' => '2018-12-27 13:22:43',
                'updated_at' => '2018-12-27 13:22:43',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 14,
                'possui_doenca' => 1,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 2,
                'peso' => 95.0,
                'altura' => 1.72,
                'fumante' => 2,
                'cirurgia' => 2,
                'dor_muscular' => 2,
                'dor_ossea' => 2,
                'dor_articular' => 2,
                'atestado' => 2,
                'observacao' => 'Idade avançada',
                'ano' => 2015,
                'pessoas_id' => 14,
                'created_at' => '2018-12-27 13:28:58',
                'updated_at' => '2018-12-27 13:28:58',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 15,
                'possui_doenca' => 2,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 1,
                'peso' => 76.12,
                'altura' => 1.5899999999999999,
                'fumante' => 1,
                'cirurgia' => 2,
                'dor_muscular' => 2,
                'dor_ossea' => 2,
                'dor_articular' => 1,
                'atestado' => 2,
                'observacao' => NULL,
                'ano' => 2015,
                'pessoas_id' => 15,
                'created_at' => '2018-12-27 13:34:55',
                'updated_at' => '2018-12-27 13:34:55',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 17,
                'possui_doenca' => 1,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 2,
                'peso' => 86.0,
                'altura' => 1.62,
                'fumante' => 1,
                'cirurgia' => 1,
                'dor_muscular' => 2,
                'dor_ossea' => 2,
                'dor_articular' => 1,
                'atestado' => 2,
                'observacao' => NULL,
                'ano' => 2015,
                'pessoas_id' => 17,
                'created_at' => '2018-12-27 14:42:15',
                'updated_at' => '2018-12-27 14:42:15',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 18,
                'possui_doenca' => 2,
                'toma_medicacao' => 2,
                'alergia_medicacao' => 2,
                'peso' => 51.05,
                'altura' => 1.58,
                'fumante' => 2,
                'cirurgia' => 2,
                'dor_muscular' => 2,
                'dor_ossea' => 2,
                'dor_articular' => 2,
                'atestado' => NULL,
                'observacao' => NULL,
                'ano' => 2016,
                'pessoas_id' => 12,
                'created_at' => '2018-12-27 15:29:07',
                'updated_at' => '2018-12-27 15:29:07',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 19,
                'possui_doenca' => 2,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 2,
                'peso' => 50.89,
                'altura' => 1.58,
                'fumante' => 2,
                'cirurgia' => 2,
                'dor_muscular' => 2,
                'dor_ossea' => 1,
                'dor_articular' => 2,
                'atestado' => NULL,
                'observacao' => NULL,
                'ano' => 2017,
                'pessoas_id' => 12,
                'created_at' => '2018-12-27 15:29:57',
                'updated_at' => '2018-12-27 15:29:57',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 21,
                'possui_doenca' => 1,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 2,
                'peso' => 50.5,
                'altura' => 1.5899999999999999,
                'fumante' => 2,
                'cirurgia' => 2,
                'dor_muscular' => 2,
                'dor_ossea' => 2,
                'dor_articular' => 2,
                'atestado' => NULL,
                'observacao' => NULL,
                'ano' => 2018,
                'pessoas_id' => 12,
                'created_at' => '2018-12-27 15:36:06',
                'updated_at' => '2018-12-27 15:36:06',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 22,
                'possui_doenca' => 2,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 1,
                'peso' => 83.12,
                'altura' => 1.5699999999999998,
                'fumante' => 2,
                'cirurgia' => 1,
                'dor_muscular' => 1,
                'dor_ossea' => 2,
                'dor_articular' => 2,
                'atestado' => NULL,
                'observacao' => 'Acima do peso',
                'ano' => 2016,
                'pessoas_id' => 11,
                'created_at' => '2018-12-27 15:39:22',
                'updated_at' => '2018-12-27 15:39:22',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 23,
                'possui_doenca' => 1,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 2,
                'peso' => 80.0,
                'altura' => 1.5699999999999998,
                'fumante' => 2,
                'cirurgia' => 1,
                'dor_muscular' => 2,
                'dor_ossea' => 1,
                'dor_articular' => 2,
                'atestado' => NULL,
                'observacao' => 'Acima do peso',
                'ano' => 2017,
                'pessoas_id' => 11,
                'created_at' => '2018-12-27 15:40:54',
                'updated_at' => '2018-12-27 15:40:54',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 24,
                'possui_doenca' => 2,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 2,
                'peso' => 80.12,
                'altura' => 1.5699999999999998,
                'fumante' => 2,
                'cirurgia' => 1,
                'dor_muscular' => 1,
                'dor_ossea' => 2,
                'dor_articular' => 2,
                'atestado' => NULL,
                'observacao' => 'Acima do peso',
                'ano' => 2018,
                'pessoas_id' => 11,
                'created_at' => '2018-12-27 15:42:18',
                'updated_at' => '2018-12-27 15:42:25',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 25,
                'possui_doenca' => 1,
                'toma_medicacao' => 2,
                'alergia_medicacao' => 2,
                'peso' => 84.12,
                'altura' => 1.69,
                'fumante' => 2,
                'cirurgia' => 1,
                'dor_muscular' => 2,
                'dor_ossea' => 2,
                'dor_articular' => 2,
                'atestado' => NULL,
                'observacao' => 'Obeso',
                'ano' => 2016,
                'pessoas_id' => 8,
                'created_at' => '2018-12-27 15:50:21',
                'updated_at' => '2018-12-27 15:51:48',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 26,
                'possui_doenca' => 1,
                'toma_medicacao' => 2,
                'alergia_medicacao' => 2,
                'peso' => 70.5,
                'altura' => 1.69,
                'fumante' => 2,
                'cirurgia' => 1,
                'dor_muscular' => 2,
                'dor_ossea' => 2,
                'dor_articular' => 2,
                'atestado' => NULL,
                'observacao' => NULL,
                'ano' => 2017,
                'pessoas_id' => 8,
                'created_at' => '2018-12-27 15:53:09',
                'updated_at' => '2018-12-27 15:53:09',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 27,
                'possui_doenca' => 2,
                'toma_medicacao' => 2,
                'alergia_medicacao' => 2,
                'peso' => 65.78,
                'altura' => 1.69,
                'fumante' => 2,
                'cirurgia' => 1,
                'dor_muscular' => 2,
                'dor_ossea' => 2,
                'dor_articular' => 2,
                'atestado' => NULL,
                'observacao' => 'Sentindo-se bem',
                'ano' => 2018,
                'pessoas_id' => 8,
                'created_at' => '2018-12-27 15:53:57',
                'updated_at' => '2018-12-27 15:53:57',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 28,
                'possui_doenca' => 1,
                'toma_medicacao' => 2,
                'alergia_medicacao' => 2,
                'peso' => 58.0,
                'altura' => 1.6,
                'fumante' => 2,
                'cirurgia' => 2,
                'dor_muscular' => 1,
                'dor_ossea' => 2,
                'dor_articular' => 2,
                'atestado' => NULL,
                'observacao' => 'Sente-se mal ultimamente',
                'ano' => 2016,
                'pessoas_id' => 7,
                'created_at' => '2018-12-27 15:58:08',
                'updated_at' => '2018-12-27 15:58:15',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}