<?php

use Illuminate\Database\Seeder;

class AnamnesesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('anamneses')->delete();
        
        \DB::table('anamneses')->insert(array (
            0 => 
            array (
                'id' => 1,
                'possui_doenca' => 0,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 0,
                'peso' => 1.8,
                'altura' => 88.0,
                'fumante' => 0,
                'cirurgia' => 0,
                'dor_muscular' => 0,
                'dor_ossea' => 0,
                'dor_articular' => 0,
                'atestado' => 1,
                'observacao' => NULL,
                'ano' => 2014,
                'pessoas_id' => 1,
                'created_at' => '2018-11-21 11:01:19',
                'updated_at' => '2018-11-21 11:01:19',
            ),
            1 => 
            array (
                'id' => 2,
                'possui_doenca' => 1,
                'toma_medicacao' => 0,
                'alergia_medicacao' => 1,
                'peso' => 1.75,
                'altura' => 75.0,
                'fumante' => 0,
                'cirurgia' => 0,
                'dor_muscular' => 0,
                'dor_ossea' => 0,
                'dor_articular' => 0,
                'atestado' => 0,
                'observacao' => 'Cansaço nas pernas muito rapido',
                'ano' => 2014,
                'pessoas_id' => 2,
                'created_at' => '2018-11-21 11:10:34',
                'updated_at' => '2018-11-21 11:10:34',
            ),
            2 => 
            array (
                'id' => 3,
                'possui_doenca' => 0,
                'toma_medicacao' => 0,
                'alergia_medicacao' => 0,
                'peso' => 1.55,
                'altura' => 60.0,
                'fumante' => 0,
                'cirurgia' => 1,
                'dor_muscular' => 0,
                'dor_ossea' => 1,
                'dor_articular' => 0,
                'atestado' => 1,
                'observacao' => 'Possui óculos de grau elevado',
                'ano' => 2014,
                'pessoas_id' => 3,
                'created_at' => '2018-11-21 11:15:44',
                'updated_at' => '2018-11-21 11:15:44',
            ),
            3 => 
            array (
                'id' => 4,
                'possui_doenca' => 1,
                'toma_medicacao' => 0,
                'alergia_medicacao' => 0,
                'peso' => 1.6800000000000002,
                'altura' => 100.0,
                'fumante' => 0,
                'cirurgia' => 0,
                'dor_muscular' => 0,
                'dor_ossea' => 0,
                'dor_articular' => 1,
                'atestado' => 1,
                'observacao' => 'Possui peso elevado',
                'ano' => 2014,
                'pessoas_id' => 4,
                'created_at' => '2018-11-21 11:20:21',
                'updated_at' => '2018-11-21 11:20:21',
            ),
            4 => 
            array (
                'id' => 5,
                'possui_doenca' => 1,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 1,
                'peso' => 1.55,
                'altura' => 80.0,
                'fumante' => 0,
                'cirurgia' => 1,
                'dor_muscular' => 1,
                'dor_ossea' => 0,
                'dor_articular' => 0,
                'atestado' => 1,
                'observacao' => 'Não tem muita energia',
                'ano' => 2014,
                'pessoas_id' => 7,
                'created_at' => '2018-11-21 11:33:38',
                'updated_at' => '2018-11-21 11:33:38',
            ),
            5 => 
            array (
                'id' => 6,
                'possui_doenca' => 1,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 0,
                'peso' => 1.75,
                'altura' => 89.0,
                'fumante' => 0,
                'cirurgia' => 1,
                'dor_muscular' => 1,
                'dor_ossea' => 0,
                'dor_articular' => 0,
                'atestado' => 0,
                'observacao' => 'Idoso',
                'ano' => 2014,
                'pessoas_id' => 9,
                'created_at' => '2018-11-21 11:38:16',
                'updated_at' => '2018-11-21 11:38:16',
            ),
            6 => 
            array (
                'id' => 7,
                'possui_doenca' => 1,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 1,
                'peso' => 1.6,
                'altura' => 65.0,
                'fumante' => 1,
                'cirurgia' => 1,
                'dor_muscular' => 1,
                'dor_ossea' => 1,
                'dor_articular' => 1,
                'atestado' => 0,
                'observacao' => 'Sente-se mal quando se fica cansada',
                'ano' => 2014,
                'pessoas_id' => 10,
                'created_at' => '2018-11-21 11:42:21',
                'updated_at' => '2018-11-21 11:42:21',
            ),
            7 => 
            array (
                'id' => 8,
                'possui_doenca' => 1,
                'toma_medicacao' => 0,
                'alergia_medicacao' => 0,
                'peso' => 1.8,
                'altura' => 88.0,
                'fumante' => 0,
                'cirurgia' => 0,
                'dor_muscular' => 0,
                'dor_ossea' => 1,
                'dor_articular' => 0,
                'atestado' => 1,
                'observacao' => 'Dores no corpo',
                'ano' => 2015,
                'pessoas_id' => 1,
                'created_at' => '2018-11-21 11:47:15',
                'updated_at' => '2018-11-21 11:47:15',
            ),
            8 => 
            array (
                'id' => 9,
                'possui_doenca' => 1,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 0,
                'peso' => 1.75,
                'altura' => 75.0,
                'fumante' => 0,
                'cirurgia' => 0,
                'dor_muscular' => 0,
                'dor_ossea' => 0,
                'dor_articular' => 0,
                'atestado' => 1,
                'observacao' => NULL,
                'ano' => 2015,
                'pessoas_id' => 2,
                'created_at' => '2018-11-21 11:48:19',
                'updated_at' => '2018-11-21 11:48:19',
            ),
            9 => 
            array (
                'id' => 10,
                'possui_doenca' => 0,
                'toma_medicacao' => 0,
                'alergia_medicacao' => 0,
                'peso' => 1.6800000000000002,
                'altura' => 100.0,
                'fumante' => 0,
                'cirurgia' => 1,
                'dor_muscular' => 0,
                'dor_ossea' => 0,
                'dor_articular' => 0,
                'atestado' => 1,
                'observacao' => 'Possui peso elevado',
                'ano' => 2015,
                'pessoas_id' => 4,
                'created_at' => '2018-11-21 11:50:31',
                'updated_at' => '2018-11-21 11:50:57',
            ),
            10 => 
            array (
                'id' => 11,
                'possui_doenca' => 0,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 1,
                'peso' => 1.56,
                'altura' => 75.0,
                'fumante' => 0,
                'cirurgia' => 1,
                'dor_muscular' => 0,
                'dor_ossea' => 1,
                'dor_articular' => 0,
                'atestado' => 1,
                'observacao' => NULL,
                'ano' => 2015,
                'pessoas_id' => 7,
                'created_at' => '2018-11-21 11:54:23',
                'updated_at' => '2018-11-21 11:54:23',
            ),
            11 => 
            array (
                'id' => 12,
                'possui_doenca' => 1,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 0,
                'peso' => 1.75,
                'altura' => 89.0,
                'fumante' => 0,
                'cirurgia' => 1,
                'dor_muscular' => 0,
                'dor_ossea' => 0,
                'dor_articular' => 1,
                'atestado' => 1,
                'observacao' => 'Idoso',
                'ano' => 2015,
                'pessoas_id' => 9,
                'created_at' => '2018-11-21 11:55:29',
                'updated_at' => '2018-11-21 11:55:29',
            ),
            12 => 
            array (
                'id' => 13,
                'possui_doenca' => 1,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 1,
                'peso' => 1.6,
                'altura' => 65.0,
                'fumante' => 0,
                'cirurgia' => 1,
                'dor_muscular' => 1,
                'dor_ossea' => 0,
                'dor_articular' => 0,
                'atestado' => 1,
                'observacao' => 'Sente-se mal quando se fica cansada',
                'ano' => 2015,
                'pessoas_id' => 10,
                'created_at' => '2018-11-21 11:56:12',
                'updated_at' => '2018-11-21 11:56:12',
            ),
            13 => 
            array (
                'id' => 14,
                'possui_doenca' => 0,
                'toma_medicacao' => 0,
                'alergia_medicacao' => 0,
                'peso' => 1.8,
                'altura' => 70.0,
                'fumante' => 0,
                'cirurgia' => 0,
                'dor_muscular' => 0,
                'dor_ossea' => 0,
                'dor_articular' => 1,
                'atestado' => 1,
                'observacao' => NULL,
                'ano' => 2016,
                'pessoas_id' => 1,
                'created_at' => '2018-11-21 11:58:16',
                'updated_at' => '2018-11-21 11:58:16',
            ),
            14 => 
            array (
                'id' => 15,
                'possui_doenca' => 0,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 0,
                'peso' => 1.75,
                'altura' => 75.0,
                'fumante' => 0,
                'cirurgia' => 0,
                'dor_muscular' => 0,
                'dor_ossea' => 0,
                'dor_articular' => 0,
                'atestado' => 1,
                'observacao' => NULL,
                'ano' => 2016,
                'pessoas_id' => 2,
                'created_at' => '2018-11-21 11:59:24',
                'updated_at' => '2018-11-21 11:59:24',
            ),
            15 => 
            array (
                'id' => 16,
                'possui_doenca' => 0,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 0,
                'peso' => 1.6800000000000002,
                'altura' => 93.0,
                'fumante' => 0,
                'cirurgia' => 1,
                'dor_muscular' => 0,
                'dor_ossea' => 0,
                'dor_articular' => 0,
                'atestado' => 1,
                'observacao' => NULL,
                'ano' => 2016,
                'pessoas_id' => 4,
                'created_at' => '2018-11-21 12:00:47',
                'updated_at' => '2018-11-21 12:00:47',
            ),
            16 => 
            array (
                'id' => 17,
                'possui_doenca' => 0,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 1,
                'peso' => 1.56,
                'altura' => 75.0,
                'fumante' => 0,
                'cirurgia' => 1,
                'dor_muscular' => 0,
                'dor_ossea' => 0,
                'dor_articular' => 0,
                'atestado' => 1,
                'observacao' => 'Não tem se sentido bem ultimamente',
                'ano' => 2016,
                'pessoas_id' => 7,
                'created_at' => '2018-11-21 12:01:41',
                'updated_at' => '2018-11-21 12:01:41',
            ),
            17 => 
            array (
                'id' => 18,
                'possui_doenca' => 0,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 0,
                'peso' => 1.75,
                'altura' => 85.0,
                'fumante' => 0,
                'cirurgia' => 1,
                'dor_muscular' => 1,
                'dor_ossea' => 0,
                'dor_articular' => 0,
                'atestado' => 1,
                'observacao' => 'Idoso, sente-se bem',
                'ano' => 2016,
                'pessoas_id' => 9,
                'created_at' => '2018-11-21 12:02:48',
                'updated_at' => '2018-11-21 12:02:48',
            ),
            18 => 
            array (
                'id' => 19,
                'possui_doenca' => 1,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 1,
                'peso' => 1.6,
                'altura' => 68.0,
                'fumante' => 1,
                'cirurgia' => 1,
                'dor_muscular' => 0,
                'dor_ossea' => 0,
                'dor_articular' => 0,
                'atestado' => 1,
                'observacao' => 'Sente-se mal quando se fica cansada',
                'ano' => 2016,
                'pessoas_id' => 10,
                'created_at' => '2018-11-21 12:04:24',
                'updated_at' => '2018-11-21 12:04:24',
            ),
            19 => 
            array (
                'id' => 20,
                'possui_doenca' => 0,
                'toma_medicacao' => 0,
                'alergia_medicacao' => 0,
                'peso' => 1.5,
                'altura' => 56.0,
                'fumante' => 0,
                'cirurgia' => 0,
                'dor_muscular' => 0,
                'dor_ossea' => 0,
                'dor_articular' => 0,
                'atestado' => 1,
                'observacao' => 'Criança',
                'ano' => 2016,
                'pessoas_id' => 11,
                'created_at' => '2018-11-21 12:07:52',
                'updated_at' => '2018-11-21 12:07:52',
            ),
            20 => 
            array (
                'id' => 21,
                'possui_doenca' => 0,
                'toma_medicacao' => 0,
                'alergia_medicacao' => 0,
                'peso' => 1.81,
                'altura' => 83.0,
                'fumante' => 0,
                'cirurgia' => 0,
                'dor_muscular' => 0,
                'dor_ossea' => 1,
                'dor_articular' => 0,
                'atestado' => 1,
                'observacao' => NULL,
                'ano' => 2017,
                'pessoas_id' => 1,
                'created_at' => '2018-11-21 12:10:45',
                'updated_at' => '2018-11-21 12:10:45',
            ),
            21 => 
            array (
                'id' => 22,
                'possui_doenca' => 0,
                'toma_medicacao' => 0,
                'alergia_medicacao' => 0,
                'peso' => 1.75,
                'altura' => 75.0,
                'fumante' => 0,
                'cirurgia' => 1,
                'dor_muscular' => 1,
                'dor_ossea' => 0,
                'dor_articular' => 0,
                'atestado' => 1,
                'observacao' => 'Foi submetido a cirurgia ultimamente',
                'ano' => 2017,
                'pessoas_id' => 2,
                'created_at' => '2018-11-21 12:12:30',
                'updated_at' => '2018-11-21 12:12:30',
            ),
            22 => 
            array (
                'id' => 23,
                'possui_doenca' => 0,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 0,
                'peso' => 1.6800000000000002,
                'altura' => 85.0,
                'fumante' => 0,
                'cirurgia' => 1,
                'dor_muscular' => 1,
                'dor_ossea' => 1,
                'dor_articular' => 0,
                'atestado' => 1,
                'observacao' => NULL,
                'ano' => 2017,
                'pessoas_id' => 4,
                'created_at' => '2018-11-21 12:13:43',
                'updated_at' => '2018-11-21 12:13:43',
            ),
            23 => 
            array (
                'id' => 24,
                'possui_doenca' => 0,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 1,
                'peso' => 1.56,
                'altura' => 75.0,
                'fumante' => 0,
                'cirurgia' => 1,
                'dor_muscular' => 0,
                'dor_ossea' => 0,
                'dor_articular' => 0,
                'atestado' => 1,
                'observacao' => NULL,
                'ano' => 2017,
                'pessoas_id' => 7,
                'created_at' => '2018-11-21 12:15:11',
                'updated_at' => '2018-11-21 12:15:11',
            ),
            24 => 
            array (
                'id' => 25,
                'possui_doenca' => 0,
                'toma_medicacao' => 0,
                'alergia_medicacao' => 1,
                'peso' => 1.6,
                'altura' => 65.0,
                'fumante' => 0,
                'cirurgia' => 1,
                'dor_muscular' => 1,
                'dor_ossea' => 0,
                'dor_articular' => 1,
                'atestado' => 1,
                'observacao' => 'Sente-se mal quando se fica cansada',
                'ano' => 2017,
                'pessoas_id' => 10,
                'created_at' => '2018-11-21 12:16:07',
                'updated_at' => '2018-11-21 12:16:07',
            ),
            25 => 
            array (
                'id' => 26,
                'possui_doenca' => 1,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 0,
                'peso' => 1.55,
                'altura' => 60.0,
                'fumante' => 0,
                'cirurgia' => 0,
                'dor_muscular' => 0,
                'dor_ossea' => 0,
                'dor_articular' => 0,
                'atestado' => 1,
                'observacao' => 'Criança',
                'ano' => 2017,
                'pessoas_id' => 11,
                'created_at' => '2018-11-21 12:16:57',
                'updated_at' => '2018-11-21 12:16:57',
            ),
            26 => 
            array (
                'id' => 27,
                'possui_doenca' => 0,
                'toma_medicacao' => 0,
                'alergia_medicacao' => 0,
                'peso' => 1.81,
                'altura' => 78.0,
                'fumante' => 0,
                'cirurgia' => 0,
                'dor_muscular' => 0,
                'dor_ossea' => 0,
                'dor_articular' => 0,
                'atestado' => 1,
                'observacao' => NULL,
                'ano' => 2018,
                'pessoas_id' => 1,
                'created_at' => '2018-11-21 12:18:45',
                'updated_at' => '2018-11-21 12:18:45',
            ),
            27 => 
            array (
                'id' => 28,
                'possui_doenca' => 1,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 0,
                'peso' => 1.75,
                'altura' => 80.0,
                'fumante' => 0,
                'cirurgia' => 0,
                'dor_muscular' => 0,
                'dor_ossea' => 0,
                'dor_articular' => 1,
                'atestado' => 1,
                'observacao' => 'Sente-se bem ultimamente',
                'ano' => 2018,
                'pessoas_id' => 2,
                'created_at' => '2018-11-21 12:20:01',
                'updated_at' => '2018-11-21 12:20:01',
            ),
            28 => 
            array (
                'id' => 29,
                'possui_doenca' => 0,
                'toma_medicacao' => 0,
                'alergia_medicacao' => 0,
                'peso' => 1.6800000000000002,
                'altura' => 85.0,
                'fumante' => 0,
                'cirurgia' => 1,
                'dor_muscular' => 0,
                'dor_ossea' => 0,
                'dor_articular' => 0,
                'atestado' => 1,
                'observacao' => NULL,
                'ano' => 2018,
                'pessoas_id' => 4,
                'created_at' => '2018-11-21 12:20:52',
                'updated_at' => '2018-11-21 12:20:52',
            ),
            29 => 
            array (
                'id' => 30,
                'possui_doenca' => 0,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 1,
                'peso' => 1.56,
                'altura' => 76.0,
                'fumante' => 0,
                'cirurgia' => 1,
                'dor_muscular' => 1,
                'dor_ossea' => 0,
                'dor_articular' => 0,
                'atestado' => 1,
                'observacao' => NULL,
                'ano' => 2018,
                'pessoas_id' => 7,
                'created_at' => '2018-11-21 12:22:27',
                'updated_at' => '2018-11-21 12:22:27',
            ),
            30 => 
            array (
                'id' => 31,
                'possui_doenca' => 0,
                'toma_medicacao' => 0,
                'alergia_medicacao' => 1,
                'peso' => 1.6,
                'altura' => 65.0,
                'fumante' => 0,
                'cirurgia' => 1,
                'dor_muscular' => 0,
                'dor_ossea' => 0,
                'dor_articular' => 0,
                'atestado' => 1,
                'observacao' => 'Sente-se mal quando se fica cansada',
                'ano' => 2018,
                'pessoas_id' => 10,
                'created_at' => '2018-11-21 12:23:29',
                'updated_at' => '2018-11-21 12:23:29',
            ),
            31 => 
            array (
                'id' => 32,
                'possui_doenca' => 0,
                'toma_medicacao' => 0,
                'alergia_medicacao' => 0,
                'peso' => 1.6,
                'altura' => 63.0,
                'fumante' => 0,
                'cirurgia' => 1,
                'dor_muscular' => 0,
                'dor_ossea' => 1,
                'dor_articular' => 0,
                'atestado' => 1,
                'observacao' => 'Criança',
                'ano' => 2018,
                'pessoas_id' => 11,
                'created_at' => '2018-11-21 12:24:29',
                'updated_at' => '2018-11-21 12:24:29',
            ),
            32 => 
            array (
                'id' => 33,
                'possui_doenca' => 0,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 1,
                'peso' => 1.65,
                'altura' => 63.0,
                'fumante' => 0,
                'cirurgia' => 0,
                'dor_muscular' => 0,
                'dor_ossea' => 0,
                'dor_articular' => 0,
                'atestado' => 1,
                'observacao' => 'Criança',
                'ano' => 2018,
                'pessoas_id' => 12,
                'created_at' => '2018-11-21 12:27:10',
                'updated_at' => '2018-11-21 12:27:10',
            ),
        ));
        
        
    }
}