<?php

use Illuminate\Database\Seeder;

class AnamnesesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('Anamneses')->delete();
        
        \DB::table('Anamneses')->insert(array (
            0 => 
            array (
                'id' => 1,
                'possui_doenca' => 2,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 2,
                'peso' => 83.0,
                'altura' => 1.73,
                'fumante' => 2,
                'cirurgia' => 1,
                'dor_muscular' => 2,
                'dor_ossea' => 2,
                'dor_articular' => 2,
                'atestado' => 2,
                'observacao' => NULL,
                'ano' => 2015,
                'pessoas_id' => 1,
                'created_at' => '2018-12-26 15:25:07',
                'updated_at' => '2018-12-26 15:25:07',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 3,
                'possui_doenca' => 1,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 1,
                'peso' => 60.0,
                'altura' => 1.5,
                'fumante' => 2,
                'cirurgia' => 1,
                'dor_muscular' => 2,
                'dor_ossea' => 2,
                'dor_articular' => 2,
                'atestado' => 2,
                'observacao' => 'Possui óculos',
                'ano' => 2015,
                'pessoas_id' => 3,
                'created_at' => '2018-12-27 12:16:50',
                'updated_at' => '2018-12-27 12:16:50',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 4,
                'possui_doenca' => 1,
                'toma_medicacao' => 2,
                'alergia_medicacao' => 2,
                'peso' => 71.0,
                'altura' => 1.69,
                'fumante' => 1,
                'cirurgia' => 1,
                'dor_muscular' => 1,
                'dor_ossea' => 2,
                'dor_articular' => 2,
                'atestado' => 2,
                'observacao' => NULL,
                'ano' => 2015,
                'pessoas_id' => 4,
                'created_at' => '2018-12-27 12:24:05',
                'updated_at' => '2018-12-27 12:24:05',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 7,
                'possui_doenca' => 2,
                'toma_medicacao' => 2,
                'alergia_medicacao' => 2,
                'peso' => 58.1,
                'altura' => 1.7,
                'fumante' => 1,
                'cirurgia' => 2,
                'dor_muscular' => 2,
                'dor_ossea' => 2,
                'dor_articular' => 2,
                'atestado' => 2,
                'observacao' => NULL,
                'ano' => 2015,
                'pessoas_id' => 7,
                'created_at' => '2018-12-27 12:37:49',
                'updated_at' => '2018-12-27 12:37:49',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 8,
                'possui_doenca' => 1,
                'toma_medicacao' => 2,
                'alergia_medicacao' => 2,
                'peso' => 90.0,
                'altura' => 1.6800000000000002,
                'fumante' => 2,
                'cirurgia' => 1,
                'dor_muscular' => 2,
                'dor_ossea' => 1,
                'dor_articular' => 1,
                'atestado' => 2,
                'observacao' => 'Cansaço físico depois de meia hora',
                'ano' => 2015,
                'pessoas_id' => 8,
                'created_at' => '2018-12-27 12:55:48',
                'updated_at' => '2018-12-27 12:55:48',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 9,
                'possui_doenca' => 1,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 2,
                'peso' => 76.82,
                'altura' => 1.65,
                'fumante' => 2,
                'cirurgia' => 2,
                'dor_muscular' => 2,
                'dor_ossea' => 2,
                'dor_articular' => 1,
                'atestado' => 2,
                'observacao' => 'Problemas na Perna',
                'ano' => 2015,
                'pessoas_id' => 9,
                'created_at' => '2018-12-27 13:00:18',
                'updated_at' => '2018-12-27 13:00:18',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 11,
                'possui_doenca' => 2,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 1,
                'peso' => 86.0,
                'altura' => 1.5699999999999998,
                'fumante' => 2,
                'cirurgia' => 1,
                'dor_muscular' => 2,
                'dor_ossea' => 2,
                'dor_articular' => 2,
                'atestado' => 2,
                'observacao' => 'Acima do peso',
                'ano' => 2015,
                'pessoas_id' => 11,
                'created_at' => '2018-12-27 13:11:58',
                'updated_at' => '2018-12-27 13:11:58',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 12,
                'possui_doenca' => 1,
                'toma_medicacao' => 2,
                'alergia_medicacao' => 2,
                'peso' => 50.9,
                'altura' => 1.58,
                'fumante' => 2,
                'cirurgia' => 2,
                'dor_muscular' => 2,
                'dor_ossea' => 2,
                'dor_articular' => 2,
                'atestado' => 2,
                'observacao' => 'Não pode ficar exposta ao sol',
                'ano' => 2015,
                'pessoas_id' => 12,
                'created_at' => '2018-12-27 13:18:02',
                'updated_at' => '2018-12-27 13:18:02',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 13,
                'possui_doenca' => 2,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 2,
                'peso' => 79.56,
                'altura' => 1.56,
                'fumante' => 2,
                'cirurgia' => 1,
                'dor_muscular' => 2,
                'dor_ossea' => 1,
                'dor_articular' => 1,
                'atestado' => 2,
                'observacao' => 'Físico Deteriorado, físico deteriorado',
                'ano' => 2015,
                'pessoas_id' => 13,
                'created_at' => '2018-12-27 13:22:43',
                'updated_at' => '2018-12-27 13:22:43',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 14,
                'possui_doenca' => 1,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 2,
                'peso' => 95.0,
                'altura' => 1.72,
                'fumante' => 2,
                'cirurgia' => 2,
                'dor_muscular' => 2,
                'dor_ossea' => 2,
                'dor_articular' => 2,
                'atestado' => 2,
                'observacao' => 'Idade avançada',
                'ano' => 2015,
                'pessoas_id' => 14,
                'created_at' => '2018-12-27 13:28:58',
                'updated_at' => '2018-12-27 13:28:58',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 15,
                'possui_doenca' => 2,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 1,
                'peso' => 76.12,
                'altura' => 1.5899999999999999,
                'fumante' => 1,
                'cirurgia' => 2,
                'dor_muscular' => 2,
                'dor_ossea' => 2,
                'dor_articular' => 1,
                'atestado' => 2,
                'observacao' => NULL,
                'ano' => 2015,
                'pessoas_id' => 15,
                'created_at' => '2018-12-27 13:34:55',
                'updated_at' => '2018-12-27 13:34:55',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 17,
                'possui_doenca' => 1,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 2,
                'peso' => 86.0,
                'altura' => 1.62,
                'fumante' => 1,
                'cirurgia' => 1,
                'dor_muscular' => 2,
                'dor_ossea' => 2,
                'dor_articular' => 1,
                'atestado' => 2,
                'observacao' => NULL,
                'ano' => 2015,
                'pessoas_id' => 17,
                'created_at' => '2018-12-27 14:42:15',
                'updated_at' => '2018-12-27 14:42:15',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 18,
                'possui_doenca' => 2,
                'toma_medicacao' => 2,
                'alergia_medicacao' => 2,
                'peso' => 51.05,
                'altura' => 1.58,
                'fumante' => 2,
                'cirurgia' => 2,
                'dor_muscular' => 2,
                'dor_ossea' => 2,
                'dor_articular' => 2,
                'atestado' => NULL,
                'observacao' => NULL,
                'ano' => 2016,
                'pessoas_id' => 12,
                'created_at' => '2018-12-27 15:29:07',
                'updated_at' => '2018-12-27 15:29:07',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 19,
                'possui_doenca' => 2,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 2,
                'peso' => 50.89,
                'altura' => 1.58,
                'fumante' => 2,
                'cirurgia' => 2,
                'dor_muscular' => 2,
                'dor_ossea' => 1,
                'dor_articular' => 2,
                'atestado' => NULL,
                'observacao' => NULL,
                'ano' => 2017,
                'pessoas_id' => 12,
                'created_at' => '2018-12-27 15:29:57',
                'updated_at' => '2018-12-27 15:29:57',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 21,
                'possui_doenca' => 1,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 2,
                'peso' => 50.5,
                'altura' => 1.5899999999999999,
                'fumante' => 2,
                'cirurgia' => 2,
                'dor_muscular' => 2,
                'dor_ossea' => 2,
                'dor_articular' => 2,
                'atestado' => NULL,
                'observacao' => NULL,
                'ano' => 2018,
                'pessoas_id' => 12,
                'created_at' => '2018-12-27 15:36:06',
                'updated_at' => '2018-12-27 15:36:06',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 22,
                'possui_doenca' => 2,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 1,
                'peso' => 83.12,
                'altura' => 1.5699999999999998,
                'fumante' => 2,
                'cirurgia' => 1,
                'dor_muscular' => 1,
                'dor_ossea' => 2,
                'dor_articular' => 2,
                'atestado' => NULL,
                'observacao' => 'Acima do peso',
                'ano' => 2016,
                'pessoas_id' => 11,
                'created_at' => '2018-12-27 15:39:22',
                'updated_at' => '2018-12-27 15:39:22',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 23,
                'possui_doenca' => 1,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 2,
                'peso' => 80.0,
                'altura' => 1.5699999999999998,
                'fumante' => 2,
                'cirurgia' => 1,
                'dor_muscular' => 2,
                'dor_ossea' => 1,
                'dor_articular' => 2,
                'atestado' => NULL,
                'observacao' => 'Acima do peso',
                'ano' => 2017,
                'pessoas_id' => 11,
                'created_at' => '2018-12-27 15:40:54',
                'updated_at' => '2018-12-27 15:40:54',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 24,
                'possui_doenca' => 2,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 2,
                'peso' => 80.12,
                'altura' => 1.5699999999999998,
                'fumante' => 2,
                'cirurgia' => 1,
                'dor_muscular' => 1,
                'dor_ossea' => 2,
                'dor_articular' => 2,
                'atestado' => NULL,
                'observacao' => 'Acima do peso',
                'ano' => 2018,
                'pessoas_id' => 11,
                'created_at' => '2018-12-27 15:42:18',
                'updated_at' => '2018-12-27 15:42:25',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 25,
                'possui_doenca' => 1,
                'toma_medicacao' => 2,
                'alergia_medicacao' => 2,
                'peso' => 84.12,
                'altura' => 1.69,
                'fumante' => 2,
                'cirurgia' => 1,
                'dor_muscular' => 2,
                'dor_ossea' => 2,
                'dor_articular' => 2,
                'atestado' => NULL,
                'observacao' => 'Obeso',
                'ano' => 2016,
                'pessoas_id' => 8,
                'created_at' => '2018-12-27 15:50:21',
                'updated_at' => '2018-12-27 15:51:48',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 26,
                'possui_doenca' => 1,
                'toma_medicacao' => 2,
                'alergia_medicacao' => 2,
                'peso' => 70.5,
                'altura' => 1.69,
                'fumante' => 2,
                'cirurgia' => 1,
                'dor_muscular' => 2,
                'dor_ossea' => 2,
                'dor_articular' => 2,
                'atestado' => NULL,
                'observacao' => NULL,
                'ano' => 2017,
                'pessoas_id' => 8,
                'created_at' => '2018-12-27 15:53:09',
                'updated_at' => '2018-12-27 15:53:09',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 27,
                'possui_doenca' => 2,
                'toma_medicacao' => 2,
                'alergia_medicacao' => 2,
                'peso' => 65.78,
                'altura' => 1.69,
                'fumante' => 2,
                'cirurgia' => 1,
                'dor_muscular' => 2,
                'dor_ossea' => 2,
                'dor_articular' => 2,
                'atestado' => NULL,
                'observacao' => 'Sentindo-se bem',
                'ano' => 2018,
                'pessoas_id' => 8,
                'created_at' => '2018-12-27 15:53:57',
                'updated_at' => '2018-12-27 15:53:57',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 28,
                'possui_doenca' => 1,
                'toma_medicacao' => 2,
                'alergia_medicacao' => 2,
                'peso' => 58.0,
                'altura' => 1.6,
                'fumante' => 2,
                'cirurgia' => 2,
                'dor_muscular' => 1,
                'dor_ossea' => 2,
                'dor_articular' => 2,
                'atestado' => NULL,
                'observacao' => 'Sente-se mal ultimamente',
                'ano' => 2016,
                'pessoas_id' => 7,
                'created_at' => '2018-12-27 15:58:08',
                'updated_at' => '2018-12-27 15:58:15',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 29,
                'possui_doenca' => 1,
                'toma_medicacao' => 2,
                'alergia_medicacao' => 2,
                'peso' => 68.23,
                'altura' => 1.7,
                'fumante' => 2,
                'cirurgia' => 1,
                'dor_muscular' => 2,
                'dor_ossea' => 2,
                'dor_articular' => 2,
                'atestado' => NULL,
                'observacao' => NULL,
                'ano' => 2016,
                'pessoas_id' => 4,
                'created_at' => '2018-12-28 10:05:10',
                'updated_at' => '2018-12-28 10:05:10',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 30,
                'possui_doenca' => 2,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 2,
                'peso' => 69.11,
                'altura' => 1.7,
                'fumante' => 2,
                'cirurgia' => 1,
                'dor_muscular' => 2,
                'dor_ossea' => 2,
                'dor_articular' => 2,
                'atestado' => NULL,
                'observacao' => NULL,
                'ano' => 2017,
                'pessoas_id' => 4,
                'created_at' => '2018-12-28 10:06:16',
                'updated_at' => '2018-12-28 10:06:16',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 31,
                'possui_doenca' => 2,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 2,
                'peso' => 70.1,
                'altura' => 1.7,
                'fumante' => 2,
                'cirurgia' => 1,
                'dor_muscular' => 2,
                'dor_ossea' => 1,
                'dor_articular' => 2,
                'atestado' => NULL,
                'observacao' => NULL,
                'ano' => 2018,
                'pessoas_id' => 4,
                'created_at' => '2018-12-28 10:07:19',
                'updated_at' => '2018-12-28 10:07:19',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 32,
                'possui_doenca' => 2,
                'toma_medicacao' => 2,
                'alergia_medicacao' => 2,
                'peso' => 61.0,
                'altura' => 1.53,
                'fumante' => 2,
                'cirurgia' => 2,
                'dor_muscular' => 2,
                'dor_ossea' => 2,
                'dor_articular' => 2,
                'atestado' => NULL,
                'observacao' => 'Possui óculos',
                'ano' => 2016,
                'pessoas_id' => 3,
                'created_at' => '2018-12-28 10:09:42',
                'updated_at' => '2018-12-28 10:09:42',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 33,
                'possui_doenca' => 2,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 2,
                'peso' => 63.11,
                'altura' => 1.56,
                'fumante' => 2,
                'cirurgia' => 2,
                'dor_muscular' => 2,
                'dor_ossea' => 2,
                'dor_articular' => 2,
                'atestado' => NULL,
                'observacao' => 'Possui óculos',
                'ano' => 2017,
                'pessoas_id' => 3,
                'created_at' => '2018-12-28 10:10:56',
                'updated_at' => '2018-12-28 10:10:56',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 34,
                'possui_doenca' => 2,
                'toma_medicacao' => 2,
                'alergia_medicacao' => 2,
                'peso' => 63.12,
                'altura' => 1.58,
                'fumante' => 2,
                'cirurgia' => 1,
                'dor_muscular' => 2,
                'dor_ossea' => 2,
                'dor_articular' => 2,
                'atestado' => NULL,
                'observacao' => NULL,
                'ano' => 2018,
                'pessoas_id' => 3,
                'created_at' => '2018-12-28 10:13:00',
                'updated_at' => '2018-12-28 10:13:00',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 35,
                'possui_doenca' => 1,
                'toma_medicacao' => 2,
                'alergia_medicacao' => 2,
                'peso' => 82.02,
                'altura' => 1.73,
                'fumante' => 2,
                'cirurgia' => 1,
                'dor_muscular' => 1,
                'dor_ossea' => 2,
                'dor_articular' => 2,
                'atestado' => NULL,
                'observacao' => NULL,
                'ano' => 2016,
                'pessoas_id' => 1,
                'created_at' => '2018-12-28 10:14:54',
                'updated_at' => '2018-12-28 10:14:54',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 36,
                'possui_doenca' => 2,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 2,
                'peso' => 80.02,
                'altura' => 1.73,
                'fumante' => 2,
                'cirurgia' => 1,
                'dor_muscular' => 2,
                'dor_ossea' => 1,
                'dor_articular' => 2,
                'atestado' => NULL,
                'observacao' => 'Sente-se cansada ultimamente',
                'ano' => 2017,
                'pessoas_id' => 1,
                'created_at' => '2018-12-28 10:16:19',
                'updated_at' => '2018-12-28 10:16:19',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 37,
                'possui_doenca' => 2,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 2,
                'peso' => 77.52,
                'altura' => 1.73,
                'fumante' => 2,
                'cirurgia' => 1,
                'dor_muscular' => 2,
                'dor_ossea' => 2,
                'dor_articular' => 2,
                'atestado' => NULL,
                'observacao' => NULL,
                'ano' => 2018,
                'pessoas_id' => 1,
                'created_at' => '2018-12-28 10:17:22',
                'updated_at' => '2018-12-28 10:17:22',
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 38,
                'possui_doenca' => 1,
                'toma_medicacao' => 2,
                'alergia_medicacao' => 2,
                'peso' => 87.0,
                'altura' => 1.62,
                'fumante' => 1,
                'cirurgia' => 1,
                'dor_muscular' => 2,
                'dor_ossea' => 2,
                'dor_articular' => 2,
                'atestado' => NULL,
                'observacao' => NULL,
                'ano' => 2016,
                'pessoas_id' => 17,
                'created_at' => '2018-12-28 10:20:41',
                'updated_at' => '2018-12-28 10:20:41',
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 39,
                'possui_doenca' => 1,
                'toma_medicacao' => 2,
                'alergia_medicacao' => 2,
                'peso' => 88.56,
                'altura' => 1.62,
                'fumante' => 1,
                'cirurgia' => 1,
                'dor_muscular' => 1,
                'dor_ossea' => 2,
                'dor_articular' => 2,
                'atestado' => NULL,
                'observacao' => NULL,
                'ano' => 2017,
                'pessoas_id' => 17,
                'created_at' => '2018-12-28 10:21:53',
                'updated_at' => '2018-12-28 10:21:53',
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 40,
                'possui_doenca' => 1,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 2,
                'peso' => 88.2,
                'altura' => 1.62,
                'fumante' => 1,
                'cirurgia' => 1,
                'dor_muscular' => 1,
                'dor_ossea' => 2,
                'dor_articular' => 1,
                'atestado' => NULL,
                'observacao' => NULL,
                'ano' => 2018,
                'pessoas_id' => 17,
                'created_at' => '2018-12-28 10:23:07',
                'updated_at' => '2018-12-28 10:23:07',
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 41,
                'possui_doenca' => 2,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 1,
                'peso' => 76.11,
                'altura' => 1.6,
                'fumante' => 1,
                'cirurgia' => 2,
                'dor_muscular' => 2,
                'dor_ossea' => 2,
                'dor_articular' => 2,
                'atestado' => NULL,
                'observacao' => 'esta com náuseas ultimamente',
                'ano' => 2016,
                'pessoas_id' => 15,
                'created_at' => '2018-12-28 10:26:11',
                'updated_at' => '2018-12-28 10:26:11',
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 42,
                'possui_doenca' => 1,
                'toma_medicacao' => 2,
                'alergia_medicacao' => 2,
                'peso' => 75.0,
                'altura' => 1.6,
                'fumante' => 1,
                'cirurgia' => 2,
                'dor_muscular' => 2,
                'dor_ossea' => 2,
                'dor_articular' => 2,
                'atestado' => NULL,
                'observacao' => NULL,
                'ano' => 2017,
                'pessoas_id' => 15,
                'created_at' => '2018-12-28 10:26:49',
                'updated_at' => '2018-12-28 10:26:49',
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 43,
                'possui_doenca' => 1,
                'toma_medicacao' => 2,
                'alergia_medicacao' => 2,
                'peso' => 76.2,
                'altura' => 1.6,
                'fumante' => 2,
                'cirurgia' => 1,
                'dor_muscular' => 1,
                'dor_ossea' => 2,
                'dor_articular' => 2,
                'atestado' => NULL,
                'observacao' => NULL,
                'ano' => 2018,
                'pessoas_id' => 15,
                'created_at' => '2018-12-28 10:27:27',
                'updated_at' => '2018-12-28 10:27:27',
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 44,
                'possui_doenca' => 2,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 2,
                'peso' => 91.12,
                'altura' => 1.72,
                'fumante' => 2,
                'cirurgia' => 2,
                'dor_muscular' => 2,
                'dor_ossea' => 1,
                'dor_articular' => 2,
                'atestado' => NULL,
                'observacao' => 'Idade avançada',
                'ano' => 2016,
                'pessoas_id' => 14,
                'created_at' => '2018-12-28 10:30:24',
                'updated_at' => '2018-12-28 10:30:24',
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 45,
                'possui_doenca' => 2,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 2,
                'peso' => 90.12,
                'altura' => 1.72,
                'fumante' => 2,
                'cirurgia' => 2,
                'dor_muscular' => 1,
                'dor_ossea' => 2,
                'dor_articular' => 2,
                'atestado' => NULL,
                'observacao' => 'Idade avançada',
                'ano' => 2017,
                'pessoas_id' => 14,
                'created_at' => '2018-12-28 10:32:30',
                'updated_at' => '2018-12-28 10:33:05',
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 46,
                'possui_doenca' => 2,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 2,
                'peso' => 89.12,
                'altura' => 1.72,
                'fumante' => 2,
                'cirurgia' => 2,
                'dor_muscular' => 1,
                'dor_ossea' => 2,
                'dor_articular' => 2,
                'atestado' => NULL,
                'observacao' => 'Idade avançada',
                'ano' => 2018,
                'pessoas_id' => 14,
                'created_at' => '2018-12-28 10:35:09',
                'updated_at' => '2018-12-28 10:35:09',
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 47,
                'possui_doenca' => 1,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 2,
                'peso' => 78.95,
                'altura' => 1.58,
                'fumante' => 2,
                'cirurgia' => 1,
                'dor_muscular' => 2,
                'dor_ossea' => 1,
                'dor_articular' => 2,
                'atestado' => NULL,
                'observacao' => 'Idade avançada, físico deteriorado',
                'ano' => 2016,
                'pessoas_id' => 13,
                'created_at' => '2018-12-28 10:38:12',
                'updated_at' => '2018-12-28 10:38:12',
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'id' => 48,
                'possui_doenca' => 2,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 2,
                'peso' => 78.12,
                'altura' => 1.58,
                'fumante' => 2,
                'cirurgia' => 1,
                'dor_muscular' => 1,
                'dor_ossea' => 1,
                'dor_articular' => 1,
                'atestado' => NULL,
                'observacao' => 'Idade avançada, físico deteriorado',
                'ano' => 2017,
                'pessoas_id' => 13,
                'created_at' => '2018-12-28 10:40:08',
                'updated_at' => '2018-12-28 10:40:08',
                'deleted_at' => NULL,
            ),
            42 => 
            array (
                'id' => 49,
                'possui_doenca' => 1,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 2,
                'peso' => 75.8,
                'altura' => 1.6600000000000001,
                'fumante' => 2,
                'cirurgia' => 2,
                'dor_muscular' => 2,
                'dor_ossea' => 2,
                'dor_articular' => 1,
                'atestado' => NULL,
                'observacao' => NULL,
                'ano' => 2016,
                'pessoas_id' => 9,
                'created_at' => '2018-12-28 11:01:58',
                'updated_at' => '2018-12-28 11:01:58',
                'deleted_at' => NULL,
            ),
            43 => 
            array (
                'id' => 50,
                'possui_doenca' => 1,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 2,
                'peso' => 75.75,
                'altura' => 1.6600000000000001,
                'fumante' => 2,
                'cirurgia' => 2,
                'dor_muscular' => 2,
                'dor_ossea' => 2,
                'dor_articular' => 1,
                'atestado' => NULL,
                'observacao' => NULL,
                'ano' => 2017,
                'pessoas_id' => 9,
                'created_at' => '2018-12-28 11:03:23',
                'updated_at' => '2018-12-28 11:03:23',
                'deleted_at' => NULL,
            ),
            44 => 
            array (
                'id' => 51,
                'possui_doenca' => 2,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 2,
                'peso' => 78.0,
                'altura' => 1.6600000000000001,
                'fumante' => 2,
                'cirurgia' => 2,
                'dor_muscular' => 1,
                'dor_ossea' => 2,
                'dor_articular' => 2,
                'atestado' => NULL,
                'observacao' => NULL,
                'ano' => 2018,
                'pessoas_id' => 9,
                'created_at' => '2018-12-28 11:04:03',
                'updated_at' => '2018-12-28 11:04:03',
                'deleted_at' => NULL,
            ),
            45 => 
            array (
                'id' => 52,
                'possui_doenca' => 2,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 2,
                'peso' => 63.52,
                'altura' => 1.75,
                'fumante' => 2,
                'cirurgia' => 1,
                'dor_muscular' => 2,
                'dor_ossea' => 2,
                'dor_articular' => 2,
                'atestado' => NULL,
                'observacao' => NULL,
                'ano' => 2018,
                'pessoas_id' => 18,
                'created_at' => '2018-12-28 11:18:52',
                'updated_at' => '2018-12-28 11:18:52',
                'deleted_at' => NULL,
            ),
            46 => 
            array (
                'id' => 53,
                'possui_doenca' => 1,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 1,
                'peso' => 58.65,
                'altura' => 1.58,
                'fumante' => 2,
                'cirurgia' => 2,
                'dor_muscular' => 2,
                'dor_ossea' => 2,
                'dor_articular' => 2,
                'atestado' => 2,
                'observacao' => NULL,
                'ano' => 2016,
                'pessoas_id' => 19,
                'created_at' => '2018-12-28 11:27:15',
                'updated_at' => '2018-12-28 11:27:15',
                'deleted_at' => NULL,
            ),
            47 => 
            array (
                'id' => 55,
                'possui_doenca' => 2,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 2,
                'peso' => 59.2,
                'altura' => 1.65,
                'fumante' => 2,
                'cirurgia' => 2,
                'dor_muscular' => 2,
                'dor_ossea' => 2,
                'dor_articular' => 2,
                'atestado' => 2,
                'observacao' => NULL,
                'ano' => 2016,
                'pessoas_id' => 21,
                'created_at' => '2018-12-28 11:34:35',
                'updated_at' => '2018-12-28 11:34:35',
                'deleted_at' => NULL,
            ),
            48 => 
            array (
                'id' => 56,
                'possui_doenca' => 1,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 1,
                'peso' => 80.18,
                'altura' => 1.73,
                'fumante' => 2,
                'cirurgia' => 1,
                'dor_muscular' => 1,
                'dor_ossea' => 2,
                'dor_articular' => 1,
                'atestado' => 2,
                'observacao' => NULL,
                'ano' => 2016,
                'pessoas_id' => 22,
                'created_at' => '2018-12-28 12:16:46',
                'updated_at' => '2018-12-28 12:16:46',
                'deleted_at' => NULL,
            ),
            49 => 
            array (
                'id' => 57,
                'possui_doenca' => 1,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 2,
                'peso' => 82.52,
                'altura' => 1.63,
                'fumante' => 1,
                'cirurgia' => 1,
                'dor_muscular' => 2,
                'dor_ossea' => 1,
                'dor_articular' => 2,
                'atestado' => 2,
                'observacao' => NULL,
                'ano' => 2016,
                'pessoas_id' => 23,
                'created_at' => '2018-12-28 12:21:56',
                'updated_at' => '2018-12-28 12:21:56',
                'deleted_at' => NULL,
            ),
            50 => 
            array (
                'id' => 58,
                'possui_doenca' => 1,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 2,
                'peso' => 96.1,
                'altura' => 1.75,
                'fumante' => 2,
                'cirurgia' => 2,
                'dor_muscular' => 2,
                'dor_ossea' => 1,
                'dor_articular' => 2,
                'atestado' => 2,
                'observacao' => NULL,
                'ano' => 2016,
                'pessoas_id' => 24,
                'created_at' => '2018-12-28 12:29:43',
                'updated_at' => '2018-12-28 12:29:43',
                'deleted_at' => NULL,
            ),
            51 => 
            array (
                'id' => 59,
                'possui_doenca' => 1,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 2,
                'peso' => 80.56,
                'altura' => 1.63,
                'fumante' => 2,
                'cirurgia' => 1,
                'dor_muscular' => 2,
                'dor_ossea' => 2,
                'dor_articular' => 1,
                'atestado' => NULL,
                'observacao' => NULL,
                'ano' => 2017,
                'pessoas_id' => 23,
                'created_at' => '2018-12-28 13:13:05',
                'updated_at' => '2018-12-28 13:13:05',
                'deleted_at' => NULL,
            ),
            52 => 
            array (
                'id' => 60,
                'possui_doenca' => 2,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 2,
                'peso' => 80.89,
                'altura' => 1.63,
                'fumante' => 2,
                'cirurgia' => 1,
                'dor_muscular' => 2,
                'dor_ossea' => 2,
                'dor_articular' => 2,
                'atestado' => NULL,
                'observacao' => NULL,
                'ano' => 2018,
                'pessoas_id' => 23,
                'created_at' => '2018-12-28 13:13:54',
                'updated_at' => '2018-12-28 13:13:54',
                'deleted_at' => NULL,
            ),
            53 => 
            array (
                'id' => 61,
                'possui_doenca' => 1,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 2,
                'peso' => 63.23,
                'altura' => 1.75,
                'fumante' => 2,
                'cirurgia' => 2,
                'dor_muscular' => 2,
                'dor_ossea' => 1,
                'dor_articular' => 2,
                'atestado' => NULL,
                'observacao' => NULL,
                'ano' => 2017,
                'pessoas_id' => 24,
                'created_at' => '2018-12-28 13:15:13',
                'updated_at' => '2018-12-28 13:15:13',
                'deleted_at' => NULL,
            ),
            54 => 
            array (
                'id' => 62,
                'possui_doenca' => 1,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 2,
                'peso' => 80.0,
                'altura' => 1.63,
                'fumante' => 2,
                'cirurgia' => 2,
                'dor_muscular' => 2,
                'dor_ossea' => 1,
                'dor_articular' => 2,
                'atestado' => NULL,
                'observacao' => NULL,
                'ano' => 2018,
                'pessoas_id' => 24,
                'created_at' => '2018-12-28 13:15:52',
                'updated_at' => '2018-12-28 13:15:52',
                'deleted_at' => NULL,
            ),
            55 => 
            array (
                'id' => 63,
                'possui_doenca' => 2,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 1,
                'peso' => 60.0,
                'altura' => 1.6,
                'fumante' => 2,
                'cirurgia' => 2,
                'dor_muscular' => 2,
                'dor_ossea' => 2,
                'dor_articular' => 2,
                'atestado' => NULL,
                'observacao' => NULL,
                'ano' => 2017,
                'pessoas_id' => 19,
                'created_at' => '2018-12-28 13:18:10',
                'updated_at' => '2018-12-28 13:18:10',
                'deleted_at' => NULL,
            ),
            56 => 
            array (
                'id' => 64,
                'possui_doenca' => 1,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 2,
                'peso' => 61.2,
                'altura' => 1.6800000000000002,
                'fumante' => 2,
                'cirurgia' => 2,
                'dor_muscular' => 2,
                'dor_ossea' => 2,
                'dor_articular' => 2,
                'atestado' => NULL,
                'observacao' => 'Incapaz de correr temporariamente',
                'ano' => 2017,
                'pessoas_id' => 21,
                'created_at' => '2018-12-28 13:24:08',
                'updated_at' => '2018-12-28 13:24:08',
                'deleted_at' => NULL,
            ),
            57 => 
            array (
                'id' => 65,
                'possui_doenca' => 1,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 2,
                'peso' => 64.2,
                'altura' => 1.6800000000000002,
                'fumante' => 2,
                'cirurgia' => 2,
                'dor_muscular' => 2,
                'dor_ossea' => 2,
                'dor_articular' => 2,
                'atestado' => NULL,
                'observacao' => NULL,
                'ano' => 2018,
                'pessoas_id' => 21,
                'created_at' => '2018-12-28 13:24:50',
                'updated_at' => '2018-12-28 13:24:50',
                'deleted_at' => NULL,
            ),
            58 => 
            array (
                'id' => 66,
                'possui_doenca' => 1,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 1,
                'peso' => 75.53,
                'altura' => 1.73,
                'fumante' => 2,
                'cirurgia' => 1,
                'dor_muscular' => 2,
                'dor_ossea' => 2,
                'dor_articular' => 2,
                'atestado' => NULL,
                'observacao' => NULL,
                'ano' => 2017,
                'pessoas_id' => 22,
                'created_at' => '2018-12-28 13:28:40',
                'updated_at' => '2018-12-28 13:28:40',
                'deleted_at' => NULL,
            ),
            59 => 
            array (
                'id' => 67,
                'possui_doenca' => 1,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 1,
                'peso' => 73.1,
                'altura' => 1.73,
                'fumante' => 2,
                'cirurgia' => 1,
                'dor_muscular' => 2,
                'dor_ossea' => 2,
                'dor_articular' => 1,
                'atestado' => NULL,
                'observacao' => NULL,
                'ano' => 2018,
                'pessoas_id' => 22,
                'created_at' => '2018-12-28 13:31:02',
                'updated_at' => '2018-12-28 13:31:02',
                'deleted_at' => NULL,
            ),
            60 => 
            array (
                'id' => 68,
                'possui_doenca' => 1,
                'toma_medicacao' => 2,
                'alergia_medicacao' => 2,
                'peso' => 70.2,
                'altura' => 1.76,
                'fumante' => 2,
                'cirurgia' => 1,
                'dor_muscular' => 1,
                'dor_ossea' => 2,
                'dor_articular' => 2,
                'atestado' => 2,
                'observacao' => NULL,
                'ano' => 2017,
                'pessoas_id' => 25,
                'created_at' => '2018-12-28 13:36:33',
                'updated_at' => '2018-12-28 13:36:33',
                'deleted_at' => NULL,
            ),
            61 => 
            array (
                'id' => 69,
                'possui_doenca' => 2,
                'toma_medicacao' => 2,
                'alergia_medicacao' => 2,
                'peso' => 65.02,
                'altura' => 1.63,
                'fumante' => 1,
                'cirurgia' => 2,
                'dor_muscular' => 2,
                'dor_ossea' => 2,
                'dor_articular' => 2,
                'atestado' => 2,
                'observacao' => NULL,
                'ano' => 2017,
                'pessoas_id' => 26,
                'created_at' => '2018-12-28 13:49:27',
                'updated_at' => '2018-12-28 13:49:27',
                'deleted_at' => NULL,
            ),
            62 => 
            array (
                'id' => 70,
                'possui_doenca' => 1,
                'toma_medicacao' => 2,
                'alergia_medicacao' => 2,
                'peso' => 73.62,
                'altura' => 1.65,
                'fumante' => 2,
                'cirurgia' => 2,
                'dor_muscular' => 2,
                'dor_ossea' => 1,
                'dor_articular' => 2,
                'atestado' => 2,
                'observacao' => NULL,
                'ano' => 2017,
                'pessoas_id' => 27,
                'created_at' => '2018-12-28 13:52:40',
                'updated_at' => '2018-12-28 13:52:40',
                'deleted_at' => NULL,
            ),
            63 => 
            array (
                'id' => 71,
                'possui_doenca' => 2,
                'toma_medicacao' => 2,
                'alergia_medicacao' => 2,
                'peso' => 72.98,
                'altura' => 1.75,
                'fumante' => 1,
                'cirurgia' => 2,
                'dor_muscular' => 1,
                'dor_ossea' => 2,
                'dor_articular' => 2,
                'atestado' => 2,
                'observacao' => 'Braço quebrado',
                'ano' => 2017,
                'pessoas_id' => 28,
                'created_at' => '2018-12-28 14:31:59',
                'updated_at' => '2018-12-28 14:31:59',
                'deleted_at' => NULL,
            ),
            64 => 
            array (
                'id' => 72,
                'possui_doenca' => 1,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 2,
                'peso' => 57.86,
                'altura' => 1.58,
                'fumante' => 2,
                'cirurgia' => 1,
                'dor_muscular' => 2,
                'dor_ossea' => 2,
                'dor_articular' => 2,
                'atestado' => 2,
                'observacao' => NULL,
                'ano' => 2016,
                'pessoas_id' => 29,
                'created_at' => '2018-12-28 15:15:48',
                'updated_at' => '2018-12-28 15:15:48',
                'deleted_at' => NULL,
            ),
            65 => 
            array (
                'id' => 73,
                'possui_doenca' => 1,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 2,
                'peso' => 64.0,
                'altura' => 1.75,
                'fumante' => 2,
                'cirurgia' => 1,
                'dor_muscular' => 2,
                'dor_ossea' => 2,
                'dor_articular' => 1,
                'atestado' => NULL,
                'observacao' => NULL,
                'ano' => 2018,
                'pessoas_id' => 28,
                'created_at' => '2018-12-28 15:19:37',
                'updated_at' => '2018-12-28 15:19:37',
                'deleted_at' => NULL,
            ),
            66 => 
            array (
                'id' => 74,
                'possui_doenca' => 2,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 2,
                'peso' => 59.12,
                'altura' => 1.6,
                'fumante' => 2,
                'cirurgia' => 1,
                'dor_muscular' => 2,
                'dor_ossea' => 2,
                'dor_articular' => 2,
                'atestado' => NULL,
                'observacao' => NULL,
                'ano' => 2017,
                'pessoas_id' => 29,
                'created_at' => '2018-12-28 15:21:05',
                'updated_at' => '2018-12-28 15:21:05',
                'deleted_at' => NULL,
            ),
            67 => 
            array (
                'id' => 75,
                'possui_doenca' => 1,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 2,
                'peso' => 62.23,
                'altura' => 1.62,
                'fumante' => 2,
                'cirurgia' => 1,
                'dor_muscular' => 2,
                'dor_ossea' => 2,
                'dor_articular' => 2,
                'atestado' => NULL,
                'observacao' => NULL,
                'ano' => 2018,
                'pessoas_id' => 29,
                'created_at' => '2018-12-28 15:21:48',
                'updated_at' => '2018-12-28 15:21:48',
                'deleted_at' => NULL,
            ),
            68 => 
            array (
                'id' => 76,
                'possui_doenca' => 2,
                'toma_medicacao' => 2,
                'alergia_medicacao' => 1,
                'peso' => 55.12,
                'altura' => 1.63,
                'fumante' => 2,
                'cirurgia' => 2,
                'dor_muscular' => 2,
                'dor_ossea' => 2,
                'dor_articular' => 1,
                'atestado' => NULL,
                'observacao' => NULL,
                'ano' => 2018,
                'pessoas_id' => 19,
                'created_at' => '2018-12-28 15:23:36',
                'updated_at' => '2018-12-28 15:23:36',
                'deleted_at' => NULL,
            ),
            69 => 
            array (
                'id' => 77,
                'possui_doenca' => 2,
                'toma_medicacao' => 2,
                'alergia_medicacao' => 2,
                'peso' => 70.56,
                'altura' => 1.6,
                'fumante' => 2,
                'cirurgia' => 2,
                'dor_muscular' => 2,
                'dor_ossea' => 2,
                'dor_articular' => 2,
                'atestado' => NULL,
                'observacao' => NULL,
                'ano' => 2018,
                'pessoas_id' => 27,
                'created_at' => '2018-12-28 15:25:56',
                'updated_at' => '2018-12-28 15:25:56',
                'deleted_at' => NULL,
            ),
            70 => 
            array (
                'id' => 78,
                'possui_doenca' => 1,
                'toma_medicacao' => 2,
                'alergia_medicacao' => 2,
                'peso' => 70.65,
                'altura' => 1.75,
                'fumante' => 2,
                'cirurgia' => 2,
                'dor_muscular' => 2,
                'dor_ossea' => 2,
                'dor_articular' => 2,
                'atestado' => 2,
                'observacao' => NULL,
                'ano' => 2018,
                'pessoas_id' => 30,
                'created_at' => '2018-12-28 15:32:25',
                'updated_at' => '2018-12-28 15:32:25',
                'deleted_at' => NULL,
            ),
            71 => 
            array (
                'id' => 79,
                'possui_doenca' => 1,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 2,
                'peso' => 61.85,
                'altura' => 1.7,
                'fumante' => 2,
                'cirurgia' => 1,
                'dor_muscular' => 1,
                'dor_ossea' => 2,
                'dor_articular' => 2,
                'atestado' => 2,
                'observacao' => NULL,
                'ano' => 2018,
                'pessoas_id' => 31,
                'created_at' => '2018-12-28 15:38:21',
                'updated_at' => '2018-12-28 15:38:21',
                'deleted_at' => NULL,
            ),
            72 => 
            array (
                'id' => 80,
                'possui_doenca' => 1,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 1,
                'peso' => 59.2,
                'altura' => 1.6800000000000002,
                'fumante' => 2,
                'cirurgia' => 1,
                'dor_muscular' => 2,
                'dor_ossea' => 1,
                'dor_articular' => 2,
                'atestado' => 2,
                'observacao' => NULL,
                'ano' => 2018,
                'pessoas_id' => 32,
                'created_at' => '2018-12-28 15:40:44',
                'updated_at' => '2018-12-28 15:40:44',
                'deleted_at' => NULL,
            ),
            73 => 
            array (
                'id' => 81,
                'possui_doenca' => 2,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 2,
                'peso' => 75.68,
                'altura' => 1.6,
                'fumante' => 2,
                'cirurgia' => 2,
                'dor_muscular' => 2,
                'dor_ossea' => 2,
                'dor_articular' => 2,
                'atestado' => 2,
                'observacao' => NULL,
                'ano' => 2018,
                'pessoas_id' => 33,
                'created_at' => '2018-12-28 15:44:04',
                'updated_at' => '2018-12-28 15:44:04',
                'deleted_at' => NULL,
            ),
            74 => 
            array (
                'id' => 82,
                'possui_doenca' => 1,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 2,
                'peso' => 76.89,
                'altura' => 1.73,
                'fumante' => 2,
                'cirurgia' => 2,
                'dor_muscular' => 1,
                'dor_ossea' => 2,
                'dor_articular' => 1,
                'atestado' => 2,
                'observacao' => NULL,
                'ano' => 2018,
                'pessoas_id' => 34,
                'created_at' => '2018-12-28 15:46:58',
                'updated_at' => '2018-12-28 15:46:58',
                'deleted_at' => NULL,
            ),
            75 => 
            array (
                'id' => 83,
                'possui_doenca' => 1,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 2,
                'peso' => 49.1,
                'altura' => 1.5899999999999999,
                'fumante' => 2,
                'cirurgia' => 2,
                'dor_muscular' => 1,
                'dor_ossea' => 2,
                'dor_articular' => 2,
                'atestado' => NULL,
                'observacao' => NULL,
                'ano' => 2019,
                'pessoas_id' => 12,
                'created_at' => '2019-01-02 10:34:43',
                'updated_at' => '2019-01-02 10:34:43',
                'deleted_at' => NULL,
            ),
            76 => 
            array (
                'id' => 84,
                'possui_doenca' => 1,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 1,
                'peso' => 60.1,
                'altura' => 1.69,
                'fumante' => 2,
                'cirurgia' => 1,
                'dor_muscular' => 2,
                'dor_ossea' => 2,
                'dor_articular' => 2,
                'atestado' => NULL,
                'observacao' => NULL,
                'ano' => 2019,
                'pessoas_id' => 32,
                'created_at' => '2019-01-02 10:39:30',
                'updated_at' => '2019-01-02 10:39:30',
                'deleted_at' => NULL,
            ),
            77 => 
            array (
                'id' => 85,
                'possui_doenca' => 2,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 2,
                'peso' => 80.0,
                'altura' => 1.5699999999999998,
                'fumante' => 2,
                'cirurgia' => 1,
                'dor_muscular' => 2,
                'dor_ossea' => 1,
                'dor_articular' => 1,
                'atestado' => NULL,
                'observacao' => 'Acima do peso',
                'ano' => 2019,
                'pessoas_id' => 11,
                'created_at' => '2019-01-02 10:43:29',
                'updated_at' => '2019-01-02 10:43:29',
                'deleted_at' => NULL,
            ),
            78 => 
            array (
                'id' => 86,
                'possui_doenca' => 2,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 2,
                'peso' => 65.13,
                'altura' => 1.76,
                'fumante' => 2,
                'cirurgia' => 1,
                'dor_muscular' => 2,
                'dor_ossea' => 2,
                'dor_articular' => 2,
                'atestado' => NULL,
                'observacao' => NULL,
                'ano' => 2019,
                'pessoas_id' => 18,
                'created_at' => '2019-01-02 10:45:55',
                'updated_at' => '2019-01-02 10:45:55',
                'deleted_at' => NULL,
            ),
            79 => 
            array (
                'id' => 87,
                'possui_doenca' => 2,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 2,
                'peso' => 70.43,
                'altura' => 1.7,
                'fumante' => 2,
                'cirurgia' => 1,
                'dor_muscular' => 2,
                'dor_ossea' => 2,
                'dor_articular' => 2,
                'atestado' => NULL,
                'observacao' => NULL,
                'ano' => 2019,
                'pessoas_id' => 4,
                'created_at' => '2019-01-02 10:48:58',
                'updated_at' => '2019-01-02 10:48:58',
                'deleted_at' => NULL,
            ),
            80 => 
            array (
                'id' => 88,
                'possui_doenca' => 2,
                'toma_medicacao' => 2,
                'alergia_medicacao' => 2,
                'peso' => 62.3,
                'altura' => 1.62,
                'fumante' => 2,
                'cirurgia' => 1,
                'dor_muscular' => 2,
                'dor_ossea' => 2,
                'dor_articular' => 2,
                'atestado' => NULL,
                'observacao' => NULL,
                'ano' => 2019,
                'pessoas_id' => 29,
                'created_at' => '2019-01-02 11:07:28',
                'updated_at' => '2019-01-02 11:07:28',
                'deleted_at' => NULL,
            ),
            81 => 
            array (
                'id' => 89,
                'possui_doenca' => 1,
                'toma_medicacao' => 2,
                'alergia_medicacao' => 2,
                'peso' => 65.12,
                'altura' => 1.65,
                'fumante' => 2,
                'cirurgia' => 1,
                'dor_muscular' => 2,
                'dor_ossea' => 2,
                'dor_articular' => 2,
                'atestado' => NULL,
                'observacao' => NULL,
                'ano' => 2019,
                'pessoas_id' => 3,
                'created_at' => '2019-01-02 11:12:27',
                'updated_at' => '2019-01-02 11:13:01',
                'deleted_at' => NULL,
            ),
            82 => 
            array (
                'id' => 90,
                'possui_doenca' => 2,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 2,
                'peso' => 88.0,
                'altura' => 1.62,
                'fumante' => 1,
                'cirurgia' => 1,
                'dor_muscular' => 2,
                'dor_ossea' => 1,
                'dor_articular' => 2,
                'atestado' => NULL,
                'observacao' => NULL,
                'ano' => 2019,
                'pessoas_id' => 17,
                'created_at' => '2019-01-02 11:15:34',
                'updated_at' => '2019-01-02 11:15:34',
                'deleted_at' => NULL,
            ),
            83 => 
            array (
                'id' => 91,
                'possui_doenca' => 1,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 2,
                'peso' => 76.1,
                'altura' => 1.63,
                'fumante' => 2,
                'cirurgia' => 1,
                'dor_muscular' => 2,
                'dor_ossea' => 1,
                'dor_articular' => 1,
                'atestado' => NULL,
                'observacao' => NULL,
                'ano' => 2019,
                'pessoas_id' => 23,
                'created_at' => '2019-01-02 11:19:36',
                'updated_at' => '2019-01-02 11:19:36',
                'deleted_at' => NULL,
            ),
            84 => 
            array (
                'id' => 92,
                'possui_doenca' => 2,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 2,
                'peso' => 85.65,
                'altura' => 1.63,
                'fumante' => 2,
                'cirurgia' => 2,
                'dor_muscular' => 2,
                'dor_ossea' => 1,
                'dor_articular' => 2,
                'atestado' => NULL,
                'observacao' => NULL,
                'ano' => 2019,
                'pessoas_id' => 24,
                'created_at' => '2019-01-02 11:23:57',
                'updated_at' => '2019-01-02 11:23:57',
                'deleted_at' => NULL,
            ),
            85 => 
            array (
                'id' => 93,
                'possui_doenca' => 1,
                'toma_medicacao' => 2,
                'alergia_medicacao' => 1,
                'peso' => 44.12,
                'altura' => 1.6600000000000001,
                'fumante' => 2,
                'cirurgia' => 2,
                'dor_muscular' => 2,
                'dor_ossea' => 2,
                'dor_articular' => 2,
                'atestado' => NULL,
                'observacao' => NULL,
                'ano' => 2019,
                'pessoas_id' => 19,
                'created_at' => '2019-01-02 11:27:39',
                'updated_at' => '2019-01-02 11:27:39',
                'deleted_at' => NULL,
            ),
            86 => 
            array (
                'id' => 94,
                'possui_doenca' => 1,
                'toma_medicacao' => 2,
                'alergia_medicacao' => 2,
                'peso' => 76.82,
                'altura' => 1.6099999999999999,
                'fumante' => 2,
                'cirurgia' => 1,
                'dor_muscular' => 2,
                'dor_ossea' => 2,
                'dor_articular' => 1,
                'atestado' => NULL,
                'observacao' => NULL,
                'ano' => 2019,
                'pessoas_id' => 15,
                'created_at' => '2019-01-02 11:30:53',
                'updated_at' => '2019-01-02 11:30:53',
                'deleted_at' => NULL,
            ),
            87 => 
            array (
                'id' => 95,
                'possui_doenca' => 2,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 2,
                'peso' => 76.4,
                'altura' => 1.73,
                'fumante' => 2,
                'cirurgia' => 2,
                'dor_muscular' => 2,
                'dor_ossea' => 1,
                'dor_articular' => 2,
                'atestado' => NULL,
                'observacao' => NULL,
                'ano' => 2019,
                'pessoas_id' => 34,
                'created_at' => '2019-01-02 11:33:52',
                'updated_at' => '2019-01-02 11:33:52',
                'deleted_at' => NULL,
            ),
            88 => 
            array (
                'id' => 96,
                'possui_doenca' => 2,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 2,
                'peso' => 89.1,
                'altura' => 1.72,
                'fumante' => 2,
                'cirurgia' => 2,
                'dor_muscular' => 1,
                'dor_ossea' => 1,
                'dor_articular' => 2,
                'atestado' => NULL,
                'observacao' => 'Idade avançada',
                'ano' => 2019,
                'pessoas_id' => 14,
                'created_at' => '2019-01-02 11:37:08',
                'updated_at' => '2019-01-02 11:37:20',
                'deleted_at' => NULL,
            ),
            89 => 
            array (
                'id' => 97,
                'possui_doenca' => 2,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 2,
                'peso' => 64.12,
                'altura' => 1.75,
                'fumante' => 2,
                'cirurgia' => 1,
                'dor_muscular' => 2,
                'dor_ossea' => 2,
                'dor_articular' => 1,
                'atestado' => NULL,
                'observacao' => NULL,
                'ano' => 2019,
                'pessoas_id' => 28,
                'created_at' => '2019-01-02 11:39:08',
                'updated_at' => '2019-01-02 11:39:08',
                'deleted_at' => NULL,
            ),
            90 => 
            array (
                'id' => 98,
                'possui_doenca' => 2,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 1,
                'peso' => 50.2,
                'altura' => 1.7,
                'fumante' => 2,
                'cirurgia' => 2,
                'dor_muscular' => 2,
                'dor_ossea' => 2,
                'dor_articular' => 2,
                'atestado' => NULL,
                'observacao' => NULL,
                'ano' => 2019,
                'pessoas_id' => 21,
                'created_at' => '2019-01-02 11:42:08',
                'updated_at' => '2019-01-02 11:42:08',
                'deleted_at' => NULL,
            ),
            91 => 
            array (
                'id' => 99,
                'possui_doenca' => 2,
                'toma_medicacao' => 2,
                'alergia_medicacao' => 1,
                'peso' => 74.2,
                'altura' => 1.65,
                'fumante' => 2,
                'cirurgia' => 1,
                'dor_muscular' => 2,
                'dor_ossea' => 2,
                'dor_articular' => 2,
                'atestado' => 1,
                'observacao' => NULL,
                'ano' => 2019,
                'pessoas_id' => 27,
                'created_at' => '2019-01-02 11:43:16',
                'updated_at' => '2019-01-02 11:45:13',
                'deleted_at' => NULL,
            ),
            92 => 
            array (
                'id' => 100,
                'possui_doenca' => 2,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 1,
                'peso' => 72.2,
                'altura' => 1.73,
                'fumante' => 2,
                'cirurgia' => 1,
                'dor_muscular' => 2,
                'dor_ossea' => 1,
                'dor_articular' => 2,
                'atestado' => NULL,
                'observacao' => NULL,
                'ano' => 2019,
                'pessoas_id' => 22,
                'created_at' => '2019-01-02 11:46:09',
                'updated_at' => '2019-01-02 11:46:09',
                'deleted_at' => NULL,
            ),
            93 => 
            array (
                'id' => 101,
                'possui_doenca' => 1,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 2,
                'peso' => 72.52,
                'altura' => 1.6099999999999999,
                'fumante' => 2,
                'cirurgia' => 2,
                'dor_muscular' => 1,
                'dor_ossea' => 1,
                'dor_articular' => 1,
                'atestado' => NULL,
                'observacao' => NULL,
                'ano' => 2019,
                'pessoas_id' => 33,
                'created_at' => '2019-01-02 11:48:02',
                'updated_at' => '2019-01-02 11:48:20',
                'deleted_at' => NULL,
            ),
            94 => 
            array (
                'id' => 102,
                'possui_doenca' => 2,
                'toma_medicacao' => 2,
                'alergia_medicacao' => 2,
                'peso' => 73.52,
                'altura' => 1.75,
                'fumante' => 2,
                'cirurgia' => 2,
                'dor_muscular' => 2,
                'dor_ossea' => 2,
                'dor_articular' => 2,
                'atestado' => NULL,
                'observacao' => NULL,
                'ano' => 2019,
                'pessoas_id' => 30,
                'created_at' => '2019-01-02 11:49:23',
                'updated_at' => '2019-01-02 11:49:23',
                'deleted_at' => NULL,
            ),
            95 => 
            array (
                'id' => 103,
                'possui_doenca' => 2,
                'toma_medicacao' => 1,
                'alergia_medicacao' => 2,
                'peso' => 62.52,
                'altura' => 1.7,
                'fumante' => 2,
                'cirurgia' => 1,
                'dor_muscular' => 2,
                'dor_ossea' => 2,
                'dor_articular' => 2,
                'atestado' => NULL,
                'observacao' => NULL,
                'ano' => 2019,
                'pessoas_id' => 31,
                'created_at' => '2019-01-02 11:51:24',
                'updated_at' => '2019-01-02 11:51:24',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}