<?php

use Illuminate\Database\Seeder;

class AuditsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('audits')->delete();
        
        \DB::table('audits')->insert(array (
            0 => 
            array (
                'id' => 1,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'updated',
                'auditable_type' => 'App\\User',
                'auditable_id' => 1,
                'old_values' => '{"remember_token":"knMUmmjxRciYk6H0VtLInj01RciqRnjkyU2uo8EB5cV5prC94spcwJcYogXm"}',
                'new_values' => '{"remember_token":"cntJ96qsZtfNlYaO674X4yfDyjIvp197IfEQupdMSjyzSqREwhjyIOHyX1sE"}',
                'url' => 'http://localhost/logout?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-26 14:06:50',
                'updated_at' => '2018-12-26 14:06:50',
            ),
            1 => 
            array (
                'id' => 2,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Pessoa',
                'auditable_id' => 1,
                'old_values' => '[]',
            'new_values' => '{"foto":"img\\/img_3x4\\/imagem_3888.png","nome":"Julio da Silva","nascimento":"1994-04-07","sexo":"M","rg":"51235121","cpf":"156.156.045-46","cpf_responsavel":null,"cidade":"S\\u00e3o Leopoldo","rua":"Ruas das Ar\\u00e1ras","bairro":"Bairro das Flores","numero_endereco":"620","cep":"41.981-210","telefone":"(56) 0980-1565","telefone_emergencia":"(56) 0198-1210","estado_civil":"Solteiro","nome_do_pai":"Juliano da Silva","nome_da_mae":"Juliana da Silva","pessoa_emergencia":"Julia da Silva (irm\\u00e3)","filhos":"0","convenio_medico":"SEN","mora_com_os_pais":"2","matricula":null,"estado":1,"id":1}',
                'url' => 'http://localhost/pessoas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-26 15:25:07',
                'updated_at' => '2018-12-26 15:25:07',
            ),
            2 => 
            array (
                'id' => 3,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Anamnese',
                'auditable_id' => 1,
                'old_values' => '[]',
                'new_values' => '{"atestado":"2","peso":"83","altura":"1.73","toma_medicacao":"1","alergia_medicacao":"2","fumante":"2","cirurgia":"1","dor_ossea":"2","dor_muscular":"2","dor_articular":"2","possui_doenca":"2","observacao":null,"ano":"2018","pessoas_id":1,"id":1}',
                'url' => 'http://localhost/pessoas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-26 15:25:07',
                'updated_at' => '2018-12-26 15:25:07',
            ),
            3 => 
            array (
                'id' => 4,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Nucleo',
                'auditable_id' => 1,
                'old_values' => '[]',
                'new_values' => '{"cidade":"S\\u00e3o Leopoldo","inativo":"1","nome":"N\\u00facleo Leste","bairro":"Bairro das Flores","rua":"Rua dos Elefantes","numero_endereco":"250","cep":"15.615-089","descricao":"Bairro ao leste da cidade","id":1}',
                'url' => 'http://localhost/nucleos?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-26 15:25:52',
                'updated_at' => '2018-12-26 15:25:52',
            ),
            4 => 
            array (
                'id' => 5,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Nucleo',
                'auditable_id' => 2,
                'old_values' => '[]',
                'new_values' => '{"cidade":"S\\u00e3o Leopoldo","inativo":"1","nome":"N\\u00facleo Norte","bairro":"Bairro dos Carros","rua":"Rua das Girafas","numero_endereco":"894","cep":"15.651-891","descricao":"Bairro ao norte da cidade","id":2}',
                'url' => 'http://localhost/nucleos?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-26 15:26:39',
                'updated_at' => '2018-12-26 15:26:39',
            ),
            5 => 
            array (
                'id' => 6,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Nucleo',
                'auditable_id' => 3,
                'old_values' => '[]',
                'new_values' => '{"cidade":"S\\u00e3o Leopoldo","inativo":"1","nome":"N\\u00facleo Oeste","bairro":"Bairro dos papeis","rua":"Rua dos Macacos","numero_endereco":"451","cep":"50.560-564","descricao":"Bairro ao oeste da cidade","id":3}',
                'url' => 'http://localhost/nucleos?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-26 15:27:23',
                'updated_at' => '2018-12-26 15:27:23',
            ),
            6 => 
            array (
                'id' => 7,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Nucleo',
                'auditable_id' => 4,
                'old_values' => '[]',
                'new_values' => '{"cidade":"S\\u00e3o Leopoldo","inativo":"1","nome":"N\\u00facleo Sul","bairro":"Bairro das canetas","rua":"Rua das on\\u00e7as","numero_endereco":"516","cep":"15.061-888","descricao":"Bairro ao sul da cidade","id":4}',
                'url' => 'http://localhost/nucleos?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-26 15:28:13',
                'updated_at' => '2018-12-26 15:28:13',
            ),
            7 => 
            array (
                'id' => 8,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Turma',
                'auditable_id' => 1,
                'old_values' => '[]',
                'new_values' => '{"nome":"Turma de Basquete A1","inativo":"1","limite":"10","horario_inicial":"12:00:00","horario_final":"14:00:00","data_semanal":"Segunda,Sexta,","nucleo_id":"2","descricao":"Turma de Basquete do norte","id":1}',
                'url' => 'http://localhost/turmas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-26 15:31:20',
                'updated_at' => '2018-12-26 15:31:20',
            ),
            8 => 
            array (
                'id' => 9,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Turma',
                'auditable_id' => 2,
                'old_values' => '[]',
                'new_values' => '{"nome":"Turma de Futebol A1","inativo":"1","limite":"8","horario_inicial":"12:00:00","horario_final":"14:00:00","data_semanal":"Ter\\u00e7a,Quinta,","nucleo_id":"1","descricao":null,"id":2}',
                'url' => 'http://localhost/turmas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-26 15:32:28',
                'updated_at' => '2018-12-26 15:32:28',
            ),
            9 => 
            array (
                'id' => 10,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Turma',
                'auditable_id' => 3,
                'old_values' => '[]',
                'new_values' => '{"nome":"Turma de Ginastica A1","inativo":"1","limite":"15","horario_inicial":"12:00:00","horario_final":"14:00:00","data_semanal":"Domingo,Sabado,","nucleo_id":"3","descricao":null,"id":3}',
                'url' => 'http://localhost/turmas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-26 15:33:24',
                'updated_at' => '2018-12-26 15:33:24',
            ),
            10 => 
            array (
                'id' => 11,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Turma',
                'auditable_id' => 4,
                'old_values' => '[]',
                'new_values' => '{"nome":"Turma de Basquete A2","inativo":"1","limite":"10","horario_inicial":"15:00:00","horario_final":"18:00:00","data_semanal":"Segunda,Quinta,","nucleo_id":"4","descricao":null,"id":4}',
                'url' => 'http://localhost/turmas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-26 15:35:39',
                'updated_at' => '2018-12-26 15:35:39',
            ),
            11 => 
            array (
                'id' => 12,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Turma',
                'auditable_id' => 5,
                'old_values' => '[]',
                'new_values' => '{"nome":"Turma de Futebol A2","inativo":"1","limite":"8","horario_inicial":"15:00:00","horario_final":"18:00:00","data_semanal":"Domingo,Sabado,","nucleo_id":"1","descricao":null,"id":5}',
                'url' => 'http://localhost/turmas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-26 15:36:31',
                'updated_at' => '2018-12-26 15:36:31',
            ),
            12 => 
            array (
                'id' => 13,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Turma',
                'auditable_id' => 6,
                'old_values' => '[]',
                'new_values' => '{"nome":"Turma de Ginastica A2","inativo":"1","limite":"15","horario_inicial":"15:00:00","horario_final":"18:00:00","data_semanal":"Segunda,Sexta,","nucleo_id":"4","descricao":null,"id":6}',
                'url' => 'http://localhost/turmas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-26 15:37:13',
                'updated_at' => '2018-12-26 15:37:13',
            ),
            13 => 
            array (
                'id' => 14,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Doenca',
                'auditable_id' => 1,
                'old_values' => '[]',
                'new_values' => '{"nome":"Acne","descricao":"Sens\\u00edvel ao sol.","id":1}',
                'url' => 'http://localhost/doencas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-26 15:38:19',
                'updated_at' => '2018-12-26 15:38:19',
            ),
            14 => 
            array (
                'id' => 15,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Doenca',
                'auditable_id' => 2,
                'old_values' => '[]',
                'new_values' => '{"nome":"Gripe","descricao":"Contagiante, problemas respirat\\u00f3rios","id":2}',
                'url' => 'http://localhost/doencas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-26 15:38:45',
                'updated_at' => '2018-12-26 15:38:45',
            ),
            15 => 
            array (
                'id' => 16,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Doenca',
                'auditable_id' => 3,
                'old_values' => '[]',
                'new_values' => '{"nome":"Tosse","descricao":"Problemas respirat\\u00f3rios, dor de garganta","id":3}',
                'url' => 'http://localhost/doencas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-26 15:39:06',
                'updated_at' => '2018-12-26 15:39:06',
            ),
            16 => 
            array (
                'id' => 17,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Doenca',
                'auditable_id' => 4,
                'old_values' => '[]',
                'new_values' => '{"nome":"Press\\u00e3o alta","descricao":"Desmaios, Necessidade de descano","id":4}',
                'url' => 'http://localhost/doencas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-26 15:39:57',
                'updated_at' => '2018-12-26 15:39:57',
            ),
            17 => 
            array (
                'id' => 18,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'updated',
                'auditable_type' => 'App\\Doenca',
                'auditable_id' => 4,
                'old_values' => '{"descricao":"Desmaios, Necessidade de descano"}',
                'new_values' => '{"descricao":"Desmaios, Necessidade de descanso"}',
                'url' => 'http://localhost/doencas/4?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-26 15:40:11',
                'updated_at' => '2018-12-26 15:40:11',
            ),
            18 => 
            array (
                'id' => 19,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'updated',
                'auditable_type' => 'App\\Doenca',
                'auditable_id' => 2,
                'old_values' => '{"descricao":"Contagiante, problemas respirat\\u00f3rios"}',
                'new_values' => '{"descricao":"Contagiante, problemas respirat\\u00f3rios."}',
                'url' => 'http://localhost/doencas/2?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-26 15:40:15',
                'updated_at' => '2018-12-26 15:40:15',
            ),
            19 => 
            array (
                'id' => 20,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'updated',
                'auditable_type' => 'App\\Doenca',
                'auditable_id' => 4,
                'old_values' => '{"descricao":"Desmaios, Necessidade de descanso"}',
                'new_values' => '{"descricao":"Desmaios, Necessidade de descanso."}',
                'url' => 'http://localhost/doencas/4?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-26 15:40:18',
                'updated_at' => '2018-12-26 15:40:18',
            ),
            20 => 
            array (
                'id' => 21,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'updated',
                'auditable_type' => 'App\\Doenca',
                'auditable_id' => 3,
                'old_values' => '{"descricao":"Problemas respirat\\u00f3rios, dor de garganta"}',
                'new_values' => '{"descricao":"Problemas respirat\\u00f3rios, dor de garganta."}',
                'url' => 'http://localhost/doencas/3?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-26 15:40:21',
                'updated_at' => '2018-12-26 15:40:21',
            ),
            21 => 
            array (
                'id' => 22,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'deleted',
                'auditable_type' => 'App\\Doenca',
                'auditable_id' => 4,
                'old_values' => '{"id":4,"nome":"Press\\u00e3o alta","descricao":"Desmaios, Necessidade de descanso."}',
                'new_values' => '[]',
                'url' => 'http://localhost/doencas/delete?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-26 15:42:01',
                'updated_at' => '2018-12-26 15:42:01',
            ),
            22 => 
            array (
                'id' => 23,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\User',
                'auditable_id' => 2,
                'old_values' => '[]',
                'new_values' => '{"name":"yuri","email":"yuri@yuri.com","password":"$2y$10$vvnoZWd7ykMK6nVtAY.bVOpcmfttXEj\\/Pu2ofbdew7iJngk1MjmUa","admin_professor":0,"id":2}',
                'url' => 'http://localhost/professor?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-26 15:45:38',
                'updated_at' => '2018-12-26 15:45:38',
            ),
            23 => 
            array (
                'id' => 24,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Professor',
                'auditable_id' => 1,
                'old_values' => '[]',
            'new_values' => '{"nome":"Yuri","matricula":"14551565","nascimento":"1989-03-08","bairro":"Bairro dos arm\\u00e1rios","rua":"Rua das Panteras","numero_endereco":"251","cep":"56.561-810","telefone":"(51) 1650-1651","cpf":"560.859.601-51","rg":"51601809","curso":"Curso em Futebol","formacao":"Forma\\u00e7\\u00e3o em educa\\u00e7\\u00e3o f\\u00edsica","cidade":"S\\u00e3o Leopoldo","user_id":2,"id":1}',
                'url' => 'http://localhost/professor?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-26 15:45:38',
                'updated_at' => '2018-12-26 15:45:38',
            ),
            24 => 
            array (
                'id' => 25,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\User',
                'auditable_id' => 3,
                'old_values' => '[]',
                'new_values' => '{"name":"oscar","email":"oscar@oscar.com","password":"$2y$10$\\/3etdWvPryUp0HLW7iWbY.JzfTmT2lUYqS6NZvMFcb0QVnD2f4ikm","admin_professor":0,"id":3}',
                'url' => 'http://localhost/professor?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-26 15:47:39',
                'updated_at' => '2018-12-26 15:47:39',
            ),
            25 => 
            array (
                'id' => 26,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Professor',
                'auditable_id' => 2,
                'old_values' => '[]',
            'new_values' => '{"nome":"Oscar","matricula":"1561851","nascimento":"1991-08-14","bairro":"Bairro das Flores","rua":"Ruas das Ar\\u00e1ras","numero_endereco":"098","cep":"15.156-515","telefone":"(18) 9480-8941","cpf":"618.908.503-27","rg":"18941561","curso":"Curso em Ginastica","formacao":"Forma\\u00e7\\u00e3o em educa\\u00e7\\u00e3o f\\u00edsica","cidade":"S\\u00e3o Leopoldo","user_id":3,"id":2}',
                'url' => 'http://localhost/professor?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-26 15:47:39',
                'updated_at' => '2018-12-26 15:47:39',
            ),
            26 => 
            array (
                'id' => 27,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\User',
                'auditable_id' => 4,
                'old_values' => '[]',
                'new_values' => '{"name":"fernando","email":"fernando@fernando.com","password":"$2y$10$Ccqhy\\/KQWaPsefO3L9kxhOkBJDrLG5NWDM.Xv\\/gCTDSMkdZTx6YHG","admin_professor":0,"id":4}',
                'url' => 'http://localhost/professor?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-26 15:50:06',
                'updated_at' => '2018-12-26 15:50:06',
            ),
            27 => 
            array (
                'id' => 28,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Professor',
                'auditable_id' => 3,
                'old_values' => '[]',
            'new_values' => '{"nome":"Fernando","matricula":"1864651","nascimento":"1983-11-16","bairro":"Bairro das Comidas","rua":"Rua dos Cachorros","numero_endereco":"262","cep":"56.165-051","telefone":"(16) 5108-5749","cpf":"864.018.412-62","rg":"15616581","curso":"Curso em Basquete","formacao":"Forma\\u00e7\\u00e3o em educa\\u00e7\\u00e3o f\\u00edsica","cidade":"S\\u00e3o Leopoldo","user_id":4,"id":3}',
                'url' => 'http://localhost/professor?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-26 15:50:06',
                'updated_at' => '2018-12-26 15:50:06',
            ),
            28 => 
            array (
                'id' => 29,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'updated',
                'auditable_type' => 'App\\Pessoa',
                'auditable_id' => 1,
                'old_values' => '{"nascimento":"1994-04-07 00:00:00","rua":"Ruas das Ar\\u00e1ras"}',
                'new_values' => '{"nascimento":"1994-04-07","rua":"Rua das Ar\\u00e1ras"}',
                'url' => 'http://localhost/pessoas/1?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-26 15:50:53',
                'updated_at' => '2018-12-26 15:50:53',
            ),
            29 => 
            array (
                'id' => 30,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\User',
                'auditable_id' => 5,
                'old_values' => '[]',
                'new_values' => '{"name":"mario","email":"mario@mario.com","password":"$2y$10$Jtas9u7Oh1fHZbCmIRxD3u5aj.wv6vlmnAn1jY3B8RUEEAQIJ4EJu","admin_professor":0,"id":5}',
                'url' => 'http://localhost/professor?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-26 15:54:40',
                'updated_at' => '2018-12-26 15:54:40',
            ),
            30 => 
            array (
                'id' => 31,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Professor',
                'auditable_id' => 4,
                'old_values' => '[]',
            'new_values' => '{"nome":"Mario","matricula":"2165150","nascimento":"1981-02-04","bairro":"Bairro das Comidas","rua":"Rua das Gaivotas","numero_endereco":"518","cep":"15.156-112","telefone":"(18) 9618-0665","cpf":"486.100.894-51","rg":"4896012","curso":"Curso de Basquete","formacao":"Forma\\u00e7\\u00e3o em educa\\u00e7\\u00e3o f\\u00edsica","cidade":"S\\u00e3o Leopoldo","user_id":5,"id":4}',
                'url' => 'http://localhost/professor?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-26 15:54:40',
                'updated_at' => '2018-12-26 15:54:40',
            ),
            31 => 
            array (
                'id' => 32,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Doenca',
                'auditable_id' => 5,
                'old_values' => '[]',
                'new_values' => '{"nome":"Alergia de Pele","descricao":"Sens\\u00edvel ao sol, problemas de alergia","id":5}',
                'url' => 'http://localhost/doencas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-26 15:57:31',
                'updated_at' => '2018-12-26 15:57:31',
            ),
            32 => 
            array (
                'id' => 33,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Doenca',
                'auditable_id' => 6,
                'old_values' => '[]',
                'new_values' => '{"nome":"Ins\\u00f4nia","descricao":"Cansa\\u00e7o, problemas de resist\\u00eancia, fadiga.","id":6}',
                'url' => 'http://localhost/doencas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-26 15:58:15',
                'updated_at' => '2018-12-26 15:58:15',
            ),
            33 => 
            array (
                'id' => 34,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'updated',
                'auditable_type' => 'App\\Doenca',
                'auditable_id' => 5,
                'old_values' => '{"descricao":"Sens\\u00edvel ao sol, problemas de alergia"}',
                'new_values' => '{"descricao":"Sens\\u00edvel ao sol, problemas de alergia."}',
                'url' => 'http://localhost/doencas/5?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-26 15:58:19',
                'updated_at' => '2018-12-26 15:58:19',
            ),
        ));
        
        
    }
}