<?php

use Illuminate\Database\Seeder;

class AuditsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('Audits')->delete();
        
        \DB::table('Audits')->insert(array (
            0 => 
            array (
                'id' => 1,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'updated',
                'auditable_type' => 'App\\User',
                'auditable_id' => 1,
                'old_values' => '{"remember_token":"knMUmmjxRciYk6H0VtLInj01RciqRnjkyU2uo8EB5cV5prC94spcwJcYogXm"}',
                'new_values' => '{"remember_token":"cntJ96qsZtfNlYaO674X4yfDyjIvp197IfEQupdMSjyzSqREwhjyIOHyX1sE"}',
                'url' => 'http://localhost/logout?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-26 14:06:50',
                'updated_at' => '2018-12-26 14:06:50',
            ),
            1 => 
            array (
                'id' => 2,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Pessoa',
                'auditable_id' => 1,
                'old_values' => '[]',
            'new_values' => '{"foto":"img\\/img_3x4\\/imagem_3888.png","nome":"Julio da Silva","nascimento":"1994-04-07","sexo":"M","rg":"51235121","cpf":"156.156.045-46","cpf_responsavel":null,"cidade":"S\\u00e3o Leopoldo","rua":"Ruas das Ar\\u00e1ras","bairro":"Bairro das Flores","numero_endereco":"620","cep":"41.981-210","telefone":"(56) 0980-1565","telefone_emergencia":"(56) 0198-1210","estado_civil":"Solteiro","nome_do_pai":"Juliano da Silva","nome_da_mae":"Juliana da Silva","pessoa_emergencia":"Julia da Silva (irm\\u00e3)","filhos":"0","convenio_medico":"SEN","mora_com_os_pais":"2","matricula":null,"estado":1,"id":1}',
                'url' => 'http://localhost/pessoas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-26 15:25:07',
                'updated_at' => '2018-12-26 15:25:07',
            ),
            2 => 
            array (
                'id' => 3,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Anamnese',
                'auditable_id' => 1,
                'old_values' => '[]',
                'new_values' => '{"atestado":"2","peso":"83","altura":"1.73","toma_medicacao":"1","alergia_medicacao":"2","fumante":"2","cirurgia":"1","dor_ossea":"2","dor_muscular":"2","dor_articular":"2","possui_doenca":"2","observacao":null,"ano":"2018","pessoas_id":1,"id":1}',
                'url' => 'http://localhost/pessoas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-26 15:25:07',
                'updated_at' => '2018-12-26 15:25:07',
            ),
            3 => 
            array (
                'id' => 4,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Nucleo',
                'auditable_id' => 1,
                'old_values' => '[]',
                'new_values' => '{"cidade":"S\\u00e3o Leopoldo","inativo":"1","nome":"N\\u00facleo Leste","bairro":"Bairro das Flores","rua":"Rua dos Elefantes","numero_endereco":"250","cep":"15.615-089","descricao":"Bairro ao leste da cidade","id":1}',
                'url' => 'http://localhost/nucleos?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-26 15:25:52',
                'updated_at' => '2018-12-26 15:25:52',
            ),
            4 => 
            array (
                'id' => 5,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Nucleo',
                'auditable_id' => 2,
                'old_values' => '[]',
                'new_values' => '{"cidade":"S\\u00e3o Leopoldo","inativo":"1","nome":"N\\u00facleo Norte","bairro":"Bairro dos Carros","rua":"Rua das Girafas","numero_endereco":"894","cep":"15.651-891","descricao":"Bairro ao norte da cidade","id":2}',
                'url' => 'http://localhost/nucleos?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-26 15:26:39',
                'updated_at' => '2018-12-26 15:26:39',
            ),
            5 => 
            array (
                'id' => 6,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Nucleo',
                'auditable_id' => 3,
                'old_values' => '[]',
                'new_values' => '{"cidade":"S\\u00e3o Leopoldo","inativo":"1","nome":"N\\u00facleo Oeste","bairro":"Bairro dos papeis","rua":"Rua dos Macacos","numero_endereco":"451","cep":"50.560-564","descricao":"Bairro ao oeste da cidade","id":3}',
                'url' => 'http://localhost/nucleos?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-26 15:27:23',
                'updated_at' => '2018-12-26 15:27:23',
            ),
            6 => 
            array (
                'id' => 7,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Nucleo',
                'auditable_id' => 4,
                'old_values' => '[]',
                'new_values' => '{"cidade":"S\\u00e3o Leopoldo","inativo":"1","nome":"N\\u00facleo Sul","bairro":"Bairro das canetas","rua":"Rua das on\\u00e7as","numero_endereco":"516","cep":"15.061-888","descricao":"Bairro ao sul da cidade","id":4}',
                'url' => 'http://localhost/nucleos?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-26 15:28:13',
                'updated_at' => '2018-12-26 15:28:13',
            ),
            7 => 
            array (
                'id' => 8,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Turma',
                'auditable_id' => 1,
                'old_values' => '[]',
                'new_values' => '{"nome":"Turma de Basquete A1","inativo":"1","limite":"10","horario_inicial":"12:00:00","horario_final":"14:00:00","data_semanal":"Segunda,Sexta,","nucleo_id":"2","descricao":"Turma de Basquete do norte","id":1}',
                'url' => 'http://localhost/turmas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-26 15:31:20',
                'updated_at' => '2018-12-26 15:31:20',
            ),
            8 => 
            array (
                'id' => 9,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Turma',
                'auditable_id' => 2,
                'old_values' => '[]',
                'new_values' => '{"nome":"Turma de Futebol A1","inativo":"1","limite":"8","horario_inicial":"12:00:00","horario_final":"14:00:00","data_semanal":"Ter\\u00e7a,Quinta,","nucleo_id":"1","descricao":null,"id":2}',
                'url' => 'http://localhost/turmas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-26 15:32:28',
                'updated_at' => '2018-12-26 15:32:28',
            ),
            9 => 
            array (
                'id' => 10,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Turma',
                'auditable_id' => 3,
                'old_values' => '[]',
                'new_values' => '{"nome":"Turma de Ginastica A1","inativo":"1","limite":"15","horario_inicial":"12:00:00","horario_final":"14:00:00","data_semanal":"Domingo,Sabado,","nucleo_id":"3","descricao":null,"id":3}',
                'url' => 'http://localhost/turmas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-26 15:33:24',
                'updated_at' => '2018-12-26 15:33:24',
            ),
            10 => 
            array (
                'id' => 11,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Turma',
                'auditable_id' => 4,
                'old_values' => '[]',
                'new_values' => '{"nome":"Turma de Basquete A2","inativo":"1","limite":"10","horario_inicial":"15:00:00","horario_final":"18:00:00","data_semanal":"Segunda,Quinta,","nucleo_id":"4","descricao":null,"id":4}',
                'url' => 'http://localhost/turmas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-26 15:35:39',
                'updated_at' => '2018-12-26 15:35:39',
            ),
            11 => 
            array (
                'id' => 12,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Turma',
                'auditable_id' => 5,
                'old_values' => '[]',
                'new_values' => '{"nome":"Turma de Futebol A2","inativo":"1","limite":"8","horario_inicial":"15:00:00","horario_final":"18:00:00","data_semanal":"Domingo,Sabado,","nucleo_id":"1","descricao":null,"id":5}',
                'url' => 'http://localhost/turmas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-26 15:36:31',
                'updated_at' => '2018-12-26 15:36:31',
            ),
            12 => 
            array (
                'id' => 13,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Turma',
                'auditable_id' => 6,
                'old_values' => '[]',
                'new_values' => '{"nome":"Turma de Ginastica A2","inativo":"1","limite":"15","horario_inicial":"15:00:00","horario_final":"18:00:00","data_semanal":"Segunda,Sexta,","nucleo_id":"4","descricao":null,"id":6}',
                'url' => 'http://localhost/turmas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-26 15:37:13',
                'updated_at' => '2018-12-26 15:37:13',
            ),
            13 => 
            array (
                'id' => 14,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Doenca',
                'auditable_id' => 1,
                'old_values' => '[]',
                'new_values' => '{"nome":"Acne","descricao":"Sens\\u00edvel ao sol.","id":1}',
                'url' => 'http://localhost/doencas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-26 15:38:19',
                'updated_at' => '2018-12-26 15:38:19',
            ),
            14 => 
            array (
                'id' => 15,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Doenca',
                'auditable_id' => 2,
                'old_values' => '[]',
                'new_values' => '{"nome":"Gripe","descricao":"Contagiante, problemas respirat\\u00f3rios","id":2}',
                'url' => 'http://localhost/doencas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-26 15:38:45',
                'updated_at' => '2018-12-26 15:38:45',
            ),
            15 => 
            array (
                'id' => 16,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Doenca',
                'auditable_id' => 3,
                'old_values' => '[]',
                'new_values' => '{"nome":"Tosse","descricao":"Problemas respirat\\u00f3rios, dor de garganta","id":3}',
                'url' => 'http://localhost/doencas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-26 15:39:06',
                'updated_at' => '2018-12-26 15:39:06',
            ),
            16 => 
            array (
                'id' => 17,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Doenca',
                'auditable_id' => 4,
                'old_values' => '[]',
                'new_values' => '{"nome":"Press\\u00e3o alta","descricao":"Desmaios, Necessidade de descano","id":4}',
                'url' => 'http://localhost/doencas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-26 15:39:57',
                'updated_at' => '2018-12-26 15:39:57',
            ),
            17 => 
            array (
                'id' => 18,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'updated',
                'auditable_type' => 'App\\Doenca',
                'auditable_id' => 4,
                'old_values' => '{"descricao":"Desmaios, Necessidade de descano"}',
                'new_values' => '{"descricao":"Desmaios, Necessidade de descanso"}',
                'url' => 'http://localhost/doencas/4?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-26 15:40:11',
                'updated_at' => '2018-12-26 15:40:11',
            ),
            18 => 
            array (
                'id' => 19,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'updated',
                'auditable_type' => 'App\\Doenca',
                'auditable_id' => 2,
                'old_values' => '{"descricao":"Contagiante, problemas respirat\\u00f3rios"}',
                'new_values' => '{"descricao":"Contagiante, problemas respirat\\u00f3rios."}',
                'url' => 'http://localhost/doencas/2?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-26 15:40:15',
                'updated_at' => '2018-12-26 15:40:15',
            ),
            19 => 
            array (
                'id' => 20,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'updated',
                'auditable_type' => 'App\\Doenca',
                'auditable_id' => 4,
                'old_values' => '{"descricao":"Desmaios, Necessidade de descanso"}',
                'new_values' => '{"descricao":"Desmaios, Necessidade de descanso."}',
                'url' => 'http://localhost/doencas/4?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-26 15:40:18',
                'updated_at' => '2018-12-26 15:40:18',
            ),
            20 => 
            array (
                'id' => 21,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'updated',
                'auditable_type' => 'App\\Doenca',
                'auditable_id' => 3,
                'old_values' => '{"descricao":"Problemas respirat\\u00f3rios, dor de garganta"}',
                'new_values' => '{"descricao":"Problemas respirat\\u00f3rios, dor de garganta."}',
                'url' => 'http://localhost/doencas/3?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-26 15:40:21',
                'updated_at' => '2018-12-26 15:40:21',
            ),
            21 => 
            array (
                'id' => 22,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'deleted',
                'auditable_type' => 'App\\Doenca',
                'auditable_id' => 4,
                'old_values' => '{"id":4,"nome":"Press\\u00e3o alta","descricao":"Desmaios, Necessidade de descanso."}',
                'new_values' => '[]',
                'url' => 'http://localhost/doencas/delete?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-26 15:42:01',
                'updated_at' => '2018-12-26 15:42:01',
            ),
            22 => 
            array (
                'id' => 23,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\User',
                'auditable_id' => 2,
                'old_values' => '[]',
                'new_values' => '{"name":"yuri","email":"yuri@yuri.com","password":"$2y$10$vvnoZWd7ykMK6nVtAY.bVOpcmfttXEj\\/Pu2ofbdew7iJngk1MjmUa","admin_professor":0,"id":2}',
                'url' => 'http://localhost/professor?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-26 15:45:38',
                'updated_at' => '2018-12-26 15:45:38',
            ),
            23 => 
            array (
                'id' => 24,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Professor',
                'auditable_id' => 1,
                'old_values' => '[]',
            'new_values' => '{"nome":"Yuri","matricula":"14551565","nascimento":"1989-03-08","bairro":"Bairro dos arm\\u00e1rios","rua":"Rua das Panteras","numero_endereco":"251","cep":"56.561-810","telefone":"(51) 1650-1651","cpf":"560.859.601-51","rg":"51601809","curso":"Curso em Futebol","formacao":"Forma\\u00e7\\u00e3o em educa\\u00e7\\u00e3o f\\u00edsica","cidade":"S\\u00e3o Leopoldo","user_id":2,"id":1}',
                'url' => 'http://localhost/professor?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-26 15:45:38',
                'updated_at' => '2018-12-26 15:45:38',
            ),
            24 => 
            array (
                'id' => 25,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\User',
                'auditable_id' => 3,
                'old_values' => '[]',
                'new_values' => '{"name":"oscar","email":"oscar@oscar.com","password":"$2y$10$\\/3etdWvPryUp0HLW7iWbY.JzfTmT2lUYqS6NZvMFcb0QVnD2f4ikm","admin_professor":0,"id":3}',
                'url' => 'http://localhost/professor?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-26 15:47:39',
                'updated_at' => '2018-12-26 15:47:39',
            ),
            25 => 
            array (
                'id' => 26,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Professor',
                'auditable_id' => 2,
                'old_values' => '[]',
            'new_values' => '{"nome":"Oscar","matricula":"1561851","nascimento":"1991-08-14","bairro":"Bairro das Flores","rua":"Ruas das Ar\\u00e1ras","numero_endereco":"098","cep":"15.156-515","telefone":"(18) 9480-8941","cpf":"618.908.503-27","rg":"18941561","curso":"Curso em Ginastica","formacao":"Forma\\u00e7\\u00e3o em educa\\u00e7\\u00e3o f\\u00edsica","cidade":"S\\u00e3o Leopoldo","user_id":3,"id":2}',
                'url' => 'http://localhost/professor?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-26 15:47:39',
                'updated_at' => '2018-12-26 15:47:39',
            ),
            26 => 
            array (
                'id' => 27,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\User',
                'auditable_id' => 4,
                'old_values' => '[]',
                'new_values' => '{"name":"fernando","email":"fernando@fernando.com","password":"$2y$10$Ccqhy\\/KQWaPsefO3L9kxhOkBJDrLG5NWDM.Xv\\/gCTDSMkdZTx6YHG","admin_professor":0,"id":4}',
                'url' => 'http://localhost/professor?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-26 15:50:06',
                'updated_at' => '2018-12-26 15:50:06',
            ),
            27 => 
            array (
                'id' => 28,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Professor',
                'auditable_id' => 3,
                'old_values' => '[]',
            'new_values' => '{"nome":"Fernando","matricula":"1864651","nascimento":"1983-11-16","bairro":"Bairro das Comidas","rua":"Rua dos Cachorros","numero_endereco":"262","cep":"56.165-051","telefone":"(16) 5108-5749","cpf":"864.018.412-62","rg":"15616581","curso":"Curso em Basquete","formacao":"Forma\\u00e7\\u00e3o em educa\\u00e7\\u00e3o f\\u00edsica","cidade":"S\\u00e3o Leopoldo","user_id":4,"id":3}',
                'url' => 'http://localhost/professor?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-26 15:50:06',
                'updated_at' => '2018-12-26 15:50:06',
            ),
            28 => 
            array (
                'id' => 29,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'updated',
                'auditable_type' => 'App\\Pessoa',
                'auditable_id' => 1,
                'old_values' => '{"nascimento":"1994-04-07 00:00:00","rua":"Ruas das Ar\\u00e1ras"}',
                'new_values' => '{"nascimento":"1994-04-07","rua":"Rua das Ar\\u00e1ras"}',
                'url' => 'http://localhost/pessoas/1?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-26 15:50:53',
                'updated_at' => '2018-12-26 15:50:53',
            ),
            29 => 
            array (
                'id' => 30,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\User',
                'auditable_id' => 5,
                'old_values' => '[]',
                'new_values' => '{"name":"mario","email":"mario@mario.com","password":"$2y$10$Jtas9u7Oh1fHZbCmIRxD3u5aj.wv6vlmnAn1jY3B8RUEEAQIJ4EJu","admin_professor":0,"id":5}',
                'url' => 'http://localhost/professor?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-26 15:54:40',
                'updated_at' => '2018-12-26 15:54:40',
            ),
            30 => 
            array (
                'id' => 31,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Professor',
                'auditable_id' => 4,
                'old_values' => '[]',
            'new_values' => '{"nome":"Mario","matricula":"2165150","nascimento":"1981-02-04","bairro":"Bairro das Comidas","rua":"Rua das Gaivotas","numero_endereco":"518","cep":"15.156-112","telefone":"(18) 9618-0665","cpf":"486.100.894-51","rg":"4896012","curso":"Curso de Basquete","formacao":"Forma\\u00e7\\u00e3o em educa\\u00e7\\u00e3o f\\u00edsica","cidade":"S\\u00e3o Leopoldo","user_id":5,"id":4}',
                'url' => 'http://localhost/professor?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-26 15:54:40',
                'updated_at' => '2018-12-26 15:54:40',
            ),
            31 => 
            array (
                'id' => 32,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Doenca',
                'auditable_id' => 5,
                'old_values' => '[]',
                'new_values' => '{"nome":"Alergia de Pele","descricao":"Sens\\u00edvel ao sol, problemas de alergia","id":5}',
                'url' => 'http://localhost/doencas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-26 15:57:31',
                'updated_at' => '2018-12-26 15:57:31',
            ),
            32 => 
            array (
                'id' => 33,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Doenca',
                'auditable_id' => 6,
                'old_values' => '[]',
                'new_values' => '{"nome":"Ins\\u00f4nia","descricao":"Cansa\\u00e7o, problemas de resist\\u00eancia, fadiga.","id":6}',
                'url' => 'http://localhost/doencas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-26 15:58:15',
                'updated_at' => '2018-12-26 15:58:15',
            ),
            33 => 
            array (
                'id' => 34,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'updated',
                'auditable_type' => 'App\\Doenca',
                'auditable_id' => 5,
                'old_values' => '{"descricao":"Sens\\u00edvel ao sol, problemas de alergia"}',
                'new_values' => '{"descricao":"Sens\\u00edvel ao sol, problemas de alergia."}',
                'url' => 'http://localhost/doencas/5?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-26 15:58:19',
                'updated_at' => '2018-12-26 15:58:19',
            ),
            34 => 
            array (
                'id' => 35,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'updated',
                'auditable_type' => 'App\\Turma',
                'auditable_id' => 1,
                'old_values' => '{"descricao":"Turma de Basquete do norte","nucleo_id":2}',
            'new_values' => '{"descricao":"<script>alert(\'teste\');<\\/script>","nucleo_id":"1"}',
                'url' => 'http://localhost/turmas/1?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-27 09:54:59',
                'updated_at' => '2018-12-27 09:54:59',
            ),
            35 => 
            array (
                'id' => 36,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'updated',
                'auditable_type' => 'App\\Turma',
                'auditable_id' => 1,
            'old_values' => '{"descricao":"<script>alert(\'teste\');<\\/script>"}',
                'new_values' => '{"descricao":null}',
                'url' => 'http://localhost/turmas/1?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-27 10:00:38',
                'updated_at' => '2018-12-27 10:00:38',
            ),
            36 => 
            array (
                'id' => 37,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'updated',
                'auditable_type' => 'App\\Pessoa',
                'auditable_id' => 1,
                'old_values' => '{"foto":"img\\/img_3x4\\/imagem_3888.png","nascimento":"1994-04-07 00:00:00"}',
                'new_values' => '{"foto":"img\\/img_3x4\\/imagem_8881.bin","nascimento":"1994-04-07"}',
                'url' => 'http://localhost/pessoas/1?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-27 10:07:25',
                'updated_at' => '2018-12-27 10:07:25',
            ),
            37 => 
            array (
                'id' => 38,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'updated',
                'auditable_type' => 'App\\Pessoa',
                'auditable_id' => 1,
                'old_values' => '{"nascimento":"1994-04-07 00:00:00","estado":1}',
                'new_values' => '{"nascimento":"1994-04-07","estado":0}',
                'url' => 'http://localhost/pessoas/1?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-27 10:20:41',
                'updated_at' => '2018-12-27 10:20:41',
            ),
            38 => 
            array (
                'id' => 39,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'updated',
                'auditable_type' => 'App\\Pessoa',
                'auditable_id' => 1,
                'old_values' => '{"foto":null,"nascimento":"1994-04-07 00:00:00","estado":0}',
                'new_values' => '{"foto":"img\\/img_3x4\\/imagem_3788.png","nascimento":"1994-04-07","estado":1}',
                'url' => 'http://localhost/pessoas/1?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-27 11:15:13',
                'updated_at' => '2018-12-27 11:15:13',
            ),
            39 => 
            array (
                'id' => 40,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'updated',
                'auditable_type' => 'App\\Pessoa',
                'auditable_id' => 1,
                'old_values' => '{"nascimento":"1994-04-07 00:00:00","cidade":"S\\u00e3o Leopoldo","estado_civil":"Solteiro"}',
                'new_values' => '{"nascimento":"1994-04-07","cidade":"teste","estado_civil":"Casado"}',
                'url' => 'http://localhost/pessoas/1?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Mobile Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-27 11:22:20',
                'updated_at' => '2018-12-27 11:22:20',
            ),
            40 => 
            array (
                'id' => 41,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Pessoa',
                'auditable_id' => 2,
                'old_values' => '[]',
            'new_values' => '{"foto":"img\\/img_3x4\\/imagem_9587.png","nome":"Jo\\u00e3o Barros","nascimento":"2005-09-14","sexo":"M","rg":"15320510","cpf":"156.601.656-20","cpf_responsavel":"056.056.420-56","cidade":"S\\u00e3o Leopoldo","rua":"Rua das Panteras","bairro":"Bairro dos arm\\u00e1rios","numero_endereco":"480","cep":"54.006-486","telefone":"(51) 1561-5618","telefone_emergencia":"(51) 5156-1566","estado_civil":"Solteiro","nome_do_pai":"Julio Barros","nome_da_mae":"Julia Barros","pessoa_emergencia":"Jorge Reis (amigo)","filhos":"0","convenio_medico":"UN","mora_com_os_pais":"1","matricula":"img\\/img_matricula\\/imagem_4003.png","estado":1,"id":2}',
                'url' => 'http://localhost/pessoas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-27 12:09:30',
                'updated_at' => '2018-12-27 12:09:30',
            ),
            41 => 
            array (
                'id' => 42,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Anamnese',
                'auditable_id' => 2,
                'old_values' => '[]',
                'new_values' => '{"possui_doenca":1,"toma_medicacao":"1","alergia_medicacao":"1","peso":"60","altura":"1.65","fumante":"2","cirurgia":"1","dor_muscular":"2","dor_articular":"2","dor_ossea":"2","atestado":"2","observacao":"Possui \\u00f3culos","id":2}',
                'url' => 'http://localhost/pessoas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-27 12:09:30',
                'updated_at' => '2018-12-27 12:09:30',
            ),
            42 => 
            array (
                'id' => 43,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Pessoa',
                'auditable_id' => 3,
                'old_values' => '[]',
            'new_values' => '{"foto":"img\\/img_3x4\\/imagem_7782.png","nome":"Jo\\u00e3o Barros","nascimento":"2005-09-14","sexo":"M","rg":"15320510","cpf":"156.601.656-20","cpf_responsavel":"056.056.420-56","cidade":"S\\u00e3o Leopoldo","rua":"Rua das Panteras","bairro":"Bairro dos arm\\u00e1rios","numero_endereco":"480","cep":"54.006-486","telefone":"(51) 1561-5618","telefone_emergencia":"(51) 5156-1566","estado_civil":"Solteiro","nome_do_pai":"Julio Barros","nome_da_mae":"Julia Barros","pessoa_emergencia":"Jorge Reis (amigo)","filhos":"0","convenio_medico":"UN","mora_com_os_pais":"1","matricula":"img\\/img_matricula\\/imagem_5171.png","estado":1,"id":3}',
                'url' => 'http://localhost/pessoas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-27 12:16:50',
                'updated_at' => '2018-12-27 12:16:50',
            ),
            43 => 
            array (
                'id' => 44,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Anamnese',
                'auditable_id' => 3,
                'old_values' => '[]',
                'new_values' => '{"possui_doenca":1,"toma_medicacao":"1","alergia_medicacao":"1","peso":"60","altura":"1.65","fumante":"2","cirurgia":"1","dor_muscular":"2","dor_articular":"2","dor_ossea":"2","atestado":"2","observacao":"Possui \\u00f3culos","ano":"2018","pessoas_id":3,"id":3}',
                'url' => 'http://localhost/pessoas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-27 12:16:50',
                'updated_at' => '2018-12-27 12:16:50',
            ),
            44 => 
            array (
                'id' => 45,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Pessoa',
                'auditable_id' => 4,
                'old_values' => '[]',
            'new_values' => '{"foto":"img\\/img_3x4\\/imagem_4996.png","nome":"Grabriel de Souza","nascimento":"1992-02-05","sexo":"M","rg":"48778984","cpf":"894.465.458-98","cpf_responsavel":null,"cidade":"S\\u00e3o Leopoldo","rua":"Rua das Zebras","bairro":"Bairro das Canetas","numero_endereco":"611","cep":"48.898-798","telefone":"(51) 5894-8189","telefone_emergencia":"(51) 5954-9875","estado_civil":"Solteiro","nome_do_pai":"Valdir de Souza","nome_da_mae":"Gabriela de Souza","pessoa_emergencia":"Felipe de Souza (Tio)","filhos":"0","convenio_medico":"UN","mora_com_os_pais":"2","matricula":null,"estado":1,"id":4}',
                'url' => 'http://localhost/pessoas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-27 12:24:05',
                'updated_at' => '2018-12-27 12:24:05',
            ),
            45 => 
            array (
                'id' => 46,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Anamnese',
                'auditable_id' => 4,
                'old_values' => '[]',
                'new_values' => '{"possui_doenca":1,"toma_medicacao":"2","alergia_medicacao":"2","peso":"71","altura":"1.69","fumante":"1","cirurgia":"1","dor_muscular":"1","dor_articular":"2","dor_ossea":"2","atestado":"2","observacao":null,"ano":"2018","pessoas_id":4,"id":4}',
                'url' => 'http://localhost/pessoas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-27 12:24:05',
                'updated_at' => '2018-12-27 12:24:05',
            ),
            46 => 
            array (
                'id' => 47,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Pessoa',
                'auditable_id' => 5,
                'old_values' => '[]',
            'new_values' => '{"foto":"img\\/img_3x4\\/imagem_3543.png","nome":"Felipe Soares","nascimento":"1990-02-23","sexo":"M","rg":"88745868","cpf":"797.141.005-55","cpf_responsavel":null,"cidade":"S\\u00e3o Leopoldo","rua":"Rua das Pombas","bairro":"Bairro das Flores","numero_endereco":"489","cep":"11.651-561","telefone":"(51) 5151-5655","telefone_emergencia":"(51) 5151-5151","estado_civil":"Casado","nome_do_pai":"Fernando Soares","nome_da_mae":"Fernando Soares","pessoa_emergencia":"Julio Emanuel (Vizinho)","filhos":"0","convenio_medico":"SEN","mora_com_os_pais":"2","matricula":null,"estado":1,"id":5}',
                'url' => 'http://localhost/pessoas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-27 12:30:18',
                'updated_at' => '2018-12-27 12:30:18',
            ),
            47 => 
            array (
                'id' => 48,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Anamnese',
                'auditable_id' => 5,
                'old_values' => '[]',
                'new_values' => '{"atestado":"2","peso":"58.1","altura":null,"toma_medicacao":"2","alergia_medicacao":"2","fumante":"1","cirurgia":"2","dor_ossea":"2","dor_muscular":"2","dor_articular":"2","possui_doenca":"2","observacao":null,"id":5}',
                'url' => 'http://localhost/pessoas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-27 12:30:18',
                'updated_at' => '2018-12-27 12:30:18',
            ),
            48 => 
            array (
                'id' => 49,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Pessoa',
                'auditable_id' => 6,
                'old_values' => '[]',
            'new_values' => '{"foto":"img\\/img_3x4\\/imagem_3339.png","nome":"Felipe Soares","nascimento":"1990-02-23","sexo":"M","rg":"88745868","cpf":"797.141.005-55","cpf_responsavel":null,"cidade":"S\\u00e3o Leopoldo","rua":"Rua das Pombas","bairro":"Bairro das Flores","numero_endereco":"489","cep":"11.651-561","telefone":"(51) 5151-5655","telefone_emergencia":"(51) 5151-5151","estado_civil":"Casado","nome_do_pai":"Fernando Soares","nome_da_mae":"Fernando Soares","pessoa_emergencia":"Julio Emanuel (Vizinho)","filhos":"0","convenio_medico":"SEN","mora_com_os_pais":"2","matricula":null,"estado":1,"id":6}',
                'url' => 'http://localhost/pessoas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-27 12:33:37',
                'updated_at' => '2018-12-27 12:33:37',
            ),
            49 => 
            array (
                'id' => 50,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Anamnese',
                'auditable_id' => 6,
                'old_values' => '[]',
                'new_values' => '{"atestado":"2","peso":"58.1","altura":null,"toma_medicacao":"2","alergia_medicacao":"2","fumante":"1","cirurgia":"2","dor_ossea":"2","dor_muscular":"2","dor_articular":"2","possui_doenca":"2","observacao":null,"id":6}',
                'url' => 'http://localhost/pessoas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-27 12:33:37',
                'updated_at' => '2018-12-27 12:33:37',
            ),
            50 => 
            array (
                'id' => 51,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Pessoa',
                'auditable_id' => 7,
                'old_values' => '[]',
            'new_values' => '{"foto":"img\\/img_3x4\\/imagem_6601.png","nome":"Felipe Soares","nascimento":"1990-02-23","sexo":"M","rg":"88745868","cpf":"797.141.005-55","cpf_responsavel":null,"cidade":"S\\u00e3o Leopoldo","rua":"Rua das Pombas","bairro":"Bairro das Flores","numero_endereco":"489","cep":"11.651-561","telefone":"(51) 5151-5655","telefone_emergencia":"(51) 5151-5151","estado_civil":"Casado","nome_do_pai":"Fernando Soares","nome_da_mae":"Fernando Soares","pessoa_emergencia":"Julio Emanuel (Vizinho)","filhos":"0","convenio_medico":"SEN","mora_com_os_pais":"2","matricula":null,"estado":1,"id":7}',
                'url' => 'http://localhost/pessoas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-27 12:37:49',
                'updated_at' => '2018-12-27 12:37:49',
            ),
            51 => 
            array (
                'id' => 52,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Anamnese',
                'auditable_id' => 7,
                'old_values' => '[]',
                'new_values' => '{"possui_doenca":"2","toma_medicacao":"2","alergia_medicacao":"2","peso":"58.1","altura":null,"fumante":"1","cirurgia":"2","dor_muscular":"2","dor_articular":"2","dor_ossea":"2","atestado":"2","observacao":null,"ano":"2018","pessoas_id":7,"id":7}',
                'url' => 'http://localhost/pessoas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-27 12:37:49',
                'updated_at' => '2018-12-27 12:37:49',
            ),
            52 => 
            array (
                'id' => 53,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Pessoa',
                'auditable_id' => 8,
                'old_values' => '[]',
            'new_values' => '{"foto":"img\\/img_3x4\\/imagem_2462.png","nome":"Diego Francisco","nascimento":"1998-01-13","sexo":"M","rg":"13212322","cpf":"456.445.656-45","cpf_responsavel":null,"cidade":"S\\u00e3o Leopoldo","rua":"Rua dos Lobos","bairro":"Bairro das Comidas","numero_endereco":"458","cep":"15.213-300","telefone":"(51) 6548-9845","telefone_emergencia":"(51) 0000-0000","estado_civil":"Casado","nome_do_pai":"Daniel Francisco","nome_da_mae":"Fatima Francisco","pessoa_emergencia":"Matheus Borrano (Amigo)","filhos":"0","convenio_medico":"ON","mora_com_os_pais":"2","matricula":null,"estado":1,"id":8}',
                'url' => 'http://localhost/pessoas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-27 12:55:48',
                'updated_at' => '2018-12-27 12:55:48',
            ),
            53 => 
            array (
                'id' => 54,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Anamnese',
                'auditable_id' => 8,
                'old_values' => '[]',
                'new_values' => '{"possui_doenca":1,"toma_medicacao":"2","alergia_medicacao":"2","peso":"90","altura":"1.68","fumante":"2","cirurgia":"1","dor_muscular":"2","dor_articular":"1","dor_ossea":"1","atestado":"2","observacao":"Cansa\\u00e7o f\\u00edsico depois de meia hora","ano":"2018","pessoas_id":8,"id":8}',
                'url' => 'http://localhost/pessoas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-27 12:55:48',
                'updated_at' => '2018-12-27 12:55:48',
            ),
            54 => 
            array (
                'id' => 55,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Pessoa',
                'auditable_id' => 9,
                'old_values' => '[]',
            'new_values' => '{"foto":"img\\/img_3x4\\/imagem_8506.png","nome":"Rogeria Duarte","nascimento":"1989-04-03","sexo":"F","rg":"95175385","cpf":"789.789.789-78","cpf_responsavel":null,"cidade":"S\\u00e3o Leopoldo","rua":"Rua dos Peixes","bairro":"Bairro das Canetas","numero_endereco":"875","cep":"45.645-651","telefone":"(51) 5156-5798","telefone_emergencia":"(51) 9872-0489","estado_civil":"Casado","nome_do_pai":"Rau Duarte","nome_da_mae":"Riana Duarte","pessoa_emergencia":"Ritta Duarte (V\\u00f3)","filhos":"2","convenio_medico":"SEM","mora_com_os_pais":"2","matricula":null,"estado":1,"id":9}',
                'url' => 'http://localhost/pessoas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-27 13:00:18',
                'updated_at' => '2018-12-27 13:00:18',
            ),
            55 => 
            array (
                'id' => 56,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Anamnese',
                'auditable_id' => 9,
                'old_values' => '[]',
                'new_values' => '{"possui_doenca":1,"toma_medicacao":"1","alergia_medicacao":"2","peso":"76.82","altura":"1.65","fumante":"2","cirurgia":"2","dor_muscular":"2","dor_articular":"1","dor_ossea":"2","atestado":"2","observacao":"Problemas na Perna","ano":"2018","pessoas_id":9,"id":9}',
                'url' => 'http://localhost/pessoas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-27 13:00:19',
                'updated_at' => '2018-12-27 13:00:19',
            ),
            56 => 
            array (
                'id' => 57,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Pessoa',
                'auditable_id' => 10,
                'old_values' => '[]',
            'new_values' => '{"foto":"img\\/img_3x4\\/imagem_9305.png","nome":"Diana Tavares","nascimento":"1985-08-14","sexo":"F","rg":"78899512","cpf":"789.789.140-49","cpf_responsavel":null,"cidade":"S\\u00e3o Leopoldo","rua":"Rua das Gaivotas","bairro":"Bairro das Comidas","numero_endereco":"987","cep":"46.498-721","telefone":"(51) 5615-6110","telefone_emergencia":"(51) 2005-6095","estado_civil":"Solteiro","nome_do_pai":"Carlos Tavares","nome_da_mae":"Vanessa Tavares","pessoa_emergencia":"Miguel Enrique","filhos":"0","convenio_medico":"GO","mora_com_os_pais":"2","matricula":null,"estado":1,"id":10}',
                'url' => 'http://localhost/pessoas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-27 13:11:41',
                'updated_at' => '2018-12-27 13:11:41',
            ),
            57 => 
            array (
                'id' => 58,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Anamnese',
                'auditable_id' => 10,
                'old_values' => '[]',
                'new_values' => '{"possui_doenca":"2","toma_medicacao":"1","alergia_medicacao":"1","peso":"86","altura":"1.57","fumante":"2","cirurgia":"1","dor_muscular":"2","dor_articular":"2","dor_ossea":"2","atestado":"2","observacao":"Acima do peso","ano":"2018","pessoas_id":10,"id":10}',
                'url' => 'http://localhost/pessoas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-27 13:11:41',
                'updated_at' => '2018-12-27 13:11:41',
            ),
            58 => 
            array (
                'id' => 59,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Pessoa',
                'auditable_id' => 11,
                'old_values' => '[]',
            'new_values' => '{"foto":"img\\/img_3x4\\/imagem_9223.png","nome":"Diana Tavares","nascimento":"1985-08-14","sexo":"F","rg":"78899512","cpf":"120.123.789-54","cpf_responsavel":null,"cidade":"S\\u00e3o Leopoldo","rua":"Rua das Gaivotas","bairro":"Bairro das Comidas","numero_endereco":"987","cep":"46.498-721","telefone":"(51) 5615-6110","telefone_emergencia":"(51) 2005-6095","estado_civil":"Solteiro","nome_do_pai":"Carlos Tavares","nome_da_mae":"Vanessa Tavares","pessoa_emergencia":"Miguel Enrique","filhos":"0","convenio_medico":"GO","mora_com_os_pais":"2","matricula":null,"estado":1,"id":11}',
                'url' => 'http://localhost/pessoas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-27 13:11:57',
                'updated_at' => '2018-12-27 13:11:57',
            ),
            59 => 
            array (
                'id' => 60,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Anamnese',
                'auditable_id' => 11,
                'old_values' => '[]',
                'new_values' => '{"possui_doenca":"2","toma_medicacao":"1","alergia_medicacao":"1","peso":"86","altura":"1.57","fumante":"2","cirurgia":"1","dor_muscular":"2","dor_articular":"2","dor_ossea":"2","atestado":"2","observacao":"Acima do peso","ano":"2018","pessoas_id":11,"id":11}',
                'url' => 'http://localhost/pessoas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-27 13:11:58',
                'updated_at' => '2018-12-27 13:11:58',
            ),
            60 => 
            array (
                'id' => 61,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Pessoa',
                'auditable_id' => 12,
                'old_values' => '[]',
            'new_values' => '{"foto":"img\\/img_3x4\\/imagem_5077.png","nome":"Amanda Teixeira","nascimento":"2005-07-27","sexo":"F","rg":"156108089","cpf":"408.948.905-98","cpf_responsavel":"401.489.487-65","cidade":"S\\u00e3o Leopoldo","rua":"Rua dos P\\u00e1ssaros","bairro":"Bairro das Flores","numero_endereco":"446","cep":"56.789-871","telefone":"(51) 5616-8487","telefone_emergencia":"(51) 6878-9732","estado_civil":"Solteiro","nome_do_pai":"Diego Teixeira","nome_da_mae":"Carol Teixeira","pessoa_emergencia":"Luciana Teixeira (Tia)","filhos":"0","convenio_medico":"SEN","mora_com_os_pais":"1","matricula":"img\\/img_matricula\\/imagem_3751.png","estado":1,"id":12}',
                'url' => 'http://localhost/pessoas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-27 13:18:02',
                'updated_at' => '2018-12-27 13:18:02',
            ),
            61 => 
            array (
                'id' => 62,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Anamnese',
                'auditable_id' => 12,
                'old_values' => '[]',
                'new_values' => '{"possui_doenca":1,"toma_medicacao":"2","alergia_medicacao":"2","peso":"50.9","altura":"1.58","fumante":"2","cirurgia":"2","dor_muscular":"2","dor_articular":"2","dor_ossea":"2","atestado":"2","observacao":"N\\u00e3o pode ficar exposta ao sol","ano":"2018","pessoas_id":12,"id":12}',
                'url' => 'http://localhost/pessoas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-27 13:18:02',
                'updated_at' => '2018-12-27 13:18:02',
            ),
            62 => 
            array (
                'id' => 63,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Pessoa',
                'auditable_id' => 13,
                'old_values' => '[]',
            'new_values' => '{"foto":"img\\/img_3x4\\/imagem_3304.png","nome":"Rita dos Santos","nascimento":"1974-06-13","sexo":"F","rg":"87542115","cpf":"080.808.880-88","cpf_responsavel":null,"cidade":"S\\u00e3o Leopoldo","rua":"Rua dos Celulares","bairro":"Bairro das Tomadas","numero_endereco":"821","cep":"79.510-326","telefone":"(51) 5100-5657","telefone_emergencia":"(51) 5615-0897","estado_civil":"Casado","nome_do_pai":null,"nome_da_mae":"Maria dos Santos","pessoa_emergencia":"Marta regina (Amiga)","filhos":"0","convenio_medico":"UN","mora_com_os_pais":"2","matricula":null,"estado":1,"id":13}',
                'url' => 'http://localhost/pessoas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-27 13:22:43',
                'updated_at' => '2018-12-27 13:22:43',
            ),
            63 => 
            array (
                'id' => 64,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Anamnese',
                'auditable_id' => 13,
                'old_values' => '[]',
                'new_values' => '{"possui_doenca":"2","toma_medicacao":"1","alergia_medicacao":"2","peso":"79.56","altura":"1.56","fumante":"2","cirurgia":"1","dor_muscular":"2","dor_articular":"1","dor_ossea":"1","atestado":"2","observacao":"F\\u00edsico Deteriorado","ano":"2018","pessoas_id":13,"id":13}',
                'url' => 'http://localhost/pessoas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-27 13:22:43',
                'updated_at' => '2018-12-27 13:22:43',
            ),
            64 => 
            array (
                'id' => 65,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Pessoa',
                'auditable_id' => 14,
                'old_values' => '[]',
            'new_values' => '{"foto":"img\\/img_3x4\\/imagem_6478.png","nome":"Reginaldo Mendes","nascimento":"1975-10-29","sexo":"M","rg":"15605657","cpf":"489.409.005-68","cpf_responsavel":null,"cidade":"S\\u00e3o Leopoldo","rua":"Rua dos Ratos","bairro":"Bairro das Pra\\u00e7a","numero_endereco":"156","cep":"56.888-815","telefone":"(51) 5615-6688","telefone_emergencia":"(51) 5684-0540","estado_civil":"Casado","nome_do_pai":"Reinaldo Mendes","nome_da_mae":"Amanda Mendes","pessoa_emergencia":"Fatima Bonai (Amiga)","filhos":"0","convenio_medico":null,"mora_com_os_pais":"2","matricula":null,"estado":0,"id":14}',
                'url' => 'http://localhost/pessoas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-27 13:28:58',
                'updated_at' => '2018-12-27 13:28:58',
            ),
            65 => 
            array (
                'id' => 66,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Anamnese',
                'auditable_id' => 14,
                'old_values' => '[]',
                'new_values' => '{"possui_doenca":1,"toma_medicacao":"1","alergia_medicacao":"2","peso":"95","altura":"1.72","fumante":"2","cirurgia":"2","dor_muscular":"2","dor_articular":"2","dor_ossea":"2","atestado":"2","observacao":"Idade avan\\u00e7ada","ano":"2018","pessoas_id":14,"id":14}',
                'url' => 'http://localhost/pessoas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-27 13:28:58',
                'updated_at' => '2018-12-27 13:28:58',
            ),
            66 => 
            array (
                'id' => 67,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Pessoa',
                'auditable_id' => 15,
                'old_values' => '[]',
            'new_values' => '{"foto":"img\\/img_3x4\\/imagem_1373.png","nome":"Rafaela Prata","nascimento":"1980-05-14","sexo":"F","rg":"45654665","cpf":"984.061.320-89","cpf_responsavel":null,"cidade":"S\\u00e3o Leopoldo","rua":"Rua das Aranhas","bairro":"Bairro dos arm\\u00e1rios","numero_endereco":"188","cep":"16.508-445","telefone":"(51) 5687-9206","telefone_emergencia":"(51) 0055-8453","estado_civil":"Casado","nome_do_pai":"Beto Prata","nome_da_mae":"Manuela Prata","pessoa_emergencia":"Mateus Prata (Filho)","filhos":"3","convenio_medico":"SEN","mora_com_os_pais":"2","matricula":null,"estado":1,"id":15}',
                'url' => 'http://localhost/pessoas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-27 13:34:55',
                'updated_at' => '2018-12-27 13:34:55',
            ),
            67 => 
            array (
                'id' => 68,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Anamnese',
                'auditable_id' => 15,
                'old_values' => '[]',
                'new_values' => '{"possui_doenca":"2","toma_medicacao":"1","alergia_medicacao":"1","peso":"76.12","altura":"1.59","fumante":"1","cirurgia":"2","dor_muscular":"2","dor_articular":"1","dor_ossea":"2","atestado":"2","observacao":null,"ano":"2018","pessoas_id":15,"id":15}',
                'url' => 'http://localhost/pessoas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-27 13:34:55',
                'updated_at' => '2018-12-27 13:34:55',
            ),
            68 => 
            array (
                'id' => 69,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'updated',
                'auditable_type' => 'App\\Pessoa',
                'auditable_id' => 11,
                'old_values' => '{"nascimento":"1985-08-14 00:00:00"}',
                'new_values' => '{"nascimento":"1985-08-14"}',
                'url' => 'http://localhost/pessoas/11?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-27 13:38:58',
                'updated_at' => '2018-12-27 13:38:58',
            ),
            69 => 
            array (
                'id' => 70,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'updated',
                'auditable_type' => 'App\\Nucleo',
                'auditable_id' => 1,
                'old_values' => '{"inativo":1}',
                'new_values' => '{"inativo":"2"}',
                'url' => 'http://localhost/nucleos/1?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-27 13:44:00',
                'updated_at' => '2018-12-27 13:44:00',
            ),
            70 => 
            array (
                'id' => 71,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'updated',
                'auditable_type' => 'App\\Turma',
                'auditable_id' => 1,
                'old_values' => '{"inativo":1}',
                'new_values' => '{"inativo":"2"}',
                'url' => 'http://localhost/turmas/1?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-27 13:47:22',
                'updated_at' => '2018-12-27 13:47:22',
            ),
            71 => 
            array (
                'id' => 72,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'updated',
                'auditable_type' => 'App\\Turma',
                'auditable_id' => 1,
                'old_values' => '{"inativo":2}',
                'new_values' => '{"inativo":"1"}',
                'url' => 'http://localhost/turmas/1?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-27 13:48:02',
                'updated_at' => '2018-12-27 13:48:02',
            ),
            72 => 
            array (
                'id' => 73,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'updated',
                'auditable_type' => 'App\\Turma',
                'auditable_id' => 4,
                'old_values' => '{"inativo":1,"nucleo_id":4}',
                'new_values' => '{"inativo":"2","nucleo_id":"1"}',
                'url' => 'http://localhost/turmas/4?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-27 13:48:06',
                'updated_at' => '2018-12-27 13:48:06',
            ),
            73 => 
            array (
                'id' => 74,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'updated',
                'auditable_type' => 'App\\Turma',
                'auditable_id' => 4,
                'old_values' => '{"inativo":2}',
                'new_values' => '{"inativo":"1"}',
                'url' => 'http://localhost/turmas/4?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-27 13:48:19',
                'updated_at' => '2018-12-27 13:48:19',
            ),
            74 => 
            array (
                'id' => 75,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'updated',
                'auditable_type' => 'App\\Turma',
                'auditable_id' => 4,
                'old_values' => '{"nucleo_id":1}',
                'new_values' => '{"nucleo_id":"2"}',
                'url' => 'http://localhost/turmas/4?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-27 13:48:46',
                'updated_at' => '2018-12-27 13:48:46',
            ),
            75 => 
            array (
                'id' => 76,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'updated',
                'auditable_type' => 'App\\Turma',
                'auditable_id' => 3,
                'old_values' => '{"nucleo_id":3}',
                'new_values' => '{"nucleo_id":"4"}',
                'url' => 'http://localhost/turmas/3?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-27 13:49:29',
                'updated_at' => '2018-12-27 13:49:29',
            ),
            76 => 
            array (
                'id' => 77,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'updated',
                'auditable_type' => 'App\\Turma',
                'auditable_id' => 5,
                'old_values' => '{"nucleo_id":1}',
                'new_values' => '{"nucleo_id":"2"}',
                'url' => 'http://localhost/turmas/5?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-27 13:49:52',
                'updated_at' => '2018-12-27 13:49:52',
            ),
            77 => 
            array (
                'id' => 78,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Pessoa',
                'auditable_id' => 16,
                'old_values' => '[]',
            'new_values' => '{"foto":"img\\/img_3x4\\/imagem_9612.png","nome":"teste","nascimento":"2018-12-20","sexo":"F","rg":"44848848","cpf":"487.177.878-07","cpf_responsavel":"707.878.708-78","cidade":"S\\u00e3o Leopoldo","rua":"teste","bairro":"teste","numero_endereco":"788","cep":"78.998-789","telefone":"(45) 0498-4898","telefone_emergencia":"(89) 8908-9809","estado_civil":"Casado","nome_do_pai":"teste","nome_da_mae":"teste","pessoa_emergencia":"teste","filhos":"0","convenio_medico":"teste","mora_com_os_pais":"2","matricula":"img\\/img_matricula\\/imagem_6733.png","estado":1,"id":16}',
                'url' => 'http://localhost/pessoas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-27 14:30:37',
                'updated_at' => '2018-12-27 14:30:37',
            ),
            78 => 
            array (
                'id' => 79,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Anamnese',
                'auditable_id' => 16,
                'old_values' => '[]',
                'new_values' => '{"possui_doenca":"2","toma_medicacao":"1","alergia_medicacao":"1","peso":"1","altura":"1","fumante":"1","cirurgia":"1","dor_muscular":"1","dor_articular":"1","dor_ossea":"1","atestado":"2","observacao":"fff","ano":"2018","pessoas_id":16,"id":16}',
                'url' => 'http://localhost/pessoas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-27 14:30:37',
                'updated_at' => '2018-12-27 14:30:37',
            ),
            79 => 
            array (
                'id' => 80,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Pessoa',
                'auditable_id' => 17,
                'old_values' => '[]',
            'new_values' => '{"foto":"img\\/img_3x4\\/imagem_6393.png","nome":"Maria Marielo","nascimento":"1982-11-30","sexo":"F","rg":"799974545","cpf":"797.875.211-66","cpf_responsavel":null,"cidade":"S\\u00e3o Leopoldo","rua":"Rua dos Bois","bairro":"Bairro das Canetas","numero_endereco":"495","cep":"98.712-657","telefone":"(51) 6100-0335","telefone_emergencia":"(51) 6518-0895","estado_civil":"Casado","nome_do_pai":"Mario Marielo","nome_da_mae":"Marta Marielo","pessoa_emergencia":"Fernando Marielo (V\\u00f4)","filhos":"1","convenio_medico":"FM","mora_com_os_pais":"2","matricula":null,"estado":1,"id":17}',
                'url' => 'http://localhost/pessoas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-27 14:42:14',
                'updated_at' => '2018-12-27 14:42:14',
            ),
            80 => 
            array (
                'id' => 81,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Anamnese',
                'auditable_id' => 17,
                'old_values' => '[]',
                'new_values' => '{"possui_doenca":1,"toma_medicacao":"1","alergia_medicacao":"2","peso":"86","altura":"1.62","fumante":"1","cirurgia":"1","dor_muscular":"2","dor_articular":"1","dor_ossea":"2","atestado":"2","observacao":null,"ano":"2018","pessoas_id":17,"id":17}',
                'url' => 'http://localhost/pessoas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-27 14:42:15',
                'updated_at' => '2018-12-27 14:42:15',
            ),
            81 => 
            array (
                'id' => 82,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Anamnese',
                'auditable_id' => 18,
                'old_values' => '[]',
                'new_values' => '{"pessoas_id":"12","peso":"51.05","altura":"1.58","toma_medicacao":"2","alergia_medicacao":"2","fumante":"2","cirurgia":"2","dor_ossea":"2","dor_muscular":"2","dor_articular":"2","possui_doenca":"2","observacao":null,"ano":"2018","id":18}',
                'url' => 'http://localhost/anamneses?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-27 15:29:07',
                'updated_at' => '2018-12-27 15:29:07',
            ),
            82 => 
            array (
                'id' => 83,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Anamnese',
                'auditable_id' => 19,
                'old_values' => '[]',
                'new_values' => '{"pessoas_id":"12","peso":"50.89","altura":"1.58","toma_medicacao":"1","alergia_medicacao":"2","fumante":"2","cirurgia":"2","dor_ossea":"1","dor_muscular":"2","dor_articular":"2","possui_doenca":"2","observacao":null,"ano":"2018","id":19}',
                'url' => 'http://localhost/anamneses?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-27 15:29:57',
                'updated_at' => '2018-12-27 15:29:57',
            ),
            83 => 
            array (
                'id' => 84,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Anamnese',
                'auditable_id' => 20,
                'old_values' => '[]',
                'new_values' => '{"pessoas_id":"12","peso":"50.50","altura":"1.59","toma_medicacao":"1","alergia_medicacao":"2","fumante":"2","cirurgia":"2","dor_ossea":"2","dor_muscular":"2","dor_articular":"2","possui_doenca":1,"observacao":null,"id":20}',
                'url' => 'http://localhost/anamneses?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-27 15:35:08',
                'updated_at' => '2018-12-27 15:35:08',
            ),
            84 => 
            array (
                'id' => 85,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Anamnese',
                'auditable_id' => 21,
                'old_values' => '[]',
                'new_values' => '{"pessoas_id":"12","peso":"50.50","altura":"1.59","toma_medicacao":"1","alergia_medicacao":"2","fumante":"2","cirurgia":"2","dor_ossea":"2","dor_muscular":"2","dor_articular":"2","possui_doenca":1,"observacao":null,"ano":"2018","id":21}',
                'url' => 'http://localhost/anamneses?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-27 15:36:06',
                'updated_at' => '2018-12-27 15:36:06',
            ),
            85 => 
            array (
                'id' => 86,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Anamnese',
                'auditable_id' => 22,
                'old_values' => '[]',
                'new_values' => '{"pessoas_id":"11","peso":"83.12","altura":"1.57","toma_medicacao":"1","alergia_medicacao":"1","fumante":"2","cirurgia":"1","dor_ossea":"2","dor_muscular":"1","dor_articular":"2","possui_doenca":"2","observacao":"Acima do peso","ano":"2018","id":22}',
                'url' => 'http://localhost/anamneses?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-27 15:39:22',
                'updated_at' => '2018-12-27 15:39:22',
            ),
            86 => 
            array (
                'id' => 87,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Anamnese',
                'auditable_id' => 23,
                'old_values' => '[]',
                'new_values' => '{"pessoas_id":"11","peso":"80.00","altura":"1.57","toma_medicacao":"1","alergia_medicacao":"2","fumante":"2","cirurgia":"1","dor_ossea":"1","dor_muscular":"2","dor_articular":"2","possui_doenca":1,"observacao":"Acima do peso","ano":"2018","id":23}',
                'url' => 'http://localhost/anamneses?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-27 15:40:54',
                'updated_at' => '2018-12-27 15:40:54',
            ),
            87 => 
            array (
                'id' => 88,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Anamnese',
                'auditable_id' => 24,
                'old_values' => '[]',
                'new_values' => '{"pessoas_id":"11","peso":"80.12","altura":"1.57","toma_medicacao":"1","alergia_medicacao":"2","fumante":"2","cirurgia":"1","dor_ossea":"2","dor_muscular":"1","dor_articular":"2","possui_doenca":"2","observacao":null,"ano":"2018","id":24}',
                'url' => 'http://localhost/anamneses?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-27 15:42:18',
                'updated_at' => '2018-12-27 15:42:18',
            ),
            88 => 
            array (
                'id' => 89,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'updated',
                'auditable_type' => 'App\\Anamnese',
                'auditable_id' => 24,
                'old_values' => '{"observacao":null}',
                'new_values' => '{"observacao":"Acima do peso"}',
                'url' => 'http://localhost/anamneses/24?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-27 15:42:25',
                'updated_at' => '2018-12-27 15:42:25',
            ),
            89 => 
            array (
                'id' => 90,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Anamnese',
                'auditable_id' => 25,
                'old_values' => '[]',
                'new_values' => '{"pessoas_id":"8","peso":"84.12","altura":"1.69","toma_medicacao":"2","alergia_medicacao":"2","fumante":"2","cirurgia":"1","dor_ossea":"2","dor_muscular":"2","dor_articular":"2","possui_doenca":1,"observacao":null,"ano":"2018","id":25}',
                'url' => 'http://localhost/anamneses?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-27 15:50:21',
                'updated_at' => '2018-12-27 15:50:21',
            ),
            90 => 
            array (
                'id' => 91,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'updated',
                'auditable_type' => 'App\\Anamnese',
                'auditable_id' => 25,
                'old_values' => '{"observacao":null}',
                'new_values' => '{"observacao":"Obeso"}',
                'url' => 'http://localhost/anamneses/25?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-27 15:51:48',
                'updated_at' => '2018-12-27 15:51:48',
            ),
            91 => 
            array (
                'id' => 92,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Anamnese',
                'auditable_id' => 26,
                'old_values' => '[]',
                'new_values' => '{"pessoas_id":"8","peso":"70.50","altura":"1.69","toma_medicacao":"2","alergia_medicacao":"2","fumante":"2","cirurgia":"1","dor_ossea":"2","dor_muscular":"2","dor_articular":"2","possui_doenca":1,"observacao":null,"ano":"2018","id":26}',
                'url' => 'http://localhost/anamneses?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-27 15:53:09',
                'updated_at' => '2018-12-27 15:53:09',
            ),
            92 => 
            array (
                'id' => 93,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Anamnese',
                'auditable_id' => 27,
                'old_values' => '[]',
                'new_values' => '{"pessoas_id":"8","peso":"65.78","altura":"1.69","toma_medicacao":"2","alergia_medicacao":"2","fumante":"2","cirurgia":"1","dor_ossea":"2","dor_muscular":"2","dor_articular":"2","possui_doenca":"2","observacao":"Sentindo-se bem","ano":"2018","id":27}',
                'url' => 'http://localhost/anamneses?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-27 15:53:57',
                'updated_at' => '2018-12-27 15:53:57',
            ),
            93 => 
            array (
                'id' => 94,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Anamnese',
                'auditable_id' => 28,
                'old_values' => '[]',
                'new_values' => '{"pessoas_id":"7","peso":"58.00","altura":"1.60","toma_medicacao":"2","alergia_medicacao":"2","fumante":"2","cirurgia":"2","dor_ossea":"2","dor_muscular":"1","dor_articular":"2","possui_doenca":1,"observacao":"Sente-se mal utimamente","ano":"2018","id":28}',
                'url' => 'http://localhost/anamneses?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-27 15:58:08',
                'updated_at' => '2018-12-27 15:58:08',
            ),
            94 => 
            array (
                'id' => 95,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'updated',
                'auditable_type' => 'App\\Anamnese',
                'auditable_id' => 28,
                'old_values' => '{"observacao":"Sente-se mal utimamente"}',
                'new_values' => '{"observacao":"Sente-se mal ultimamente"}',
                'url' => 'http://localhost/anamneses/28?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-12-27 15:58:15',
                'updated_at' => '2018-12-27 15:58:15',
            ),
        ));
        
        
    }
}