<?php

use Illuminate\Database\Seeder;

class AuditsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('audits')->delete();
        
        \DB::table('audits')->insert(array (
            0 => 
            array (
                'id' => 1,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'updated',
                'auditable_type' => 'App\\User',
                'auditable_id' => 1,
                'old_values' => '{"remember_token":"5MHmFU0d5fNOtNKXGB8HZGUJBE5qAsCaQoDOcXvpPvXVUhWvOeYxtQT75C5j"}',
                'new_values' => '{"remember_token":"gN1ZypyCSiNIMe9D8se2I6fd9RZXhJy4NYRbEFhr1HJSRQY3w1zFf9kQciBG"}',
                'url' => 'http://localhost/logout?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-11 13:55:03',
                'updated_at' => '2019-02-11 13:55:03',
            ),
            1 => 
            array (
                'id' => 2,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Nucleo',
                'auditable_id' => 1,
                'old_values' => '[]',
                'new_values' => '{"cidade":"S\\u00e3o Leopoldo","inativo":"1","nome":"N\\u00facleo Leste","bairro":"CRISTO REI","rua":"Ruas das Ar\\u00e1ras","numero_endereco":"523","cep":"45.565-892","descricao":"Coment\\u00e1rio exemplo do n\\u00facleo leste","id":1}',
                'url' => 'http://localhost/nucleos?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-11 13:56:02',
                'updated_at' => '2019-02-11 13:56:02',
            ),
            2 => 
            array (
                'id' => 3,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Nucleo',
                'auditable_id' => 2,
                'old_values' => '[]',
                'new_values' => '{"cidade":"S\\u00e3o Leopoldo","inativo":"1","nome":"N\\u00facleo Norte","bairro":"FAZENDA SAO BORJA","rua":"Rua dos Elefantes","numero_endereco":"898","cep":"56.548-988","descricao":"Coment\\u00e1rio exemplo do n\\u00facleo norte.","id":2}',
                'url' => 'http://localhost/nucleos?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-11 13:57:14',
                'updated_at' => '2019-02-11 13:57:14',
            ),
            3 => 
            array (
                'id' => 4,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'updated',
                'auditable_type' => 'App\\Nucleo',
                'auditable_id' => 1,
                'old_values' => '{"descricao":"Coment\\u00e1rio exemplo do n\\u00facleo leste"}',
                'new_values' => '{"descricao":"Coment\\u00e1rio exemplo do n\\u00facleo leste."}',
                'url' => 'http://localhost/nucleos/1?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-11 13:57:29',
                'updated_at' => '2019-02-11 13:57:29',
            ),
            4 => 
            array (
                'id' => 5,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Nucleo',
                'auditable_id' => 3,
                'old_values' => '[]',
                'new_values' => '{"cidade":"S\\u00e3o Leopoldo","inativo":"1","nome":"N\\u00facleo Oeste","bairro":"CENTRO","rua":"Rua das Gaivotas","numero_endereco":"985","cep":"87.945-687","descricao":"Coment\\u00e1rio exemplo do n\\u00facleo Oeste.","id":3}',
                'url' => 'http://localhost/nucleos?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-11 13:58:55',
                'updated_at' => '2019-02-11 13:58:55',
            ),
            5 => 
            array (
                'id' => 6,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'updated',
                'auditable_type' => 'App\\Nucleo',
                'auditable_id' => 1,
                'old_values' => '{"descricao":"Coment\\u00e1rio exemplo do n\\u00facleo leste."}',
                'new_values' => '{"descricao":"Coment\\u00e1rio exemplo do n\\u00facleo Leste."}',
                'url' => 'http://localhost/nucleos/1?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-11 13:59:14',
                'updated_at' => '2019-02-11 13:59:14',
            ),
            6 => 
            array (
                'id' => 7,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'updated',
                'auditable_type' => 'App\\Nucleo',
                'auditable_id' => 2,
                'old_values' => '{"descricao":"Coment\\u00e1rio exemplo do n\\u00facleo norte."}',
                'new_values' => '{"descricao":"Coment\\u00e1rio exemplo do n\\u00facleo Norte."}',
                'url' => 'http://localhost/nucleos/2?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-11 13:59:25',
                'updated_at' => '2019-02-11 13:59:25',
            ),
            7 => 
            array (
                'id' => 8,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Nucleo',
                'auditable_id' => 4,
                'old_values' => '[]',
                'new_values' => '{"cidade":"S\\u00e3o Leopoldo","inativo":"1","nome":"N\\u00facleo Sul","bairro":"CAMPINA","rua":"Rua das Panteras","numero_endereco":"468","cep":"46.589-223","descricao":"Coment\\u00e1rio exemplo do n\\u00facleo Sul.","id":4}',
                'url' => 'http://localhost/nucleos?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-11 14:00:03',
                'updated_at' => '2019-02-11 14:00:03',
            ),
            8 => 
            array (
                'id' => 9,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Turma',
                'auditable_id' => 1,
                'old_values' => '[]',
                'new_values' => '{"nome":"Turma de Basquete A1","limite":"8","horario_inicial":"24:00:00","horario_final":"14:00:00","data_semanal":"Segunda,Quinta,","nucleo_id":"1","descricao":null,"inativo":"1","id":1}',
                'url' => 'http://localhost/turmas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-11 14:01:53',
                'updated_at' => '2019-02-11 14:01:53',
            ),
            9 => 
            array (
                'id' => 10,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'updated',
                'auditable_type' => 'App\\Nucleo',
                'auditable_id' => 1,
                'old_values' => '{"descricao":"Coment\\u00e1rio exemplo do n\\u00facleo Leste."}',
                'new_values' => '{"descricao":"Coment\\u00e1rio exemplo do n\\u00facleo Leste"}',
                'url' => 'http://localhost/nucleos/1?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-11 14:09:04',
                'updated_at' => '2019-02-11 14:09:04',
            ),
            10 => 
            array (
                'id' => 11,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'updated',
                'auditable_type' => 'App\\Nucleo',
                'auditable_id' => 2,
                'old_values' => '{"descricao":"Coment\\u00e1rio exemplo do n\\u00facleo Norte."}',
                'new_values' => '{"descricao":"Coment\\u00e1rio exemplo do n\\u00facleo Norte"}',
                'url' => 'http://localhost/nucleos/2?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-11 14:10:31',
                'updated_at' => '2019-02-11 14:10:31',
            ),
            11 => 
            array (
                'id' => 12,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Turma',
                'auditable_id' => 2,
                'old_values' => '[]',
                'new_values' => '{"nome":"Turma de Basquete A2","limite":"8","horario_inicial":"12:00:00","horario_final":"14:00:00","data_semanal":"Quinta,Sexta,","nucleo_id":"2","descricao":null,"inativo":"1","id":2}',
                'url' => 'http://localhost/turmas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-11 14:13:20',
                'updated_at' => '2019-02-11 14:13:20',
            ),
            12 => 
            array (
                'id' => 13,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Turma',
                'auditable_id' => 3,
                'old_values' => '[]',
                'new_values' => '{"nome":"Turma de Futebol A1","limite":"8","horario_inicial":"12:00:00","horario_final":"14:00:00","data_semanal":"Domingo,Sabado,","nucleo_id":"4","descricao":null,"inativo":"1","id":3}',
                'url' => 'http://localhost/turmas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-11 14:14:34',
                'updated_at' => '2019-02-11 14:14:34',
            ),
            13 => 
            array (
                'id' => 14,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Turma',
                'auditable_id' => 4,
                'old_values' => '[]',
                'new_values' => '{"nome":"Turma de Futebol A2","limite":"8","horario_inicial":"15:00:00","horario_final":"18:00:00","data_semanal":"Quinta,Sexta,","nucleo_id":"2","descricao":null,"inativo":"1","id":4}',
                'url' => 'http://localhost/turmas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-11 14:15:48',
                'updated_at' => '2019-02-11 14:15:48',
            ),
            14 => 
            array (
                'id' => 15,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Turma',
                'auditable_id' => 5,
                'old_values' => '[]',
                'new_values' => '{"nome":"Turma de Ginastica","limite":"5","horario_inicial":"18:00:00","horario_final":"20:00:00","data_semanal":"Ter\\u00e7a,Sexta,","nucleo_id":"3","descricao":null,"inativo":"1","id":5}',
                'url' => 'http://localhost/turmas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-11 14:16:54',
                'updated_at' => '2019-02-11 14:16:54',
            ),
            15 => 
            array (
                'id' => 16,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'updated',
                'auditable_type' => 'App\\Turma',
                'auditable_id' => 5,
                'old_values' => '{"nome":"Turma de Ginastica"}',
                'new_values' => '{"nome":"Turma de Ginastica A1"}',
                'url' => 'http://localhost/turmas/5?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-11 15:10:35',
                'updated_at' => '2019-02-11 15:10:35',
            ),
            16 => 
            array (
                'id' => 17,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Turma',
                'auditable_id' => 6,
                'old_values' => '[]',
                'new_values' => '{"nome":"Turma de A2","limite":"8","horario_inicial":"17:00:00","horario_final":"19:00:00","data_semanal":"Quinta,Sexta,","nucleo_id":"3","descricao":null,"inativo":"1","id":6}',
                'url' => 'http://localhost/turmas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-11 15:13:13',
                'updated_at' => '2019-02-11 15:13:13',
            ),
            17 => 
            array (
                'id' => 18,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'updated',
                'auditable_type' => 'App\\Turma',
                'auditable_id' => 6,
                'old_values' => '{"nome":"Turma de A2"}',
                'new_values' => '{"nome":"Turma de Ginastica A2"}',
                'url' => 'http://localhost/turmas/6?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-11 15:13:35',
                'updated_at' => '2019-02-11 15:13:35',
            ),
            18 => 
            array (
                'id' => 19,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Turma',
                'auditable_id' => 7,
                'old_values' => '[]',
                'new_values' => '{"nome":"Turma de Futebol A3","limite":"8","horario_inicial":"20:00:00","horario_final":"22:00:00","data_semanal":"Segunda,Ter\\u00e7a,","nucleo_id":"1","descricao":null,"inativo":"1","id":7}',
                'url' => 'http://localhost/turmas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-11 15:17:46',
                'updated_at' => '2019-02-11 15:17:46',
            ),
            19 => 
            array (
                'id' => 20,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Doenca',
                'auditable_id' => 1,
                'old_values' => '[]',
                'new_values' => '{"nome":"Primeira Doen\\u00e7a","descricao":"Coment\\u00e1rio doen\\u00e7a 1","id":1}',
                'url' => 'http://localhost/doencas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-11 15:19:20',
                'updated_at' => '2019-02-11 15:19:20',
            ),
            20 => 
            array (
                'id' => 21,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Doenca',
                'auditable_id' => 2,
                'old_values' => '[]',
                'new_values' => '{"nome":"Segunda Doen\\u00e7a","descricao":"Coment\\u00e1rio Doen\\u00e7a 2","id":2}',
                'url' => 'http://localhost/doencas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-11 15:19:33',
                'updated_at' => '2019-02-11 15:19:33',
            ),
            21 => 
            array (
                'id' => 22,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Doenca',
                'auditable_id' => 3,
                'old_values' => '[]',
                'new_values' => '{"nome":"Terceira Doen\\u00e7a","descricao":"Coment\\u00e1rio Doen\\u00e7a 3","id":3}',
                'url' => 'http://localhost/doencas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-11 15:20:19',
                'updated_at' => '2019-02-11 15:20:19',
            ),
            22 => 
            array (
                'id' => 23,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Doenca',
                'auditable_id' => 4,
                'old_values' => '[]',
                'new_values' => '{"nome":"Quarta Doen\\u00e7a","descricao":"Coment\\u00e1rio Doen\\u00e7a 4","id":4}',
                'url' => 'http://localhost/doencas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-11 15:20:39',
                'updated_at' => '2019-02-11 15:20:39',
            ),
            23 => 
            array (
                'id' => 24,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Pessoa',
                'auditable_id' => 1,
                'old_values' => '[]',
            'new_values' => '{"foto":null,"nome":"Jo\\u00e3o Almeida","nascimento":"1994-08-17","sexo":"M","rg":"871354981","cpf":"498.798.498-49","cpf_responsavel":null,"cidade":"S\\u00e3o Leopoldo","rua":"Primeira rua da FEITORIA","bairro":null,"numero_endereco":"465","complemento":"Bloco 4","cep":"41.657-898","telefone":"(51) 5161-5689","telefone_emergencia":"(51) 6516-8765","estado_civil":"Solteiro","nome_do_pai":"Bruno almeida","nome_da_mae":"Rita Almeida","pessoa_emergencia":"Augusto Almeida","filhos":"0","convenio_medico":"SON","mora_com_os_pais":"2","matricula":null,"estado":2,"id":1}',
                'url' => 'http://localhost/pessoas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-11 15:31:32',
                'updated_at' => '2019-02-11 15:31:32',
            ),
            24 => 
            array (
                'id' => 25,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Anamnese',
                'auditable_id' => 1,
                'old_values' => '[]',
                'new_values' => '{"possui_doenca":"2","toma_medicacao":-1,"alergia_medicacao":-1,"peso":"68","altura":"1.79","fumante":"2","cirurgia":"Perna direita","dor_muscular":-1,"dor_articular":"M\\u00e3o esquerda","dor_ossea":-1,"atestado":"2","observacao":null,"ano":"2019","pessoas_id":1,"id":1}',
                'url' => 'http://localhost/pessoas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-11 15:31:32',
                'updated_at' => '2019-02-11 15:31:32',
            ),
            25 => 
            array (
                'id' => 26,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\HistoricoPT',
                'auditable_id' => 1,
                'old_values' => '[]',
                'new_values' => '{"pessoa_id":"1","turma_id":"1","inativo":"1","comentario":null,"id":1}',
                'url' => 'http://localhost/pessoas_turmas/vincular?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-11 15:32:23',
                'updated_at' => '2019-02-11 15:32:23',
            ),
            26 => 
            array (
                'id' => 27,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\HistoricoPT',
                'auditable_id' => 2,
                'old_values' => '[]',
                'new_values' => '{"pessoa_id":"1","turma_id":"2","inativo":"1","comentario":null,"id":2}',
                'url' => 'http://localhost/pessoas_turmas/vincular?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-11 15:32:26',
                'updated_at' => '2019-02-11 15:32:26',
            ),
            27 => 
            array (
                'id' => 28,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'updated',
                'auditable_type' => 'App\\Pessoa',
                'auditable_id' => 1,
                'old_values' => '{"nascimento":"1994-08-17 00:00:00","bairro":null,"convenio_medico":"SON"}',
                'new_values' => '{"nascimento":"1994-08-17","bairro":"FEITORIA","convenio_medico":null}',
                'url' => 'http://localhost/pessoas/1?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-11 15:33:07',
                'updated_at' => '2019-02-11 15:33:07',
            ),
            28 => 
            array (
                'id' => 29,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'updated',
                'auditable_type' => 'App\\Pessoa',
                'auditable_id' => 1,
                'old_values' => '{"foto":null,"nascimento":"1994-08-17 00:00:00","convenio_medico":null,"estado":2}',
                'new_values' => '{"foto":"img\\/img_3x4\\/imagem_5670.png","nascimento":"1994-08-17","convenio_medico":"SON","estado":1}',
                'url' => 'http://localhost/pessoas/1?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-11 15:45:31',
                'updated_at' => '2019-02-11 15:45:31',
            ),
            29 => 
            array (
                'id' => 30,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'updated',
                'auditable_type' => 'App\\Anamnese',
                'auditable_id' => 1,
                'old_values' => '{"possui_doenca":2}',
                'new_values' => '{"possui_doenca":1}',
                'url' => 'http://localhost/anamneses/1?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-12 12:00:20',
                'updated_at' => '2019-02-12 12:00:20',
            ),
            30 => 
            array (
                'id' => 31,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\User',
                'auditable_id' => 2,
                'old_values' => '[]',
                'new_values' => '{"name":"professorum","email":"professorum@professorum.com","password":"$2y$10$\\/dy51kz48UfcxaVqdb2Q7Oj7ING.WBcbZkGklYocBo4OfKttD3XP.","admin_professor":0,"id":2}',
                'url' => 'http://localhost/professor?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-12 12:44:50',
                'updated_at' => '2019-02-12 12:44:50',
            ),
            31 => 
            array (
                'id' => 32,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Professor',
                'auditable_id' => 1,
                'old_values' => '[]',
            'new_values' => '{"nome":"Professor Um","nascimento":"1991-10-16","matricula":"45318921","cidade":"Novo Hamburgo","rua":"Rua de Novo Hamburgo","cep":"74.897-256","numero_endereco":"762","complemento":null,"telefone":"(51) 6515-6186","cpf":"489.789.123-45","rg":"4898465113","formacao":"Forma\\u00e7\\u00e3o 1","curso":"Curso 1","cref":"CREF 1","user_id":2,"id":1}',
                'url' => 'http://localhost/professor?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-12 12:44:50',
                'updated_at' => '2019-02-12 12:44:50',
            ),
            32 => 
            array (
                'id' => 33,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\User',
                'auditable_id' => 3,
                'old_values' => '[]',
                'new_values' => '{"name":"professordois","email":"professordois@professordois.com","password":"$2y$10$mxPNgTczDRRo7PTbgCq.\\/OUk73G1gvM\\/jYgcm0.ceOPsfquik3h6a","admin_professor":0,"id":3}',
                'url' => 'http://localhost/professor?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-12 13:05:15',
                'updated_at' => '2019-02-12 13:05:15',
            ),
            33 => 
            array (
                'id' => 34,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Professor',
                'auditable_id' => 2,
                'old_values' => '[]',
            'new_values' => '{"nome":"Professor Dois","nascimento":"1988-07-21","matricula":"54649875","cidade":"S\\u00e3o Leopoldo","bairro":"CAMPESTRE","rua":"Rua numero um Campestre","cep":"45.646-879","numero_endereco":"456","complemento":null,"telefone":"(51) 6568-7953","cpf":"465.798.426-57","rg":"546549982","formacao":"Forma\\u00e7\\u00e3o 2","curso":"Curso 2","cref":"CREF 2","user_id":3,"id":2}',
                'url' => 'http://localhost/professor?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-12 13:05:16',
                'updated_at' => '2019-02-12 13:05:16',
            ),
            34 => 
            array (
                'id' => 35,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\User',
                'auditable_id' => 4,
                'old_values' => '[]',
                'new_values' => '{"name":"professortres","email":"professortres@professortres.com","password":"$2y$10$G5RUX119qbGoRjp5sTTGGOGWqXsym4SBItCbDfEJFCgDWuXcGl3b6","admin_professor":0,"id":4}',
                'url' => 'http://localhost/professor?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-12 13:11:42',
                'updated_at' => '2019-02-12 13:11:42',
            ),
            35 => 
            array (
                'id' => 36,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Professor',
                'auditable_id' => 3,
                'old_values' => '[]',
            'new_values' => '{"nome":"Professor Tr\\u00eas","nascimento":"1990-09-13","matricula":"13548985","cidade":"Canoas","rua":"Rua de Canoas","cep":"65.719-878","numero_endereco":"987","complemento":null,"telefone":"(51) 6873-0608","cpf":"700.988.975-68","rg":"08940985","formacao":"Forma\\u00e7\\u00e3o 3","curso":"Curso 3","cref":"CREF 3","user_id":4,"id":3}',
                'url' => 'http://localhost/professor?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-12 13:11:42',
                'updated_at' => '2019-02-12 13:11:42',
            ),
            36 => 
            array (
                'id' => 37,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\User',
                'auditable_id' => 5,
                'old_values' => '[]',
                'new_values' => '{"name":"professorquatro","email":"professorquatro@professorquatro.com","password":"$2y$10$kn1CjhLdBIIWNK4FENz67O9SshOwoRcxfW783nsdQzWVLvEW5FT0W","admin_professor":0,"id":5}',
                'url' => 'http://localhost/professor?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-12 13:28:42',
                'updated_at' => '2019-02-12 13:28:42',
            ),
            37 => 
            array (
                'id' => 38,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Professor',
                'auditable_id' => 4,
                'old_values' => '[]',
            'new_values' => '{"nome":"Professor Quatro","nascimento":"1992-06-16","matricula":"49878423","cidade":"S\\u00e3o Leopoldo","bairro":"ARROIO DA MANTEIGA","rua":"Rua numero um do arroio da manteiga","cep":"46.544-648","numero_endereco":"519","complemento":"Bloco 2","telefone":"(51) 6489-7865","cpf":"909.007.889-77","rg":"6179781868","formacao":"Forma\\u00e7\\u00e3o 4","curso":"Curso 4","cref":"CREF 3","user_id":5,"id":4}',
                'url' => 'http://localhost/professor?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-12 13:28:42',
                'updated_at' => '2019-02-12 13:28:42',
            ),
            38 => 
            array (
                'id' => 39,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'updated',
                'auditable_type' => 'App\\Nucleo',
                'auditable_id' => 1,
                'old_values' => '{"nome":"N\\u00facleo Leste"}',
                'new_values' => '{"nome":"N\\u00facleo Lest"}',
                'url' => 'http://localhost/nucleos/1?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-12 13:53:11',
                'updated_at' => '2019-02-12 13:53:11',
            ),
            39 => 
            array (
                'id' => 40,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'updated',
                'auditable_type' => 'App\\Nucleo',
                'auditable_id' => 1,
                'old_values' => '{"nome":"N\\u00facleo Lest"}',
                'new_values' => '{"nome":"N\\u00facleo Leste"}',
                'url' => 'http://localhost/nucleos/1?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-12 13:54:03',
                'updated_at' => '2019-02-12 13:54:03',
            ),
            40 => 
            array (
                'id' => 41,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'updated',
                'auditable_type' => 'App\\Anamnese',
                'auditable_id' => 1,
                'old_values' => '{"toma_medicacao":"-1"}',
                'new_values' => '{"toma_medicacao":null}',
                'url' => 'http://localhost/anamneses/1?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-12 14:54:54',
                'updated_at' => '2019-02-12 14:54:54',
            ),
            41 => 
            array (
                'id' => 42,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\User',
                'auditable_id' => 6,
                'old_values' => '[]',
                'new_values' => '{"name":"professorcinco","email":"professorcinco@professorcinco.com","password":"$2y$10$X\\/gY6cgkKrrAAl2WIpRj0e35FHBp.LFGxLE94m3R9FzYpNnhV.5nu","admin_professor":0,"id":6}',
                'url' => 'http://localhost/professor?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-13 09:48:25',
                'updated_at' => '2019-02-13 09:48:25',
            ),
            42 => 
            array (
                'id' => 43,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Professor',
                'auditable_id' => 5,
                'old_values' => '[]',
            'new_values' => '{"nome":"Proessor Cinco","nascimento":"2019-02-12","matricula":"16512312","cidade":"S\\u00e3o Leopoldo","bairro":"JARDIM AMERICA","rua":"Rua numero um Jardim America","cep":"46.546-549","numero_endereco":"168","complemento":null,"telefone":"(51) 6516-8798","cpf":"498.732.215-98","rg":"51651236","formacao":"Forma\\u00e7\\u00e3o 5","curso":"Curso 5","cref":"CREF 5","user_id":6,"id":5}',
                'url' => 'http://localhost/professor?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-13 09:48:25',
                'updated_at' => '2019-02-13 09:48:25',
            ),
            43 => 
            array (
                'id' => 44,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\HistoricoPrT',
                'auditable_id' => 1,
                'old_values' => '[]',
                'new_values' => '{"professor_id":"1","turma_id":"1","comentario":null,"inativo":1,"id":1}',
                'url' => 'http://localhost/professor_turmas/vincular?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-13 09:50:19',
                'updated_at' => '2019-02-13 09:50:19',
            ),
            44 => 
            array (
                'id' => 45,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\HistoricoPrT',
                'auditable_id' => 2,
                'old_values' => '[]',
                'new_values' => '{"professor_id":"1","turma_id":"2","comentario":null,"inativo":1,"id":2}',
                'url' => 'http://localhost/professor_turmas/vincular?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-13 09:50:26',
                'updated_at' => '2019-02-13 09:50:26',
            ),
            45 => 
            array (
                'id' => 46,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\HistoricoPrT',
                'auditable_id' => 3,
                'old_values' => '[]',
                'new_values' => '{"professor_id":"2","turma_id":"3","comentario":null,"inativo":1,"id":3}',
                'url' => 'http://localhost/professor_turmas/vincular?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-13 09:58:43',
                'updated_at' => '2019-02-13 09:58:43',
            ),
            46 => 
            array (
                'id' => 47,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\HistoricoPrT',
                'auditable_id' => 4,
                'old_values' => '[]',
                'new_values' => '{"professor_id":"2","turma_id":"4","comentario":null,"inativo":1,"id":4}',
                'url' => 'http://localhost/professor_turmas/vincular?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-13 09:58:46',
                'updated_at' => '2019-02-13 09:58:46',
            ),
            47 => 
            array (
                'id' => 48,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\HistoricoPrT',
                'auditable_id' => 5,
                'old_values' => '[]',
                'new_values' => '{"professor_id":"3","turma_id":"5","comentario":null,"inativo":1,"id":5}',
                'url' => 'http://localhost/professor_turmas/vincular?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-13 09:58:55',
                'updated_at' => '2019-02-13 09:58:55',
            ),
            48 => 
            array (
                'id' => 49,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\HistoricoPrT',
                'auditable_id' => 6,
                'old_values' => '[]',
                'new_values' => '{"professor_id":"3","turma_id":"6","comentario":null,"inativo":1,"id":6}',
                'url' => 'http://localhost/professor_turmas/vincular?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-13 09:58:58',
                'updated_at' => '2019-02-13 09:58:58',
            ),
            49 => 
            array (
                'id' => 50,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\HistoricoPrT',
                'auditable_id' => 7,
                'old_values' => '[]',
                'new_values' => '{"professor_id":"4","turma_id":"1","comentario":null,"inativo":1,"id":7}',
                'url' => 'http://localhost/professor_turmas/vincular?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-13 09:59:17',
                'updated_at' => '2019-02-13 09:59:17',
            ),
            50 => 
            array (
                'id' => 51,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\HistoricoPrT',
                'auditable_id' => 8,
                'old_values' => '[]',
                'new_values' => '{"professor_id":"4","turma_id":"2","comentario":null,"inativo":1,"id":8}',
                'url' => 'http://localhost/professor_turmas/vincular?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-13 09:59:20',
                'updated_at' => '2019-02-13 09:59:20',
            ),
            51 => 
            array (
                'id' => 52,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\HistoricoPrT',
                'auditable_id' => 9,
                'old_values' => '[]',
                'new_values' => '{"professor_id":"5","turma_id":"4","comentario":null,"inativo":1,"id":9}',
                'url' => 'http://localhost/professor_turmas/vincular?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-13 09:59:29',
                'updated_at' => '2019-02-13 09:59:29',
            ),
            52 => 
            array (
                'id' => 53,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\HistoricoPrT',
                'auditable_id' => 10,
                'old_values' => '[]',
                'new_values' => '{"professor_id":"5","turma_id":"7","comentario":null,"inativo":1,"id":10}',
                'url' => 'http://localhost/professor_turmas/vincular?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-13 09:59:32',
                'updated_at' => '2019-02-13 09:59:32',
            ),
            53 => 
            array (
                'id' => 54,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Pessoa',
                'auditable_id' => 2,
                'old_values' => '[]',
            'new_values' => '{"foto":"img\\/img_3x4\\/imagem_3954.png","nome":"Felipe da Silva Soares","nascimento":"2005-06-08","sexo":"M","rg":"1231465489","cpf":"489.321.087-56","cpf_responsavel":"489.489.454-68","cidade":"S\\u00e3o Leopoldo","rua":"Rua numero um Feitoria","bairro":null,"numero_endereco":"562","complemento":null,"cep":"46.549-878","telefone":"(51) 6165-8792","telefone_emergencia":"(51) 5616-8795","estado_civil":"Solteiro","nome_do_pai":"Gustavo da Silva Soares","nome_da_mae":"Ana da Silva Soares","pessoa_emergencia":"Julio da Silva Soares (irm\\u00e3o)","filhos":"0","convenio_medico":"OM","mora_com_os_pais":"1","matricula":"img\\/img_matricula\\/imagem_7983.jpeg","estado":2,"id":2}',
                'url' => 'http://localhost/pessoas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-13 10:06:56',
                'updated_at' => '2019-02-13 10:06:56',
            ),
            54 => 
            array (
                'id' => 55,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Anamnese',
                'auditable_id' => 2,
                'old_values' => '[]',
                'new_values' => '{"possui_doenca":"2","toma_medicacao":"Medicamento 1","alergia_medicacao":"Alergia 1","peso":"65","altura":"1.69","fumante":"2","cirurgia":-1,"dor_muscular":-1,"dor_articular":"Punho esquerdo","dor_ossea":-1,"atestado":"2","observacao":null,"ano":"2019","pessoas_id":2,"id":2}',
                'url' => 'http://localhost/pessoas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-13 10:06:56',
                'updated_at' => '2019-02-13 10:06:56',
            ),
            55 => 
            array (
                'id' => 56,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'updated',
                'auditable_type' => 'App\\Turma',
                'auditable_id' => 2,
                'old_values' => '{"inativo":1}',
                'new_values' => '{"inativo":2}',
                'url' => 'http://localhost/turmas/ativar_inativar?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-13 10:14:47',
                'updated_at' => '2019-02-13 10:14:47',
            ),
            56 => 
            array (
                'id' => 57,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\HistoricoT',
                'auditable_id' => 1,
                'old_values' => '[]',
                'new_values' => '{"turma_id":"2","comentario":"Chuva intensa","inativo":2,"id":1}',
                'url' => 'http://localhost/turmas/ativar_inativar?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-13 10:14:47',
                'updated_at' => '2019-02-13 10:14:47',
            ),
            57 => 
            array (
                'id' => 58,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'updated',
                'auditable_type' => 'App\\Turma',
                'auditable_id' => 5,
                'old_values' => '{"inativo":1}',
                'new_values' => '{"inativo":2}',
                'url' => 'http://localhost/turmas/ativar_inativar?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-13 10:15:13',
                'updated_at' => '2019-02-13 10:15:13',
            ),
            58 => 
            array (
                'id' => 59,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\HistoricoT',
                'auditable_id' => 2,
                'old_values' => '[]',
                'new_values' => '{"turma_id":"5","comentario":"Fechamento temporario","inativo":2,"id":2}',
                'url' => 'http://localhost/turmas/ativar_inativar?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-13 10:15:13',
                'updated_at' => '2019-02-13 10:15:13',
            ),
            59 => 
            array (
                'id' => 60,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'updated',
                'auditable_type' => 'App\\Turma',
                'auditable_id' => 2,
                'old_values' => '{"inativo":2}',
                'new_values' => '{"inativo":1}',
                'url' => 'http://localhost/turmas/ativar_inativar?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-13 10:22:11',
                'updated_at' => '2019-02-13 10:22:11',
            ),
            60 => 
            array (
                'id' => 61,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\HistoricoT',
                'auditable_id' => 3,
                'old_values' => '[]',
                'new_values' => '{"turma_id":"2","comentario":null,"inativo":1,"id":3}',
                'url' => 'http://localhost/turmas/ativar_inativar?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-13 10:22:11',
                'updated_at' => '2019-02-13 10:22:11',
            ),
            61 => 
            array (
                'id' => 62,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'updated',
                'auditable_type' => 'App\\Turma',
                'auditable_id' => 5,
                'old_values' => '{"inativo":2}',
                'new_values' => '{"inativo":1}',
                'url' => 'http://localhost/turmas/ativar_inativar?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-13 10:22:19',
                'updated_at' => '2019-02-13 10:22:19',
            ),
            62 => 
            array (
                'id' => 63,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\HistoricoT',
                'auditable_id' => 4,
                'old_values' => '[]',
                'new_values' => '{"turma_id":"5","comentario":null,"inativo":1,"id":4}',
                'url' => 'http://localhost/turmas/ativar_inativar?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-13 10:22:19',
                'updated_at' => '2019-02-13 10:22:19',
            ),
            63 => 
            array (
                'id' => 64,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'updated',
                'auditable_type' => 'App\\Pessoa',
                'auditable_id' => 2,
                'old_values' => '{"nascimento":"2005-06-08 00:00:00","bairro":null}',
                'new_values' => '{"nascimento":"2005-06-08","bairro":"FEITORIA"}',
                'url' => 'http://localhost/pessoas/2?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-13 10:52:38',
                'updated_at' => '2019-02-13 10:52:38',
            ),
            64 => 
            array (
                'id' => 65,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'updated',
                'auditable_type' => 'App\\Pessoa',
                'auditable_id' => 2,
                'old_values' => '{"nascimento":"2005-06-08 00:00:00"}',
                'new_values' => '{"nascimento":"2005-06-08"}',
                'url' => 'http://localhost/pessoas/2?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-13 10:54:17',
                'updated_at' => '2019-02-13 10:54:17',
            ),
            65 => 
            array (
                'id' => 66,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'updated',
                'auditable_type' => 'App\\Pessoa',
                'auditable_id' => 2,
                'old_values' => '{"nascimento":"2005-06-08 00:00:00","rg_responsavel":null}',
                'new_values' => '{"nascimento":"2005-06-08","rg_responsavel":"1231321312335"}',
                'url' => 'http://localhost/pessoas/2?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-13 10:55:39',
                'updated_at' => '2019-02-13 10:55:39',
            ),
            66 => 
            array (
                'id' => 67,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'updated',
                'auditable_type' => 'App\\Pessoa',
                'auditable_id' => 2,
                'old_values' => '{"nascimento":"2005-06-08 00:00:00"}',
                'new_values' => '{"nascimento":"2005-06-08"}',
                'url' => 'http://localhost/pessoas/2?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-13 10:55:47',
                'updated_at' => '2019-02-13 10:55:47',
            ),
            67 => 
            array (
                'id' => 68,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'updated',
                'auditable_type' => 'App\\Pessoa',
                'auditable_id' => 2,
                'old_values' => '{"nascimento":"2005-06-08 00:00:00","estado":2}',
                'new_values' => '{"nascimento":"2005-06-08","estado":1}',
                'url' => 'http://localhost/pessoas/2?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-13 10:58:23',
                'updated_at' => '2019-02-13 10:58:23',
            ),
            68 => 
            array (
                'id' => 69,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'updated',
                'auditable_type' => 'App\\Pessoa',
                'auditable_id' => 2,
                'old_values' => '{"nascimento":"2005-06-08 00:00:00","numero_endereco":"562","estado":1}',
                'new_values' => '{"nascimento":"2005-06-08","numero_endereco":null,"estado":2}',
                'url' => 'http://localhost/pessoas/2?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-13 11:27:05',
                'updated_at' => '2019-02-13 11:27:05',
            ),
            69 => 
            array (
                'id' => 70,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'updated',
                'auditable_type' => 'App\\Nucleo',
                'auditable_id' => 1,
                'old_values' => '{"inativo":1}',
                'new_values' => '{"inativo":2}',
                'url' => 'http://localhost/nucleos/ativar_inativar?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-13 11:29:03',
                'updated_at' => '2019-02-13 11:29:03',
            ),
            70 => 
            array (
                'id' => 71,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\HistoricoN',
                'auditable_id' => 1,
                'old_values' => '[]',
                'new_values' => '{"nucleo_id":"1","comentario":"1221332","inativo":2,"id":1}',
                'url' => 'http://localhost/nucleos/ativar_inativar?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-13 11:29:03',
                'updated_at' => '2019-02-13 11:29:03',
            ),
            71 => 
            array (
                'id' => 72,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'updated',
                'auditable_type' => 'App\\User',
                'auditable_id' => 1,
                'old_values' => '{"remember_token":"gN1ZypyCSiNIMe9D8se2I6fd9RZXhJy4NYRbEFhr1HJSRQY3w1zFf9kQciBG"}',
                'new_values' => '{"remember_token":"L255VlLnxPao66vOJqmntAJjxgcq54H11rQ1TOwagY7f2YFwZeB5BQ0M0yni"}',
                'url' => 'http://localhost/logout?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-13 11:47:55',
                'updated_at' => '2019-02-13 11:47:55',
            ),
            72 => 
            array (
                'id' => 73,
                'user_type' => 'App\\User',
                'user_id' => 2,
                'event' => 'updated',
                'auditable_type' => 'App\\User',
                'auditable_id' => 2,
                'old_values' => '{"remember_token":null}',
                'new_values' => '{"remember_token":"FSCUBxjTvdfLMed61V33dYFD93hU4u1uqCoTbJcY42nGUiMOGeQY2HenYWpk"}',
                'url' => 'http://localhost/logout?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-13 11:53:16',
                'updated_at' => '2019-02-13 11:53:16',
            ),
            73 => 
            array (
                'id' => 74,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\HistoricoPT',
                'auditable_id' => 3,
                'old_values' => '[]',
                'new_values' => '{"pessoa_id":"1","turma_id":"2","comentario":"iuhuih","inativo":2,"id":3}',
                'url' => 'http://localhost/pessoas_turmas/ativar_inativar?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-13 11:57:37',
                'updated_at' => '2019-02-13 11:57:37',
            ),
            74 => 
            array (
                'id' => 75,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\HistoricoPT',
                'auditable_id' => 4,
                'old_values' => '[]',
                'new_values' => '{"pessoa_id":"1","turma_id":"3","inativo":"1","comentario":null,"id":4}',
                'url' => 'http://localhost/pessoas_turmas/vincular?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-13 11:59:08',
                'updated_at' => '2019-02-13 11:59:08',
            ),
            75 => 
            array (
                'id' => 76,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'updated',
                'auditable_type' => 'App\\User',
                'auditable_id' => 1,
                'old_values' => '{"remember_token":"L255VlLnxPao66vOJqmntAJjxgcq54H11rQ1TOwagY7f2YFwZeB5BQ0M0yni"}',
                'new_values' => '{"remember_token":"PZbBo3U7RGTXKlQGkwBAsaUiShG3n5nJ370NdcmX1U25bMFM6wW1VcwaM0il"}',
                'url' => 'http://localhost/logout?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-13 12:24:19',
                'updated_at' => '2019-02-13 12:24:19',
            ),
            76 => 
            array (
                'id' => 77,
                'user_type' => 'App\\User',
                'user_id' => 2,
                'event' => 'updated',
                'auditable_type' => 'App\\User',
                'auditable_id' => 2,
                'old_values' => '{"remember_token":"FSCUBxjTvdfLMed61V33dYFD93hU4u1uqCoTbJcY42nGUiMOGeQY2HenYWpk"}',
                'new_values' => '{"remember_token":"oPX1sDHRxLes6toEjvaEnZaxV9by3fBgPEufW1A78Tz0PSyVo0bxKyj78GpS"}',
                'url' => 'http://localhost/logout?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-13 12:25:16',
                'updated_at' => '2019-02-13 12:25:16',
            ),
            77 => 
            array (
                'id' => 78,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'updated',
                'auditable_type' => 'App\\Pessoa',
                'auditable_id' => 2,
                'old_values' => '{"nascimento":"2005-06-08 00:00:00","numero_endereco":null,"estado":2}',
                'new_values' => '{"nascimento":"2005-06-08","numero_endereco":"788","estado":1}',
                'url' => 'http://localhost/pessoas/2?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-13 12:38:19',
                'updated_at' => '2019-02-13 12:38:19',
            ),
            78 => 
            array (
                'id' => 79,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'updated',
                'auditable_type' => 'App\\Professor',
                'auditable_id' => 5,
                'old_values' => '{"nome":"Proessor Cinco","nascimento":"2019-02-12 00:00:00"}',
                'new_values' => '{"nome":"Professor Cinco","nascimento":"2019-02-12"}',
                'url' => 'http://localhost/professor/5?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-13 14:14:01',
                'updated_at' => '2019-02-13 14:14:01',
            ),
            79 => 
            array (
                'id' => 80,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'updated',
                'auditable_type' => 'App\\Quant',
                'auditable_id' => 1,
                'old_values' => '{"quantidade":4}',
                'new_values' => '{"quantidade":"2"}',
                'url' => 'http://localhost/pessoa/quantidade?_token=LDpMgcZJiC3vMQxNOZN3MMoG5whktgQc5MplLks5&pessoa_id=2&quantidade=2',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-13 14:15:04',
                'updated_at' => '2019-02-13 14:15:04',
            ),
            80 => 
            array (
                'id' => 81,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'updated',
                'auditable_type' => 'App\\User',
                'auditable_id' => 1,
                'old_values' => '{"remember_token":"PZbBo3U7RGTXKlQGkwBAsaUiShG3n5nJ370NdcmX1U25bMFM6wW1VcwaM0il"}',
                'new_values' => '{"remember_token":"KKxj9D9BZIwDvSDG9ddlwLGtt1nKSxiVonuzk6EKUK6bu8Gb2LdpjnMs8wEe"}',
                'url' => 'http://localhost/logout?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-13 14:20:10',
                'updated_at' => '2019-02-13 14:20:10',
            ),
            81 => 
            array (
                'id' => 82,
                'user_type' => 'App\\User',
                'user_id' => 2,
                'event' => 'updated',
                'auditable_type' => 'App\\User',
                'auditable_id' => 2,
                'old_values' => '{"remember_token":"oPX1sDHRxLes6toEjvaEnZaxV9by3fBgPEufW1A78Tz0PSyVo0bxKyj78GpS"}',
                'new_values' => '{"remember_token":"LBAjyfcdAUcEZoZvHTKRilPGawQQKUzFzf2bOsB8AYPmM0fpXduTIay2iIGo"}',
                'url' => 'http://localhost/logout?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-13 14:21:13',
                'updated_at' => '2019-02-13 14:21:13',
            ),
            82 => 
            array (
                'id' => 83,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\HistoricoPT',
                'auditable_id' => 5,
                'old_values' => '[]',
                'new_values' => '{"pessoa_id":"2","turma_id":"3","inativo":"1","comentario":null,"id":5}',
                'url' => 'http://localhost/pessoas_turmas/vincular?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-13 14:31:56',
                'updated_at' => '2019-02-13 14:31:56',
            ),
            83 => 
            array (
                'id' => 84,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\HistoricoPT',
                'auditable_id' => 6,
                'old_values' => '[]',
                'new_values' => '{"pessoa_id":"2","turma_id":"4","inativo":"1","comentario":null,"id":6}',
                'url' => 'http://localhost/pessoas_turmas/vincular?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-13 14:31:59',
                'updated_at' => '2019-02-13 14:31:59',
            ),
            84 => 
            array (
                'id' => 85,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'updated',
                'auditable_type' => 'App\\Quant',
                'auditable_id' => 1,
                'old_values' => '{"quantidade":2}',
                'new_values' => '{"quantidade":"3"}',
                'url' => 'http://localhost/pessoa/quantidade?_token=zq7L49mKAWkEhmSGsYDfpc9PxG8QKZN09DeWxFcp&pessoa_id=2&quantidade=3',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-13 14:32:13',
                'updated_at' => '2019-02-13 14:32:13',
            ),
            85 => 
            array (
                'id' => 86,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\HistoricoPT',
                'auditable_id' => 7,
                'old_values' => '[]',
                'new_values' => '{"pessoa_id":"2","turma_id":"7","inativo":"1","comentario":null,"id":7}',
                'url' => 'http://localhost/pessoas_turmas/vincular?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-13 14:32:16',
                'updated_at' => '2019-02-13 14:32:16',
            ),
            86 => 
            array (
                'id' => 87,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'updated',
                'auditable_type' => 'App\\Nucleo',
                'auditable_id' => 1,
                'old_values' => '{"inativo":2}',
                'new_values' => '{"inativo":1}',
                'url' => 'http://localhost/nucleos/ativar_inativar?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-13 14:32:35',
                'updated_at' => '2019-02-13 14:32:35',
            ),
            87 => 
            array (
                'id' => 88,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\HistoricoN',
                'auditable_id' => 2,
                'old_values' => '[]',
                'new_values' => '{"nucleo_id":"1","comentario":null,"inativo":1,"id":2}',
                'url' => 'http://localhost/nucleos/ativar_inativar?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-13 14:32:36',
                'updated_at' => '2019-02-13 14:32:36',
            ),
            88 => 
            array (
                'id' => 89,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'updated',
                'auditable_type' => 'App\\Anamnese',
                'auditable_id' => 1,
                'old_values' => '{"peso":68}',
                'new_values' => '{"peso":"0"}',
                'url' => 'http://localhost/anamneses/1?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-14 09:47:21',
                'updated_at' => '2019-02-14 09:47:21',
            ),
            89 => 
            array (
                'id' => 90,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Turma',
                'auditable_id' => 8,
                'old_values' => '[]',
                'new_values' => '{"nome":"gsddg","limite":"88","horario_inicial":"08:17:00","horario_final":"08:18:00","data_semanal":"Ter\\u00e7a,Quinta,","nucleo_id":"2","descricao":null,"id":8}',
                'url' => 'http://localhost/turmas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-14 10:19:01',
                'updated_at' => '2019-02-14 10:19:01',
            ),
            90 => 
            array (
                'id' => 91,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'updated',
                'auditable_type' => 'App\\Nucleo',
                'auditable_id' => 4,
                'old_values' => '{"nome":"N\\u00facleo Sul","bairro":"CAMPINA"}',
                'new_values' => '{"nome":"N\\u00facleo Sul 1","bairro":"BOA VISTA"}',
                'url' => 'http://localhost/nucleos/4?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Mobile Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-14 11:10:36',
                'updated_at' => '2019-02-14 11:10:36',
            ),
            91 => 
            array (
                'id' => 92,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'updated',
                'auditable_type' => 'App\\Nucleo',
                'auditable_id' => 4,
                'old_values' => '{"nome":"N\\u00facleo Sul 1"}',
                'new_values' => '{"nome":"N\\u00facleo Sul"}',
                'url' => 'http://localhost/nucleos/4?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2019-02-14 11:38:56',
                'updated_at' => '2019-02-14 11:38:56',
            ),
        ));
        
        
    }
}